package script

import "testing"

// scriptOpcodeMap254Pin pins every compiler-visible opcode name to its 254
// numeric value. Generated from TS ScriptOpcode.ts at pin 43e02957 (enum
// values + ScriptOpcodeMap keys, including the four '*' vararg keys).
// 254 inserts STAT_TOTAL (2102, after STAT) and SET_PLAYER_OP (2133, after
// IF_SETSCROLLPOS): the implicitly-numbered player-ops run STAT_ADD..
// IF_SETSCROLLPOS shifts +1 and the four *QUEUEVARARG tail ops shift +2
// (2134-2137). PUSH_VARBIT (25) / POP_VARBIT (27) restored at 254.
// Regenerate ONLY when REFERENCES.md moves the rev-254 pin.
var scriptOpcodeMap254Pin = map[string]Opcode{
	"PUSH_CONSTANT_INT":             0,
	"PUSH_VARP":                     1,
	"POP_VARP":                      2,
	"PUSH_CONSTANT_STRING":          3,
	"PUSH_VARN":                     4,
	"POP_VARN":                      5,
	"BRANCH":                        6,
	"BRANCH_NOT":                    7,
	"BRANCH_EQUALS":                 8,
	"BRANCH_LESS_THAN":              9,
	"BRANCH_GREATER_THAN":           10,
	"PUSH_VARS":                     11,
	"POP_VARS":                      12,
	"RETURN":                        21,
	"GOSUB":                         22,
	"JUMP":                          23,
	"SWITCH":                        24,
	"PUSH_VARBIT":                   25,
	"POP_VARBIT":                    27,
	"BRANCH_LESS_THAN_OR_EQUALS":    31,
	"BRANCH_GREATER_THAN_OR_EQUALS": 32,
	"PUSH_INT_LOCAL":                33,
	"POP_INT_LOCAL":                 34,
	"PUSH_STRING_LOCAL":             35,
	"POP_STRING_LOCAL":              36,
	"JOIN_STRING":                   37,
	"POP_INT_DISCARD":               38,
	"POP_STRING_DISCARD":            39,
	"GOSUB_WITH_PARAMS":             40,
	"JUMP_WITH_PARAMS":              41,
	"DEFINE_ARRAY":                  44,
	"PUSH_ARRAY_INT":                45,
	"POP_ARRAY_INT":                 46,
	"COORDX":                        1000,
	"COORDY":                        1001,
	"COORDZ":                        1002,
	"DISTANCE":                      1003,
	"HUNTALL":                       1004,
	"HUNTNEXT":                      1005,
	"INZONE":                        1006,
	"LINEOFSIGHT":                   1007,
	"LINEOFWALK":                    1008,
	"MAP_BLOCKED":                   1009,
	"MAP_INDOORS":                   1010,
	"MAP_CLOCK":                     1011,
	"MAP_LOCADDUNSAFE":              1012,
	"MAP_MEMBERS":                   1013,
	"MAP_PLAYERCOUNT":               1014,
	"MAP_FINDSQUARE":                1015,
	"MOVECOORD":                     1016,
	"PLAYERCOUNT":                   1017,
	"PROJANIM_MAP":                  1018,
	"PROJANIM_NPC":                  1019,
	"PROJANIM_PL":                   1020,
	"SEQLENGTH":                     1021,
	"SPLIT_GET":                     1022,
	"SPLIT_GETANIM":                 1023,
	"SPLIT_INIT":                    1024,
	"SPLIT_LINECOUNT":               1025,
	"SPLIT_PAGECOUNT":               1026,
	"SPOTANIM_MAP":                  1027,
	"STRUCT_PARAM":                  1028,
	"WORLD_DELAY":                   1029,
	"NPCCOUNT":                      1030,
	"ZONECOUNT":                     1031,
	"LOCCOUNT":                      1032,
	"OBJCOUNT":                      1033,
	"MAP_MULTIWAY":                  1034,
	"ALLOWDESIGN":                   2000,
	"ANIM":                          2001,
	"BAS_READYANIM":                 2002,
	"BAS_RUNNING":                   2003,
	"BAS_TURNONSPOT":                2004,
	"BAS_WALK_B":                    2005,
	"BAS_WALK_F":                    2006,
	"BAS_WALK_L":                    2007,
	"BAS_WALK_R":                    2008,
	"BUFFER_FULL":                   2009,
	"BUILDAPPEARANCE":               2010,
	"BUSY":                          2011,
	"CAM_LOOKAT":                    2012,
	"CAM_MOVETO":                    2013,
	"CAM_RESET":                     2014,
	"CAM_SHAKE":                     2015,
	"CLEARQUEUE":                    2016,
	"CLEARSOFTTIMER":                2017,
	"CLEARTIMER":                    2018,
	"GETTIMER":                      2019,
	"COORD":                         2020,
	"DAMAGE":                        2021,
	"DISPLAYNAME":                   2022,
	"FACESQUARE":                    2023,
	"FINDUID":                       2024,
	"GENDER":                        2025,
	"GETQUEUE":                      2026,
	"STAT_ADVANCE":                  2027,
	"HEADICONS_GET":                 2028,
	"HEADICONS_SET":                 2029,
	"HEALENERGY":                    2030,
	"HINT_COORD":                    2031,
	"HINT_NPC":                      2032,
	"HINT_PLAYER":                   2033,
	"HINT_STOP":                     2034,
	"IF_CLOSE":                      2035,
	"TUT_CLOSE":                     2036,
	"IF_MULTIZONE":                  2037,
	"IF_OPENCHAT":                   2038,
	"TUT_OPEN":                      2039,
	"IF_OPENMAIN":                   2040,
	"IF_OPENMAIN_SIDE":              2042,
	"IF_OPENOVERLAY":                2041,
	"IF_OPENSIDE":                   2043,
	"IF_SETANIM":                    2044,
	"IF_SETCOLOUR":                  2045,
	"IF_SETHIDE":                    2046,
	"IF_SETMODEL":                   2047,
	"IF_SETNPCHEAD":                 2048,
	"IF_SETOBJECT":                  2049,
	"IF_SETPLAYERHEAD":              2050,
	"IF_SETPOSITION":                2051,
	"IF_SETRESUMEBUTTONS":           2052,
	"IF_SETTAB":                     2053,
	"IF_SETTABACTIVE":               2054,
	"TUT_FLASH":                     2055,
	"IF_SETTEXT":                    2056,
	"LAST_LOGIN_INFO":               2057,
	"LAST_COM":                      2058,
	"LAST_INT":                      2059,
	"LAST_ITEM":                     2060,
	"LAST_SLOT":                     2061,
	"LAST_TARGETSLOT":               2062,
	"LAST_USEITEM":                  2063,
	"LAST_USESLOT":                  2064,
	"LONGQUEUE":                     2065,
	"LONGQUEUE*":                    2135,
	"MES":                           2066,
	"MIDI_JINGLE":                   2067,
	"MIDI_SONG":                     2068,
	"NAME":                          2069,
	"P_APRANGE":                     2070,
	"P_ARRIVEDELAY":                 2071,
	"P_COUNTDIALOG":                 2072,
	"P_DELAY":                       2073,
	"P_EXACTMOVE":                   2074,
	"P_FINDUID":                     2075,
	"P_LOCMERGE":                    2076,
	"P_LOGOUT":                      2077,
	"P_PREVENTLOGOUT":               2078,
	"P_OPHELD":                      2079,
	"P_OPLOC":                       2080,
	"P_OPNPC":                       2081,
	"P_OPNPCT":                      2082,
	"P_OPOBJ":                       2083,
	"P_OPPLAYER":                    2084,
	"P_OPPLAYERT":                   2085,
	"P_PAUSEBUTTON":                 2086,
	"P_STOPACTION":                  2087,
	"P_TELEJUMP":                    2088,
	"P_TELEPORT":                    2089,
	"P_WALK":                        2090,
	"PLAYER_FINDALLZONE":            2091,
	"PLAYER_FINDNEXT":               2092,
	"QUEUE":                         2093,
	"QUEUE*":                        2134,
	"SAY":                           2094,
	"WALKTRIGGER":                   2095,
	"SETTIMER":                      2096,
	"SOFTTIMER":                     2097,
	"SOUND_SYNTH":                   2098,
	"SPOTANIM_PL":                   2099,
	"STAFFMODLEVEL":                 2100,
	"STAT":                          2101,
	"STAT_TOTAL":                    2102,
	"STAT_ADD":                      2103,
	"STAT_BASE":                     2104,
	"STAT_HEAL":                     2105,
	"STAT_SUB":                      2106,
	"STAT_BOOST":                    2107,
	"STAT_DRAIN":                    2108,
	"STAT_RANDOM":                   2109,
	"STRONGQUEUE":                   2110,
	"STRONGQUEUE*":                  2137,
	"UID":                           2111,
	"WEAKQUEUE":                     2112,
	"WEAKQUEUE*":                    2136,
	"IF_OPENMAINOVERLAY":            2113,
	"AFK_EVENT":                     2114,
	"LOWMEMORY":                     2115,
	"SETIDKIT":                      2116,
	"P_CLEARPENDINGACTION":          2117,
	"GETWALKTRIGGER":                2118,
	"BUSY2":                         2119,
	"FINDHERO":                      2120,
	"BOTH_HEROPOINTS":               2121,
	"SETGENDER":                     2122,
	"SETSKINCOLOUR":                 2123,
	"P_ANIMPROTECT":                 2124,
	"RUNENERGY":                     2125,
	"WEIGHT":                        2126,
	"LAST_COORD":                    2127,
	"SESSION_LOG":                   2128,
	"WEALTH_EVENT":                  2129,
	"P_RUN":                         2130,
	"PLAYERMEMBER":                  2131,
	"IF_SETSCROLLPOS":               2132,
	"SET_PLAYER_OP":                 2133,
	"NPC_ADD":                       2500,
	"NPC_ANIM":                      2501,
	"NPC_BASESTAT":                  2502,
	"NPC_CATEGORY":                  2503,
	"NPC_CHANGETYPE":                2504,
	"NPC_CHANGETYPE_KEEPALL":        2505,
	"NPC_COORD":                     2506,
	"NPC_DAMAGE":                    2507,
	"NPC_DEL":                       2508,
	"NPC_DELAY":                     2509,
	"NPC_FACESQUARE":                2510,
	"NPC_FIND":                      2511,
	"NPC_FINDCAT":                   2512,
	"NPC_FINDALLANY":                2513,
	"NPC_FINDALL":                   2514,
	"NPC_FINDEXACT":                 2515,
	"NPC_FINDHERO":                  2516,
	"NPC_FINDALLZONE":               2517,
	"NPC_FINDNEXT":                  2518,
	"NPC_FINDUID":                   2519,
	"NPC_GETMODE":                   2520,
	"NPC_HEROPOINTS":                2521,
	"NPC_NAME":                      2522,
	"NPC_PARAM":                     2523,
	"NPC_QUEUE":                     2524,
	"NPC_RANGE":                     2525,
	"NPC_SAY":                       2526,
	"NPC_HUNT":                      2527,
	"NPC_HUNTALL":                   2528,
	"NPC_HUNTNEXT":                  2529,
	"NPC_SETHUNT":                   2530,
	"NPC_SETHUNTMODE":               2531,
	"NPC_SETMODE":                   2532,
	"NPC_WALKTRIGGER":               2533,
	"NPC_SETTIMER":                  2534,
	"NPC_STAT":                      2535,
	"NPC_STATADD":                   2536,
	"NPC_STATHEAL":                  2537,
	"NPC_STATSUB":                   2538,
	"NPC_TELE":                      2539,
	"NPC_TYPE":                      2540,
	"NPC_UID":                       2541,
	"SPOTANIM_NPC":                  2542,
	"NPC_WALK":                      2543,
	"NPC_ATTACKRANGE":               2544,
	"NPC_HASOP":                     2545,
	"NPC_ARRIVEDELAY":               2546,
	"NPC_INRANGE":                   2547,
	"LOC_ADD":                       3000,
	"LOC_ANGLE":                     3001,
	"LOC_ANIM":                      3002,
	"LOC_CATEGORY":                  3003,
	"LOC_CHANGE":                    3004,
	"LOC_COORD":                     3005,
	"LOC_DEL":                       3006,
	"LOC_FIND":                      3007,
	"LOC_FINDALLZONE":               3008,
	"LOC_FINDNEXT":                  3009,
	"LOC_NAME":                      3010,
	"LOC_PARAM":                     3011,
	"LOC_SHAPE":                     3012,
	"LOC_TYPE":                      3013,
	"OBJ_ADD":                       3500,
	"OBJ_ADDALL":                    3501,
	"OBJ_FIND":                      3509,
	"OBJ_FINDALLZONE":               3510,
	"OBJ_FINDNEXT":                  3511,
	"OBJ_COORD":                     3502,
	"OBJ_COUNT":                     3503,
	"OBJ_DEL":                       3504,
	"OBJ_NAME":                      3505,
	"OBJ_PARAM":                     3506,
	"OBJ_TAKEITEM":                  3507,
	"OBJ_TYPE":                      3508,
	"NC_CATEGORY":                   4000,
	"NC_DEBUGNAME":                  4001,
	"NC_DESC":                       4002,
	"NC_NAME":                       4003,
	"NC_OP":                         4004,
	"NC_PARAM":                      4005,
	"NC_SIZE":                       4006,
	"NC_VISLEVEL":                   4007,
	"LC_CATEGORY":                   4100,
	"LC_DEBUGNAME":                  4101,
	"LC_DESC":                       4102,
	"LC_NAME":                       4103,
	"LC_OP":                         4104,
	"LC_PARAM":                      4105,
	"LC_WIDTH":                      4106,
	"LC_LENGTH":                     4107,
	"OC_CATEGORY":                   4200,
	"OC_CERT":                       4201,
	"OC_COST":                       4202,
	"OC_DEBUGNAME":                  4203,
	"OC_DESC":                       4204,
	"OC_IOP":                        4205,
	"OC_MEMBERS":                    4206,
	"OC_NAME":                       4207,
	"OC_OP":                         4208,
	"OC_PARAM":                      4209,
	"OC_STACKABLE":                  4210,
	"OC_TRADEABLE":                  4211,
	"OC_UNCERT":                     4212,
	"OC_WEARPOS2":                   4213,
	"OC_WEARPOS3":                   4214,
	"OC_WEARPOS":                    4215,
	"OC_WEIGHT":                     4216,
	"INV_ALLSTOCK":                  4300,
	"INV_SIZE":                      4301,
	"INV_STOCKBASE":                 4302,
	"INV_ADD":                       4303,
	"INV_CHANGESLOT":                4304,
	"INV_CLEAR":                     4305,
	"INV_DEL":                       4306,
	"INV_DELSLOT":                   4307,
	"INV_DROPITEM":                  4308,
	"INV_DROPITEM_DELAYED":          4309,
	"INV_DROPSLOT":                  4310,
	"INV_FREESPACE":                 4311,
	"INV_GETNUM":                    4312,
	"INV_GETOBJ":                    4313,
	"INV_ITEMSPACE":                 4314,
	"INV_ITEMSPACE2":                4315,
	"INV_MOVEFROMSLOT":              4316,
	"INV_MOVETOSLOT":                4317,
	"BOTH_MOVEINV":                  4318,
	"INV_MOVEITEM":                  4319,
	"INV_MOVEITEM_CERT":             4320,
	"INV_MOVEITEM_UNCERT":           4321,
	"INV_SETSLOT":                   4322,
	"INV_TOTAL":                     4323,
	"INV_TOTALCAT":                  4324,
	"INV_TRANSMIT":                  4325,
	"INVOTHER_TRANSMIT":             4326,
	"INV_STOPTRANSMIT":              4327,
	"BOTH_DROPSLOT":                 4328,
	"INV_DROPALL":                   4329,
	"INV_TOTALPARAM":                4330,
	"INV_TOTALPARAM_STACK":          4331,
	"INV_DEBUGNAME":                 4332,
	"ENUM":                          4400,
	"ENUM_GETOUTPUTCOUNT":           4401,
	"APPEND_NUM":                    4500,
	"APPEND":                        4501,
	"APPEND_SIGNNUM":                4502,
	"LOWERCASE":                     4503,
	"TEXT_GENDER":                   4504,
	"TOSTRING":                      4505,
	"COMPARE":                       4506,
	"TEXT_SWITCH":                   4507,
	"APPEND_CHAR":                   4508,
	"STRING_LENGTH":                 4509,
	"SUBSTRING":                     4510,
	"STRING_INDEXOF_CHAR":           4511,
	"STRING_INDEXOF_STRING":         4512,
	"ADD":                           4600,
	"SUB":                           4601,
	"MULTIPLY":                      4602,
	"DIVIDE":                        4603,
	"RANDOM":                        4604,
	"RANDOMINC":                     4605,
	"INTERPOLATE":                   4606,
	"ADDPERCENT":                    4607,
	"SETBIT":                        4608,
	"CLEARBIT":                      4609,
	"TESTBIT":                       4610,
	"MODULO":                        4611,
	"POW":                           4612,
	"INVPOW":                        4613,
	"AND":                           4614,
	"OR":                            4615,
	"MIN":                           4616,
	"MAX":                           4617,
	"SCALE":                         4618,
	"BITCOUNT":                      4619,
	"TOGGLEBIT":                     4620,
	"SETBIT_RANGE":                  4621,
	"CLEARBIT_RANGE":                4622,
	"GETBIT_RANGE":                  4623,
	"SETBIT_RANGE_TOINT":            4624,
	"SIN_DEG":                       4625,
	"COS_DEG":                       4626,
	"ATAN2_DEG":                     4627,
	"ABS":                           4628,
	"DB_FIND_WITH_COUNT":            7500,
	"DB_FINDNEXT":                   7501,
	"DB_GETFIELD":                   7502,
	"DB_GETFIELDCOUNT":              7503,
	"DB_LISTALL_WITH_COUNT":         7504,
	"DB_GETROWTABLE":                7505,
	"DB_FINDBYINDEX":                7506,
	"DB_FIND_REFINE_WITH_COUNT":     7507,
	"DB_FIND":                       7508,
	"DB_FIND_REFINE":                7509,
	"DB_LISTALL":                    7510,
	"ERROR":                         10000,
	"MAP_PRODUCTION":                10001,
	"MAP_LASTCLOCK":                 10002,
	"MAP_LASTWORLD":                 10003,
	"MAP_LASTCLIENTIN":              10004,
	"MAP_LASTNPC":                   10005,
	"MAP_LASTPLAYER":                10006,
	"MAP_LASTLOGOUT":                10007,
	"MAP_LASTLOGIN":                 10008,
	"MAP_LASTZONE":                  10009,
	"MAP_LASTCLIENTOUT":             10010,
	"MAP_LASTCLEANUP":               10011,
	"MAP_LASTBANDWIDTHIN":           10012,
	"MAP_LASTBANDWIDTHOUT":          10013,
	"TIMESPENT":                     10014,
	"GETTIMESPENT":                  10015,
	"CONSOLE":                       10016,
}

// removed254Names were deleted/renamed upstream and must NOT resolve.
// PUSH_VARBIT/POP_VARBIT and STAT_TOTAL left this list at 254 — all three
// restored upstream (ScriptOpcode.ts:20-21,179 @43e02957).
var removed254Names = []string{
	"MAP_LIVE", "IF_SETRECOL",
	"HINT_PL", "LOWMEM", "READYANIM", "RUNANIM", "TURNANIM",
	"WALKANIM", "WALKANIM_B", "WALKANIM_L", "WALKANIM_R",
}

func TestScriptOpcodeMap_254Pin(t *testing.T) {
	for name, want := range scriptOpcodeMap254Pin {
		got, ok := ScriptOpcodeMap[name]
		if !ok {
			t.Errorf("ScriptOpcodeMap missing %q", name)
			continue
		}
		if got != want {
			t.Errorf("ScriptOpcodeMap[%q] = %d, want %d", name, got, want)
		}
	}
	if len(ScriptOpcodeMap) != len(scriptOpcodeMap254Pin) {
		t.Errorf("ScriptOpcodeMap has %d entries, 254 pin has %d", len(ScriptOpcodeMap), len(scriptOpcodeMap254Pin))
	}
	for _, name := range removed254Names {
		if _, ok := ScriptOpcodeMap[name]; ok {
			t.Errorf("ScriptOpcodeMap still contains removed name %q", name)
		}
	}
}

func TestOpcodeString_254Pin(t *testing.T) {
	for name, op := range scriptOpcodeMap254Pin {
		if name[len(name)-1] == '*' {
			continue // vararg map keys; String() keeps the enum spelling
		}
		if got := op.String(); got != name {
			t.Errorf("Opcode(%d).String() = %q, want %q", op, got, name)
		}
	}
}
