package script

import "testing"

// scriptOpcodeMap274Pin pins every compiler-visible opcode name to its 274
// numeric value. Generated from TS ScriptOpcode.ts at pin dee467c8 (enum
// values + ScriptOpcodeMap keys, including the four '*' vararg keys). 400
// entries (enum and map counts are equal at this pin; the 2e3bcf43 table
// had 396 — rev-274 adds MAP_LOC, MINIMAP_TOGGLE, SET_SKILL_LEVEL and
// NPC_DESTINATION, and renames SETSKINCOLOUR to SETIDKCOLOUR in place).
// Regenerate ONLY when REFERENCES.md moves the rev-274 pin.
var scriptOpcodeMap274Pin = map[string]Opcode{
	"PUSH_CONSTANT_INT":             0,
	"PUSH_VARP":                     1,
	"POP_VARP":                      2,
	"PUSH_CONSTANT_STRING":          3,
	"PUSH_VARN":                     4,
	"POP_VARN":                      5,
	"BRANCH":                        6,
	"BRANCH_NOT":                    7,
	"BRANCH_EQUALS":                 8,
	"BRANCH_LESS_THAN":              9,
	"BRANCH_GREATER_THAN":           10,
	"PUSH_VARS":                     11,
	"POP_VARS":                      12,
	"RETURN":                        21,
	"GOSUB":                         22,
	"JUMP":                          23,
	"SWITCH":                        24,
	"PUSH_VARBIT":                   25,
	"POP_VARBIT":                    27,
	"BRANCH_LESS_THAN_OR_EQUALS":    31,
	"BRANCH_GREATER_THAN_OR_EQUALS": 32,
	"PUSH_INT_LOCAL":                33,
	"POP_INT_LOCAL":                 34,
	"PUSH_STRING_LOCAL":             35,
	"POP_STRING_LOCAL":              36,
	"JOIN_STRING":                   37,
	"POP_INT_DISCARD":               38,
	"POP_STRING_DISCARD":            39,
	"GOSUB_WITH_PARAMS":             40,
	"JUMP_WITH_PARAMS":              41,
	"DEFINE_ARRAY":                  44,
	"PUSH_ARRAY_INT":                45,
	"POP_ARRAY_INT":                 46,
	"COORDX":                        1000,
	"COORDY":                        1001,
	"COORDZ":                        1002,
	"DISTANCE":                      1003,
	"INZONE":                        1004,
	"LINEOFSIGHT":                   1005,
	"LINEOFWALK":                    1006,
	"MAP_BLOCKED":                   1007,
	"MAP_CLOCK":                     1008,
	"MAP_FINDSQUARE":                1009,
	"MAP_INDOORS":                   1010,
	"MAP_LIVE":                      1011,
	"MAP_LOCADDUNSAFE":              1012,
	"MAP_LOC":                       1013,
	"MAP_MEMBERS":                   1014,
	"MAP_MULTIWAY":                  1015,
	"MAP_PLAYERCOUNT":               1016,
	"MOVECOORD":                     1017,
	"PLAYERCOUNT":                   1018,
	"PROJANIM_MAP":                  1019,
	"SEQLENGTH":                     1020,
	"SPOTANIM_MAP":                  1021,
	"WORLD_DELAY":                   1022,
	"MIDI_LENGTH":                   1023,
	"AFK_EVENT":                     2000,
	"ALLOWDESIGN":                   2001,
	"ANIM":                          2002,
	"BOTH_HEROPOINTS":               2003,
	"BUILDAPPEARANCE":               2004,
	"BUSY":                          2005,
	"BUSY2":                         2006,
	"CAM_LOOKAT":                    2007,
	"CAM_MOVETO":                    2008,
	"CAM_RESET":                     2009,
	"CAM_SHAKE":                     2010,
	"CLEARQUEUE":                    2011,
	"CLEARSOFTTIMER":                2012,
	"CLEARTIMER":                    2013,
	"COORD":                         2014,
	"DAMAGE":                        2015,
	"DISPLAYNAME":                   2016,
	"FACESQUARE":                    2017,
	"FINDHERO":                      2018,
	"FINDUID":                       2019,
	"GENDER":                        2020,
	"GETQUEUE":                      2021,
	"GETTIMER":                      2022,
	"GETWALKTRIGGER":                2023,
	"HEADICONS_GET":                 2024,
	"HEADICONS_SET":                 2025,
	"HEALENERGY":                    2026,
	"HINT_COORD":                    2027,
	"HINT_NPC":                      2028,
	"HINT_PL":                       2029,
	"HINT_STOP":                     2030,
	"HUNTALL":                       2031,
	"HUNTNEXT":                      2032,
	"IF_CLOSE":                      2033,
	"IF_OPENCHAT":                   2034,
	"IF_OPENMAIN_SIDE":              2035,
	"IF_OPENMAIN":                   2036,
	"IF_OPENOVERLAY":                2037,
	"IF_OPENSIDE":                   2038,
	"IF_SETANIM":                    2039,
	"IF_SETCOLOUR":                  2040,
	"IF_SETHIDE":                    2041,
	"IF_SETMODEL":                   2042,
	"IF_SETNPCHEAD":                 2043,
	"IF_SETOBJECT":                  2044,
	"IF_SETPLAYERHEAD":              2045,
	"IF_SETPOSITION":                2046,
	"IF_ADDRESUMEBUTTON":            2047,
	"IF_SETSCROLLPOS":               2048,
	"IF_SETTAB":                     2049,
	"IF_SETTABACTIVE":               2050,
	"IF_SETTEXT":                    2051,
	"LAST_COM":                      2052,
	"LAST_INT":                      2053,
	"LAST_ITEM":                     2054,
	"LAST_LOGIN_INFO":               2055,
	"LAST_SLOT":                     2056,
	"LAST_TARGETSLOT":               2057,
	"LAST_USEITEM":                  2058,
	"LAST_USESLOT":                  2059,
	"LONGQUEUE":                     2060,
	"LONGQUEUE*":                    2061,
	"LOWMEM":                        2062,
	"MES":                           2063,
	"MIDI_JINGLE":                   2064,
	"MIDI_SONG":                     2065,
	"MINIMAP_TOGGLE":                2066,
	"NAME":                          2067,
	"P_ANIMPROTECT":                 2068,
	"P_APRANGE":                     2069,
	"P_ARRIVEDELAY":                 2070,
	"P_CLEARPENDINGACTION":          2071,
	"P_COUNTDIALOG":                 2072,
	"P_DELAY":                       2073,
	"P_EXACTMOVE":                   2074,
	"P_FINDUID":                     2075,
	"P_LOCMERGE":                    2076,
	"P_LOGOUT":                      2077,
	"P_OPHELD":                      2078,
	"P_OPLOC":                       2079,
	"P_OPNPC":                       2080,
	"P_OPNPCT":                      2081,
	"P_OPOBJ":                       2082,
	"P_OPPLAYER":                    2083,
	"P_OPPLAYERT":                   2084,
	"P_PAUSEBUTTON":                 2085,
	"P_PREVENTLOGOUT":               2086,
	"P_RUN":                         2087,
	"P_STOPACTION":                  2088,
	"P_TELEJUMP":                    2089,
	"P_TELEPORT":                    2090,
	"P_WALK":                        2091,
	"PLAYERMEMBER":                  2092,
	"PROJANIM_NPC":                  2547,
	"PROJANIM_PL":                   2093,
	"QUEUE":                         2094,
	"QUEUE*":                        2095,
	"READYANIM":                     2096,
	"RUNANIM":                       2097,
	"RUNENERGY":                     2098,
	"SAY":                           2099,
	"SESSION_LOG":                   2100,
	"SET_PLAYER_OP":                 2101,
	"SETGENDER":                     2102,
	"SETIDKIT":                      2103,
	"SET_SKILL_LEVEL":               2104,
	"SETIDKCOLOUR":                  2105,
	"SETTIMER":                      2106,
	"SOFTTIMER":                     2107,
	"SOUND_SYNTH":                   2108,
	"SPLIT_GET":                     4513,
	"SPLIT_GETANIM":                 4514,
	"SPLIT_INIT":                    4515,
	"SPLIT_LINECOUNT":               4516,
	"SPLIT_PAGECOUNT":               4517,
	"SPOTANIM_PL":                   2109,
	"STAFFMODLEVEL":                 2110,
	"STAT_ADD":                      2111,
	"STAT_ADVANCE":                  2112,
	"STAT_BASE":                     2113,
	"STAT_BOOST":                    2114,
	"STAT_DRAIN":                    2115,
	"STAT_HEAL":                     2116,
	"STAT_RANDOM":                   2117,
	"STAT_SUB":                      2118,
	"STAT_TOTAL":                    2119,
	"STAT":                          2120,
	"STRONGQUEUE":                   2121,
	"STRONGQUEUE*":                  2122,
	"TURNANIM":                      2123,
	"TUT_CLOSE":                     2124,
	"TUT_FLASH":                     2125,
	"TUT_OPEN":                      2126,
	"UID":                           2127,
	"WALKANIM_B":                    2128,
	"WALKANIM_L":                    2129,
	"WALKANIM_R":                    2130,
	"WALKANIM":                      2131,
	"WALKTRIGGER":                   2132,
	"WEAKQUEUE":                     2133,
	"WEAKQUEUE*":                    2134,
	"WEALTH_EVENT":                  2135,
	"WEIGHT":                        2136,
	"NPC_ADD":                       2500,
	"NPC_ANIM":                      2501,
	"NPC_ARRIVEDELAY":               2502,
	"NPC_ATTACKRANGE":               2503,
	"NPC_BASESTAT":                  2504,
	"NPC_CATEGORY":                  2505,
	"NPC_CHANGETYPE_KEEPALL":        2506,
	"NPC_CHANGETYPE":                2507,
	"NPC_COORD":                     2508,
	"NPC_DAMAGE":                    2509,
	"NPC_DEL":                       2510,
	"NPC_DELAY":                     2511,
	"NPC_FACESQUARE":                2512,
	"NPC_FIND":                      2513,
	"NPC_FINDALL":                   2514,
	"NPC_FINDALLANY":                2515,
	"NPC_FINDALLZONE":               2516,
	"NPC_FINDCAT":                   2517,
	"NPC_FINDEXACT":                 2518,
	"NPC_FINDHERO":                  2519,
	"NPC_FINDNEXT":                  2520,
	"NPC_FINDUID":                   2521,
	"NPC_GETMODE":                   2522,
	"NPC_HASOP":                     2523,
	"NPC_HEROPOINTS":                2524,
	"NPC_HUNT":                      2525,
	"NPC_HUNTALL":                   2526,
	"NPC_INRANGE":                   2527,
	"NPC_DESTINATION":               2528,
	"NPC_NAME":                      2529,
	"NPC_PARAM":                     2530,
	"NPC_QUEUE":                     2531,
	"NPC_RANGE":                     2532,
	"NPC_SAY":                       2533,
	"NPC_SETHUNT":                   2534,
	"NPC_SETHUNTMODE":               2535,
	"NPC_SETMODE":                   2536,
	"NPC_SETTIMER":                  2537,
	"NPC_STAT":                      2538,
	"NPC_STATADD":                   2539,
	"NPC_STATHEAL":                  2540,
	"NPC_STATSUB":                   2541,
	"NPC_TELE":                      2542,
	"NPC_TYPE":                      2543,
	"NPC_UID":                       2544,
	"NPC_WALK":                      2545,
	"NPC_WALKTRIGGER":               2546,
	"SPOTANIM_NPC":                  2548,
	"LOC_ADD":                       3000,
	"LOC_ANGLE":                     3001,
	"LOC_ANIM":                      3002,
	"LOC_CATEGORY":                  3003,
	"LOC_CHANGE":                    3004,
	"LOC_COORD":                     3005,
	"LOC_DEL":                       3006,
	"LOC_FIND":                      3007,
	"LOC_FINDALLZONE":               3008,
	"LOC_FINDNEXT":                  3009,
	"LOC_NAME":                      3010,
	"LOC_PARAM":                     3011,
	"LOC_SHAPE":                     3012,
	"LOC_TYPE":                      3013,
	"OBJ_ADD":                       3500,
	"OBJ_ADDALL":                    3501,
	"OBJ_COORD":                     3502,
	"OBJ_COUNT":                     3503,
	"OBJ_DEL":                       3504,
	"OBJ_FIND":                      3505,
	"OBJ_FINDALLZONE":               3506,
	"OBJ_FINDNEXT":                  3507,
	"OBJ_NAME":                      3508,
	"OBJ_PARAM":                     3509,
	"OBJ_TAKEITEM":                  3510,
	"OBJ_TYPE":                      3511,
	"NC_CATEGORY":                   4000,
	"NC_DEBUGNAME":                  4001,
	"NC_DESC":                       4002,
	"NC_NAME":                       4003,
	"NC_OP":                         4004,
	"NC_PARAM":                      4005,
	"NC_SIZE":                       4006,
	"NC_VISLEVEL":                   4007,
	"LC_CATEGORY":                   4100,
	"LC_DEBUGNAME":                  4101,
	"LC_DESC":                       4102,
	"LC_LENGTH":                     4103,
	"LC_NAME":                       4104,
	"LC_OP":                         4105,
	"LC_PARAM":                      4106,
	"LC_WIDTH":                      4107,
	"OC_CATEGORY":                   4200,
	"OC_CERT":                       4201,
	"OC_COST":                       4202,
	"OC_DEBUGNAME":                  4203,
	"OC_DESC":                       4204,
	"OC_IOP":                        4205,
	"OC_MEMBERS":                    4206,
	"OC_NAME":                       4207,
	"OC_OP":                         4208,
	"OC_PARAM":                      4209,
	"OC_STACKABLE":                  4210,
	"OC_TRADEABLE":                  4211,
	"OC_UNCERT":                     4212,
	"OC_WEARPOS":                    4213,
	"OC_WEARPOS2":                   4214,
	"OC_WEARPOS3":                   4215,
	"OC_WEIGHT":                     4216,
	"BOTH_DROPSLOT":                 4300,
	"BOTH_MOVEINV":                  4301,
	"INV_ADD":                       4302,
	"INV_ALLSTOCK":                  4303,
	"INV_CHANGESLOT":                4304,
	"INV_CLEAR":                     4305,
	"INV_DEBUGNAME":                 4306,
	"INV_DEL":                       4307,
	"INV_DELSLOT":                   4308,
	"INV_DROPALL":                   4309,
	"INV_DROPITEM_DELAYED":          4310,
	"INV_DROPITEM":                  4311,
	"INV_DROPSLOT":                  4312,
	"INV_FREESPACE":                 4313,
	"INV_GETNUM":                    4314,
	"INV_GETOBJ":                    4315,
	"INV_ITEMSPACE":                 4316,
	"INV_ITEMSPACE2":                4317,
	"INV_MOVEFROMSLOT":              4318,
	"INV_MOVEITEM_CERT":             4319,
	"INV_MOVEITEM_UNCERT":           4320,
	"INV_MOVEITEM":                  4321,
	"INV_MOVETOSLOT":                4322,
	"INV_SETSLOT":                   4323,
	"INV_SIZE":                      4324,
	"INV_STOCKBASE":                 4325,
	"INV_STOPTRANSMIT":              4326,
	"INV_TOTAL":                     4327,
	"INV_TOTALCAT":                  4328,
	"INV_TOTALPARAM_STACK":          4329,
	"INV_TOTALPARAM":                4330,
	"INV_TRANSMIT":                  4331,
	"INVOTHER_TRANSMIT":             4332,
	"ENUM":                          4400,
	"ENUM_GETOUTPUTCOUNT":           4401,
	"APPEND_NUM":                    4500,
	"APPEND":                        4501,
	"APPEND_SIGNNUM":                4502,
	"LOWERCASE":                     4503,
	"TEXT_GENDER":                   4504,
	"TOSTRING":                      4505,
	"COMPARE":                       4506,
	"TEXT_SWITCH":                   4507,
	"APPEND_CHAR":                   4508,
	"STRING_LENGTH":                 4509,
	"SUBSTRING":                     4510,
	"STRING_INDEXOF_CHAR":           4511,
	"STRING_INDEXOF_STRING":         4512,
	"ADD":                           4600,
	"SUB":                           4601,
	"MULTIPLY":                      4602,
	"DIVIDE":                        4603,
	"RANDOM":                        4604,
	"RANDOMINC":                     4605,
	"INTERPOLATE":                   4606,
	"ADDPERCENT":                    4607,
	"SETBIT":                        4608,
	"CLEARBIT":                      4609,
	"TESTBIT":                       4610,
	"MODULO":                        4611,
	"POW":                           4612,
	"INVPOW":                        4613,
	"AND":                           4614,
	"OR":                            4615,
	"MIN":                           4616,
	"MAX":                           4617,
	"SCALE":                         4618,
	"BITCOUNT":                      4619,
	"TOGGLEBIT":                     4620,
	"SETBIT_RANGE":                  4621,
	"CLEARBIT_RANGE":                4622,
	"GETBIT_RANGE":                  4623,
	"SETBIT_RANGE_TOINT":            4624,
	"SIN_DEG":                       4625,
	"COS_DEG":                       4626,
	"ATAN2_DEG":                     4627,
	"ABS":                           4628,
	"STRUCT_PARAM":                  4700,
	"DB_FIND_WITH_COUNT":            7500,
	"DB_FINDNEXT":                   7501,
	"DB_GETFIELD":                   7502,
	"DB_GETFIELDCOUNT":              7503,
	"DB_LISTALL_WITH_COUNT":         7504,
	"DB_GETROWTABLE":                7505,
	"DB_FINDBYINDEX":                7506,
	"DB_FIND_REFINE_WITH_COUNT":     7507,
	"DB_FIND":                       7508,
	"DB_FIND_REFINE":                7509,
	"DB_LISTALL":                    7510,
	"CONSOLE":                       10000,
	"ERROR":                         10001,
	"GETTIMESPENT":                  10002,
	"TIMESPENT":                     10003,
}

// removed274Names were deleted/renamed upstream and must NOT resolve. The
// BAS_* family, HINT_PLAYER, LOWMEMORY and IF_SETRESUMEBUTTONS are the
// 43e02957-era spellings of the renamed ops; SETSKINCOLOUR is the pre-274
// spelling renamed to SETIDKCOLOUR at dee467c8; the rest were deleted
// outright (IF_SETRECOL has been gone since 244).
var removed274Names = []string{
	"IF_SETRECOL",
	"BAS_READYANIM", "BAS_RUNNING", "BAS_TURNONSPOT",
	"BAS_WALK_B", "BAS_WALK_F", "BAS_WALK_L", "BAS_WALK_R",
	"HINT_PLAYER", "LOWMEMORY", "IF_SETRESUMEBUTTONS",
	"NPCCOUNT", "ZONECOUNT", "LOCCOUNT", "OBJCOUNT",
	"BUFFER_FULL", "IF_MULTIZONE", "PLAYER_FINDALLZONE", "PLAYER_FINDNEXT",
	"IF_OPENMAINOVERLAY", "LAST_COORD", "NPC_HUNTNEXT",
	"MAP_PRODUCTION", "MAP_LASTCLOCK", "MAP_LASTWORLD", "MAP_LASTCLIENTIN",
	"MAP_LASTNPC", "MAP_LASTPLAYER", "MAP_LASTLOGOUT", "MAP_LASTLOGIN",
	"MAP_LASTZONE", "MAP_LASTCLIENTOUT", "MAP_LASTCLEANUP",
	"MAP_LASTBANDWIDTHIN", "MAP_LASTBANDWIDTHOUT",
	"SETSKINCOLOUR",
}

func TestScriptOpcodeMap_274Pin(t *testing.T) {
	for name, want := range scriptOpcodeMap274Pin {
		got, ok := ScriptOpcodeMap[name]
		if !ok {
			t.Errorf("ScriptOpcodeMap missing %q", name)
			continue
		}
		if got != want {
			t.Errorf("ScriptOpcodeMap[%q] = %d, want %d", name, got, want)
		}
	}
	if len(ScriptOpcodeMap) != len(scriptOpcodeMap274Pin) {
		t.Errorf("ScriptOpcodeMap has %d entries, 274 pin has %d", len(ScriptOpcodeMap), len(scriptOpcodeMap274Pin))
	}
	for _, name := range removed274Names {
		if _, ok := ScriptOpcodeMap[name]; ok {
			t.Errorf("ScriptOpcodeMap still contains removed name %q", name)
		}
	}
}

func TestOpcodeString_274Pin(t *testing.T) {
	for name, op := range scriptOpcodeMap274Pin {
		if name[len(name)-1] == '*' {
			continue // vararg map keys; String() keeps the enum spelling
		}
		if got := op.String(); got != name {
			t.Errorf("Opcode(%d).String() = %q, want %q", op, got, name)
		}
	}
}
