package script

// ScriptOpcodeMap maps uppercase opcode name → Opcode value. Mirrors TS
// ScriptOpcodeMap (src/engine/script/ScriptOpcode.ts, map section at pin
// 9aadcec4). Consumed by the bytecode compiler's allCommands construction
// in pkg/pack/compiler (NAI-202 runServerCompiler).
//
// 244 changes vs 225: HUNTALL/HUNTNEXT moved to server block (1004–1005);
// SPLIT_*/STRUCT_PARAM moved to server block; new server ops (1030–1034);
// player block renumbered; BAS_* rename family; HINT_PLAYER/LOWMEMORY
// renames; IF_SETRECOL/STAT_TOTAL/MAP_LIVE/PUSH_VARBIT/POP_VARBIT removed;
// new player ops (BUFFER_FULL, IF_MULTIZONE, IF_OPENOVERLAY, etc.);
// NPC block renumbered; inv block renumbered; MAP_LAST* debug ops added.
//
// Naming: TS UPPER_SNAKE_CASE → goscape Op* constant in
// pkg/script/opcode.go. Most names follow mechanical UPPER_SNAKE →
// OpUpperCamel translation; goscape uses all-caps for acronyms (UID, ID)
// so e.g. FINDUID → OpFindUID, GETTIMESPENT → OpGetTimeSpent.
//
// Iteration order: Go map iteration is randomized. TS Map<string,
// number> is insertion-ordered, but runServerCompiler sorts by opcode
// value before iteration (Compiler.ts:111). Iteration order does not
// matter to consumers.
var ScriptOpcodeMap = map[string]Opcode{
	// Core language ops
	"PUSH_CONSTANT_INT":             OpPushConstantInt,
	"PUSH_VARP":                     OpPushVarp,
	"POP_VARP":                      OpPopVarp,
	"PUSH_CONSTANT_STRING":          OpPushConstantString,
	"PUSH_VARN":                     OpPushVarn,
	"POP_VARN":                      OpPopVarn,
	"BRANCH":                        OpBranch,
	"BRANCH_NOT":                    OpBranchNot,
	"BRANCH_EQUALS":                 OpBranchEquals,
	"BRANCH_LESS_THAN":              OpBranchLessThan,
	"BRANCH_GREATER_THAN":           OpBranchGreaterThan,
	"PUSH_VARS":                     OpPushVars,
	"POP_VARS":                      OpPopVars,
	"RETURN":                        OpReturn,
	"GOSUB":                         OpGosub,
	"JUMP":                          OpJump,
	"SWITCH":                        OpSwitch,
	"BRANCH_LESS_THAN_OR_EQUALS":    OpBranchLessThanOrEquals,
	"BRANCH_GREATER_THAN_OR_EQUALS": OpBranchGreaterThanOrEquals,
	"PUSH_INT_LOCAL":                OpPushIntLocal,
	"POP_INT_LOCAL":                 OpPopIntLocal,
	"PUSH_STRING_LOCAL":             OpPushStringLocal,
	"POP_STRING_LOCAL":              OpPopStringLocal,
	"JOIN_STRING":                   OpJoinString,
	"POP_INT_DISCARD":               OpPopIntDiscard,
	"POP_STRING_DISCARD":            OpPopStringDiscard,
	"GOSUB_WITH_PARAMS":             OpGosubWithParams,
	"JUMP_WITH_PARAMS":              OpJumpWithParams,
	"DEFINE_ARRAY":                  OpDefineArray,
	"PUSH_ARRAY_INT":                OpPushArrayInt,
	"POP_ARRAY_INT":                 OpPopArrayInt,

	// Server ops (1000–1034)
	"COORDX":           OpCoordX,
	"COORDY":           OpCoordY,
	"COORDZ":           OpCoordZ,
	"DISTANCE":         OpDistance,
	"HUNTALL":          OpHuntAll,
	"HUNTNEXT":         OpHuntNext,
	"INZONE":           OpInZone,
	"LINEOFSIGHT":      OpLineOfSight,
	"LINEOFWALK":       OpLineOfWalk,
	"MAP_BLOCKED":      OpMapBlocked,
	"MAP_INDOORS":      OpMapIndoors,
	"MAP_CLOCK":        OpMapClock,
	"MAP_LOCADDUNSAFE": OpMapLocAddUnsafe,
	"MAP_MEMBERS":      OpMapMembers,
	"MAP_PLAYERCOUNT":  OpMapPlayerCount,
	"MAP_FINDSQUARE":   OpMapFindSquare,
	"MOVECOORD":        OpMoveCoord,
	"PLAYERCOUNT":      OpPlayerCount,
	"PROJANIM_MAP":     OpProjAnimMap,
	"PROJANIM_NPC":     OpProjAnimNpc,
	"PROJANIM_PL":      OpProjAnimPl,
	"SEQLENGTH":        OpSeqLength,
	"SPLIT_GET":        OpSplitGet,
	"SPLIT_GETANIM":    OpSplitGetAnim,
	"SPLIT_INIT":       OpSplitInit,
	"SPLIT_LINECOUNT":  OpSplitLineCount,
	"SPLIT_PAGECOUNT":  OpSplitPageCount,
	"SPOTANIM_MAP":     OpSpotAnimMap,
	"STRUCT_PARAM":     OpStructParam,
	"WORLD_DELAY":      OpWorldDelay,
	"NPCCOUNT":         OpNpcCount,
	"ZONECOUNT":        OpZoneCount,
	"LOCCOUNT":         OpLocCount,
	"OBJCOUNT":         OpZoneObjCount,
	"MAP_MULTIWAY":     OpMapMultiway,

	// Player ops (2000–2135)
	"ALLOWDESIGN":          OpAllowDesign,
	"ANIM":                 OpAnim,
	"BAS_READYANIM":        OpBasReadyAnim,
	"BAS_RUNNING":          OpBasRunning,
	"BAS_TURNONSPOT":       OpBasTurnOnSpot,
	"BAS_WALK_B":           OpBasWalkB,
	"BAS_WALK_F":           OpBasWalkF,
	"BAS_WALK_L":           OpBasWalkL,
	"BAS_WALK_R":           OpBasWalkR,
	"BUFFER_FULL":          OpBufferFull,
	"BUILDAPPEARANCE":      OpBuildAppearance,
	"BUSY":                 OpBusy,
	"CAM_LOOKAT":           OpCamLookAt,
	"CAM_MOVETO":           OpCamMoveTo,
	"CAM_RESET":            OpCamReset,
	"CAM_SHAKE":            OpCamShake,
	"CLEARQUEUE":           OpClearQueue,
	"CLEARSOFTTIMER":       OpClearSoftTimer,
	"CLEARTIMER":           OpClearTimer,
	"GETTIMER":             OpGetTimer,
	"COORD":                OpCoord,
	"DAMAGE":               OpDamage,
	"DISPLAYNAME":          OpDisplayName,
	"FACESQUARE":           OpFaceSquare,
	"FINDUID":              OpFindUID,
	"GENDER":               OpGender,
	"GETQUEUE":             OpGetQueue,
	"STAT_ADVANCE":         OpStatAdvance,
	"HEADICONS_GET":        OpHeadIconsGet,
	"HEADICONS_SET":        OpHeadIconsSet,
	"HEALENERGY":           OpHealEnergy,
	"HINT_COORD":           OpHintCoord,
	"HINT_NPC":             OpHintNpc,
	"HINT_PLAYER":          OpHintPlayer,
	"HINT_STOP":            OpHintStop,
	"IF_CLOSE":             OpIfClose,
	"TUT_CLOSE":            OpTutClose,
	"IF_MULTIZONE":         OpIfMultizone,
	"IF_OPENCHAT":          OpIfOpenChat,
	"TUT_OPEN":             OpTutOpen,
	"IF_OPENMAIN":          OpIfOpenMain,
	"IF_OPENOVERLAY":       OpIfOpenOverlay,
	"IF_OPENMAIN_SIDE":     OpIfOpenMainSide,
	"IF_OPENSIDE":          OpIfOpenSide,
	"IF_SETANIM":           OpIfSetAnim,
	"IF_SETCOLOUR":         OpIfSetColour,
	"IF_SETHIDE":           OpIfSetHide,
	"IF_SETMODEL":          OpIfSetModel,
	"IF_SETNPCHEAD":        OpIfSetNpcHead,
	"IF_SETOBJECT":         OpIfSetObject,
	"IF_SETPLAYERHEAD":     OpIfSetPlayerHead,
	"IF_SETPOSITION":       OpIfSetPosition,
	"IF_SETSCROLLPOS":      OpIfSetScrollPos,
	"IF_SETRESUMEBUTTONS":  OpIfSetResumeButtons,
	"IF_SETTAB":            OpIfSetTab,
	"IF_SETTABACTIVE":      OpIfSetTabActive,
	"TUT_FLASH":            OpTutFlash,
	"IF_SETTEXT":           OpIfSetText,
	"LAST_LOGIN_INFO":      OpLastLoginInfo,
	"LAST_COM":             OpLastCom,
	"LAST_INT":             OpLastInt,
	"LAST_ITEM":            OpLastItem,
	"LAST_SLOT":            OpLastSlot,
	"LAST_TARGETSLOT":      OpLastTargetSlot,
	"LAST_USEITEM":         OpLastUseItem,
	"LAST_USESLOT":         OpLastUseSlot,
	"LONGQUEUE":            OpLongQueue,
	"LONGQUEUE*":           OpLongQueueVarArg,
	"MES":                  OpMes,
	"MIDI_JINGLE":          OpMidiJingle,
	"MIDI_SONG":            OpMidiSong,
	"NAME":                 OpName,
	"P_APRANGE":            OpPApRange,
	"P_ARRIVEDELAY":        OpPArriveDelay,
	"P_COUNTDIALOG":        OpPCountDialog,
	"P_DELAY":              OpPDelay,
	"P_EXACTMOVE":          OpPExactMove,
	"P_FINDUID":            OpPFindUID,
	"P_LOCMERGE":           OpPLocMerge,
	"P_LOGOUT":             OpPLogout,
	"P_PREVENTLOGOUT":      OpPPreventLogout,
	"P_OPHELD":             OpPOpHeld,
	"P_OPLOC":              OpPOpLoc,
	"P_OPNPC":              OpPOpNpc,
	"P_OPNPCT":             OpPOpNpcT,
	"P_OPOBJ":              OpPOpObj,
	"P_OPPLAYER":           OpPOpPlayer,
	"P_OPPLAYERT":          OpPOpPlayerT,
	"P_PAUSEBUTTON":        OpPPauseButton,
	"P_STOPACTION":         OpPStopAction,
	"P_TELEJUMP":           OpPTeleJump,
	"P_TELEPORT":           OpPTeleport,
	"P_WALK":               OpPWalk,
	"PLAYER_FINDALLZONE":   OpPlayerFindAllZone,
	"PLAYER_FINDNEXT":      OpPlayerFindNext,
	"QUEUE":                OpQueue,
	"QUEUE*":               OpQueueVarArg,
	"SAY":                  OpSay,
	"WALKTRIGGER":          OpWalkTrigger,
	"SETTIMER":             OpSetTimer,
	"SOFTTIMER":            OpSoftTimer,
	"SOUND_SYNTH":          OpSoundSynth,
	"SPOTANIM_PL":          OpSpotAnimPl,
	"STAFFMODLEVEL":        OpStaffModLevel,
	"STAT":                 OpStat,
	"STAT_ADD":             OpStatAdd,
	"STAT_BASE":            OpStatBase,
	"STAT_HEAL":            OpStatHeal,
	"STAT_SUB":             OpStatSub,
	"STAT_BOOST":           OpStatBoost,
	"STAT_DRAIN":           OpStatDrain,
	"STAT_RANDOM":          OpStatRandom,
	"STRONGQUEUE":          OpStrongQueue,
	"STRONGQUEUE*":         OpStrongQueueVarArg,
	"UID":                  OpUID,
	"WEAKQUEUE":            OpWeakQueue,
	"WEAKQUEUE*":           OpWeakQueueVarArg,
	"IF_OPENMAINOVERLAY":   OpIfOpenMainOverlay,
	"AFK_EVENT":            OpAfkEvent,
	"LOWMEMORY":            OpLowMemory,
	"SETIDKIT":             OpSetIdKit,
	"P_CLEARPENDINGACTION": OpPClearPendingAction,
	"GETWALKTRIGGER":       OpGetWalkTrigger,
	"BUSY2":                OpBusy2,
	"FINDHERO":             OpFindHero,
	"BOTH_HEROPOINTS":      OpBothHeroPoints,
	"SETGENDER":            OpSetGender,
	"SETSKINCOLOUR":        OpSetSkinColour,
	"P_ANIMPROTECT":        OpPAnimProtect,
	"RUNENERGY":            OpRunEnergy,
	"WEIGHT":               OpWeight,
	"LAST_COORD":           OpLastCoord,
	"SESSION_LOG":          OpSessionLog,
	"WEALTH_EVENT":         OpWealthEvent,
	"P_RUN":                OpPRun,
	"PLAYERMEMBER":         OpPlayerMember,

	// NPC ops (2500–2547)
	"NPC_ADD":                OpNpcAdd,
	"NPC_ANIM":               OpNpcAnim,
	"NPC_BASESTAT":           OpNpcBaseStat,
	"NPC_CATEGORY":           OpNpcCategory,
	"NPC_CHANGETYPE":         OpNpcChangeType,
	"NPC_CHANGETYPE_KEEPALL": OpNpcChangeTypeKeepAll,
	"NPC_COORD":              OpNpcCoord,
	"NPC_DAMAGE":             OpNpcDamage,
	"NPC_DEL":                OpNpcDel,
	"NPC_DELAY":              OpNpcDelay,
	"NPC_FACESQUARE":         OpNpcFaceSquare,
	"NPC_FIND":               OpNpcFind,
	"NPC_FINDCAT":            OpNpcFindCat,
	"NPC_FINDALLANY":         OpNpcFindAllAny,
	"NPC_FINDALL":            OpNpcFindAll,
	"NPC_FINDEXACT":          OpNpcFindExact,
	"NPC_FINDHERO":           OpNpcFindHero,
	"NPC_FINDALLZONE":        OpNpcFindAllZone,
	"NPC_FINDNEXT":           OpNpcFindNext,
	"NPC_FINDUID":            OpNpcFindUID,
	"NPC_GETMODE":            OpNpcGetMode,
	"NPC_HEROPOINTS":         OpNpcHeroPoints,
	"NPC_NAME":               OpNpcName,
	"NPC_PARAM":              OpNpcParam,
	"NPC_QUEUE":              OpNpcQueue,
	"NPC_RANGE":              OpNpcRange,
	"NPC_SAY":                OpNpcSay,
	"NPC_HUNT":               OpNpcHunt,
	"NPC_HUNTALL":            OpNpcHuntAll,
	"NPC_HUNTNEXT":           OpNpcHuntNext,
	"NPC_SETHUNT":            OpNpcSetHunt,
	"NPC_SETHUNTMODE":        OpNpcSetHuntMode,
	"NPC_SETMODE":            OpNpcSetMode,
	"NPC_WALKTRIGGER":        OpNpcWalkTrigger,
	"NPC_SETTIMER":           OpNpcSetTimer,
	"NPC_STAT":               OpNpcStat,
	"NPC_STATADD":            OpNpcStatAdd,
	"NPC_STATHEAL":           OpNpcStatHeal,
	"NPC_STATSUB":            OpNpcStatSub,
	"NPC_TELE":               OpNpcTele,
	"NPC_TYPE":               OpNpcType,
	"NPC_UID":                OpNpcUID,
	"SPOTANIM_NPC":           OpSpotAnimNpc,
	"NPC_WALK":               OpNpcWalk,
	"NPC_ATTACKRANGE":        OpNpcAttackRange,
	"NPC_HASOP":              OpNpcHasOp,
	"NPC_ARRIVEDELAY":        OpNpcArriveDelay,
	"NPC_INRANGE":            OpNpcInRange,

	// Loc ops (3000–3013)
	"LOC_ADD":         OpLocAdd,
	"LOC_ANGLE":       OpLocAngle,
	"LOC_ANIM":        OpLocAnim,
	"LOC_CATEGORY":    OpLocCategory,
	"LOC_CHANGE":      OpLocChange,
	"LOC_COORD":       OpLocCoord,
	"LOC_DEL":         OpLocDel,
	"LOC_FIND":        OpLocFind,
	"LOC_FINDALLZONE": OpLocFindAllZone,
	"LOC_FINDNEXT":    OpLocFindNext,
	"LOC_NAME":        OpLocName,
	"LOC_PARAM":       OpLocParam,
	"LOC_SHAPE":       OpLocShape,
	"LOC_TYPE":        OpLocType,

	// Obj ops (3500–3511)
	"OBJ_ADD":         OpObjAdd,
	"OBJ_ADDALL":      OpObjAddAll,
	"OBJ_FIND":        OpObjFind,
	"OBJ_FINDALLZONE": OpObjFindAllZone,
	"OBJ_FINDNEXT":    OpObjFindNext,
	"OBJ_COORD":       OpObjCoord,
	"OBJ_COUNT":       OpObjCount,
	"OBJ_DEL":         OpObjDel,
	"OBJ_NAME":        OpObjName,
	"OBJ_PARAM":       OpObjParam,
	"OBJ_TAKEITEM":    OpObjTakeItem,
	"OBJ_TYPE":        OpObjType,

	// NPC config ops (4000–4007)
	"NC_CATEGORY":  OpNcCategory,
	"NC_DEBUGNAME": OpNcDebugName,
	"NC_DESC":      OpNcDesc,
	"NC_NAME":      OpNcName,
	"NC_OP":        OpNcOp,
	"NC_PARAM":     OpNcParam,
	"NC_SIZE":      OpNcSize,
	"NC_VISLEVEL":  OpNcVisLevel,

	// Loc config ops (4100–4107)
	"LC_CATEGORY":  OpLcCategory,
	"LC_DEBUGNAME": OpLcDebugName,
	"LC_DESC":      OpLcDesc,
	"LC_NAME":      OpLcName,
	"LC_OP":        OpLcOp,
	"LC_PARAM":     OpLcParam,
	"LC_WIDTH":     OpLcWidth,
	"LC_LENGTH":    OpLcLength,

	// Obj config ops (4200–4216)
	"OC_CATEGORY":  OpOcCategory,
	"OC_CERT":      OpOcCert,
	"OC_COST":      OpOcCost,
	"OC_DEBUGNAME": OpOcDebugName,
	"OC_DESC":      OpOcDesc,
	"OC_IOP":       OpOcIop,
	"OC_MEMBERS":   OpOcMembers,
	"OC_NAME":      OpOcName,
	"OC_OP":        OpOcOp,
	"OC_PARAM":     OpOcParam,
	"OC_STACKABLE": OpOcStackable,
	"OC_TRADEABLE": OpOcTradeable,
	"OC_UNCERT":    OpOcUncert,
	"OC_WEARPOS2":  OpOcWearPos2,
	"OC_WEARPOS3":  OpOcWearPos3,
	"OC_WEARPOS":   OpOcWearPos,
	"OC_WEIGHT":    OpOcWeight,

	// Inventory ops (4300–4332)
	"INV_ALLSTOCK":         OpInvAllStock,
	"INV_SIZE":             OpInvSize,
	"INV_STOCKBASE":        OpInvStockBase,
	"INV_ADD":              OpInvAdd,
	"INV_CHANGESLOT":       OpInvChangeSlot,
	"INV_CLEAR":            OpInvClear,
	"INV_DEL":              OpInvDel,
	"INV_DELSLOT":          OpInvDelSlot,
	"INV_DROPITEM":         OpInvDropItem,
	"INV_DROPITEM_DELAYED": OpInvDropItemDelayed,
	"INV_DROPSLOT":         OpInvDropSlot,
	"INV_FREESPACE":        OpInvFreeSpace,
	"INV_GETNUM":           OpInvGetNum,
	"INV_GETOBJ":           OpInvGetObj,
	"INV_ITEMSPACE":        OpInvItemSpace,
	"INV_ITEMSPACE2":       OpInvItemSpace2,
	"INV_MOVEFROMSLOT":     OpInvMoveFromSlot,
	"INV_MOVETOSLOT":       OpInvMoveToSlot,
	"BOTH_MOVEINV":         OpBothMoveInv,
	"INV_MOVEITEM":         OpInvMoveItem,
	"INV_MOVEITEM_CERT":    OpInvMoveItemCert,
	"INV_MOVEITEM_UNCERT":  OpInvMoveItemUncert,
	"INV_SETSLOT":          OpInvSetSlot,
	"INV_TOTAL":            OpInvTotal,
	"INV_TOTALCAT":         OpInvTotalCat,
	"INV_TRANSMIT":         OpInvTransmit,
	"INVOTHER_TRANSMIT":    OpInvOtherTransmit,
	"INV_STOPTRANSMIT":     OpInvStopTransmit,
	"BOTH_DROPSLOT":        OpBothDropSlot,
	"INV_DROPALL":          OpInvDropAll,
	"INV_TOTALPARAM":       OpInvTotalParam,
	"INV_TOTALPARAM_STACK": OpInvTotalParamStack,
	"INV_DEBUGNAME":        OpInvDebugName,

	// Enum ops (4400–4401)
	"ENUM":                OpEnum,
	"ENUM_GETOUTPUTCOUNT": OpEnumGetOutputCount,

	// String ops (4500–4512)
	"APPEND_NUM":            OpAppendNum,
	"APPEND":                OpAppend,
	"APPEND_SIGNNUM":        OpAppendSignNum,
	"LOWERCASE":             OpLowercase,
	"TEXT_GENDER":           OpTextGender,
	"TOSTRING":              OpToString,
	"COMPARE":               OpCompare,
	"TEXT_SWITCH":           OpTextSwitch,
	"APPEND_CHAR":           OpAppendChar,
	"STRING_LENGTH":         OpStringLength,
	"SUBSTRING":             OpSubstring,
	"STRING_INDEXOF_CHAR":   OpStringIndexOfChar,
	"STRING_INDEXOF_STRING": OpStringIndexOfString,

	// Number ops (4600–4628)
	"ADD":                OpAdd,
	"SUB":                OpSub,
	"MULTIPLY":           OpMultiply,
	"DIVIDE":             OpDivide,
	"RANDOM":             OpRandom,
	"RANDOMINC":          OpRandomInc,
	"INTERPOLATE":        OpInterpolate,
	"ADDPERCENT":         OpAddPercent,
	"SETBIT":             OpSetBit,
	"CLEARBIT":           OpClearBit,
	"TESTBIT":            OpTestBit,
	"MODULO":             OpModulo,
	"POW":                OpPow,
	"INVPOW":             OpInvPow,
	"AND":                OpAnd,
	"OR":                 OpOr,
	"MIN":                OpMin,
	"MAX":                OpMax,
	"SCALE":              OpScale,
	"BITCOUNT":           OpBitCount,
	"TOGGLEBIT":          OpToggleBit,
	"SETBIT_RANGE":       OpSetBitRange,
	"CLEARBIT_RANGE":     OpClearBitRange,
	"GETBIT_RANGE":       OpGetBitRange,
	"SETBIT_RANGE_TOINT": OpSetBitRangeToInt,
	"SIN_DEG":            OpSinDeg,
	"COS_DEG":            OpCosDeg,
	"ATAN2_DEG":          OpAtan2Deg,
	"ABS":                OpAbs,

	// DB ops (7500–7510)
	"DB_FIND_WITH_COUNT":        OpDbFindWithCount,
	"DB_FINDNEXT":               OpDbFindNext,
	"DB_GETFIELD":               OpDbGetField,
	"DB_GETFIELDCOUNT":          OpDbGetFieldCount,
	"DB_LISTALL_WITH_COUNT":     OpDbListAllWithCount,
	"DB_GETROWTABLE":            OpDbGetRowTable,
	"DB_FINDBYINDEX":            OpDbFindByIndex,
	"DB_FIND_REFINE_WITH_COUNT": OpDbFindRefineWithCount,
	"DB_FIND":                   OpDbFind,
	"DB_FIND_REFINE":            OpDbFindRefine,
	"DB_LISTALL":                OpDbListAll,

	// Debug ops (10000–10016)
	"ERROR":                OpError,
	"MAP_PRODUCTION":       OpMapProduction,
	"MAP_LASTCLOCK":        OpMapLastClock,
	"MAP_LASTWORLD":        OpMapLastWorld,
	"MAP_LASTCLIENTIN":     OpMapLastClientIn,
	"MAP_LASTNPC":          OpMapLastNpc,
	"MAP_LASTPLAYER":       OpMapLastPlayer,
	"MAP_LASTLOGOUT":       OpMapLastLogout,
	"MAP_LASTLOGIN":        OpMapLastLogin,
	"MAP_LASTZONE":         OpMapLastZone,
	"MAP_LASTCLIENTOUT":    OpMapLastClientOut,
	"MAP_LASTCLEANUP":      OpMapLastCleanup,
	"MAP_LASTBANDWIDTHIN":  OpMapLastBandwidthIn,
	"MAP_LASTBANDWIDTHOUT": OpMapLastBandwidthOut,
	"TIMESPENT":            OpTimeSpent,
	"GETTIMESPENT":         OpGetTimeSpent,
	"CONSOLE":              OpConsole,
}
