-- Unified central-database schema (fresh lineage; clean break from the
-- retired modules/login/migrations + modules/friends/migrations chains).
-- Spec: docs/superpowers/specs/2026-07-05-central-db-consolidation-postgres-design.md
--
-- Postgres translation of migrations/sqlite/000001_init.up.sql: table
-- names, column names, constraints, indexes, and FK clauses are
-- identical; only column types change (INTEGER PRIMARY KEY AUTOINCREMENT
-- -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account
-- id-holding columns -> BIGINT, timestamp-bearing columns -> timestamptz,
-- the session_uuid CHECK's GLOB -> POSIX regex).
--
-- rev-225 login surface is PRE-B5 (login-server-7 not yet closed on this
-- branch): logout_time still lives on `account` itself, and
-- `account_login` has no logged_out/logout_time columns at all — see the
-- account/account_login definitions below. This mirrors this branch's
-- own modules/login/migrations/000001-000004 lineage (account.logout_time,
-- account_login sans logged_out/logout_time), not rev-254/274's post-B5
-- shape.
--
-- FK posture: account-referencing columns that goscape itself
-- reads/writes carry REFERENCES account(id) ON DELETE CASCADE — a
-- goscape extension over TS (the prisma schemas @e1dea19f declare zero
-- @relation fields). Deliberate exceptions:
--   * ignorelist.value — raw username string, NO FK: TS addIgnore
--     (FriendServerRepository.ts:249-294) never checks the target, so
--     you can ignore usernames that don't exist.
--   * public_chat.session_uuid — NO FK: headless players emit uuids
--     with no session row (world sends p.sessionOrHeadless()).

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    registration_ip TEXT NOT NULL DEFAULT '',
    staff_mod_level INTEGER NOT NULL DEFAULT 0,
    members INTEGER NOT NULL DEFAULT 0,
    banned_until timestamptz,
    muted_until timestamptz,
    logout_time timestamptz
);

CREATE TABLE account_login (
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile    TEXT    NOT NULL,
    node_id    INTEGER NOT NULL DEFAULT 0,
    logged_in  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (account_id, profile)
);

CREATE TABLE session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid TEXT NOT NULL CHECK (
        session_uuid ~ '^.{8}-.{4}-.{4}-.{4}-.{12}$'
    ),
    account_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile TEXT NOT NULL,
    world INTEGER NOT NULL DEFAULT 0,
    uid INTEGER NOT NULL DEFAULT 0,
    login_time timestamptz NOT NULL,
    remote_address TEXT NOT NULL DEFAULT ''
);

CREATE INDEX idx_session_account_profile ON session (account_id, profile);

CREATE TABLE ipban (
    ip TEXT NOT NULL PRIMARY KEY,
    added_by TEXT NOT NULL DEFAULT '',
    added_on TEXT NOT NULL DEFAULT ''
);

CREATE TABLE hiscore (
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile    TEXT    NOT NULL DEFAULT 'main',
    type       INTEGER NOT NULL,
    level      INTEGER NOT NULL,
    value      BIGINT  NOT NULL,
    date       timestamptz NOT NULL,
    PRIMARY KEY (profile, type, account_id)
);

CREATE TABLE hiscore_large (
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile    TEXT    NOT NULL DEFAULT 'main',
    type       INTEGER NOT NULL,
    level      INTEGER NOT NULL,
    value      BIGINT  NOT NULL,
    date       timestamptz NOT NULL,
    PRIMARY KEY (profile, type, account_id)
);

-- ==== friends tables: TS shape @e1dea19f + goscape FK extensions ====
-- addFriend's cap (FriendServerRepository.ts:222-233 @e1dea19f) is a flat
-- `const limit = 100` (:231) applied identically to friends and ignores —
-- NOT the members-aware `account.members ? 200 : 100` split rev-254/274's
-- own TS pins have. The owner-resolution select at :222 does fetch
-- `account.members` alongside `id`, but the function never reads it back
-- (dead code at this pin) — no members-aware behavior to port here.

CREATE TABLE friendlist (
    profile           TEXT    NOT NULL,
    account_id        BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    friend_account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    created           timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile, account_id, friend_account_id)
);

-- Backs GetFollowers / IsVisibleTo reverse lookups (friend-side scan).
CREATE INDEX idx_friendlist_friend ON friendlist (profile, friend_account_id);

CREATE TABLE ignorelist (
    profile    TEXT    NOT NULL,
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    value      TEXT    NOT NULL,
    created    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile, account_id, value)
);

CREATE TABLE private_chat (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile       TEXT    NOT NULL,
    timestamp     timestamptz NOT NULL DEFAULT now(),
    coord         INTEGER NOT NULL,
    to_account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    message       TEXT    NOT NULL
);

CREATE INDEX idx_private_chat_to   ON private_chat (profile, to_account_id, timestamp);
CREATE INDEX idx_private_chat_from ON private_chat (profile, account_id, timestamp);

CREATE TABLE public_chat (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid TEXT    NOT NULL,
    timestamp    timestamptz NOT NULL DEFAULT now(),
    coord        INTEGER NOT NULL,
    message      TEXT    NOT NULL
);

CREATE INDEX idx_public_chat_session ON public_chat (session_uuid, timestamp);
