-- Unified central-database schema (fresh lineage; clean break from the
-- retired modules/login/migrations + modules/friends/migrations chains).
-- Spec: docs/superpowers/specs/2026-07-05-central-db-consolidation-postgres-design.md
--
-- Postgres translation of migrations/sqlite/000001_init.up.sql: table
-- names, column names, constraints, indexes, and FK clauses are
-- identical; only column types change (INTEGER PRIMARY KEY AUTOINCREMENT
-- -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account/thread
-- id-holding columns -> BIGINT, timestamp-bearing columns -> timestamptz,
-- the session_uuid CHECK's GLOB -> POSIX regex).
--
-- FK posture: account-referencing columns that goscape itself
-- reads/writes carry REFERENCES account(id) ON DELETE CASCADE — a
-- goscape extension over TS (the prisma schemas @2e3bcf43 declare zero
-- @relation fields). Deliberate exceptions:
--   * ignorelist.value — raw username string, NO FK: TS addIgnore
--     (FriendServerRepository.ts:249-294) never checks the target, so
--     you can ignore usernames that don't exist.
--   * public_chat.session_uuid — NO FK: headless players emit uuids
--     with no session row (world sends p.sessionOrHeadless()).
--   * message_* / account_session / wealth_event — dormant landing
--     tables, NO FKs, mirroring their prisma-generated DDL.

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    registration_ip TEXT NOT NULL DEFAULT '',
    staff_mod_level INTEGER NOT NULL DEFAULT 0,
    members INTEGER NOT NULL DEFAULT 0,
    banned_until timestamptz,
    muted_until timestamptz
);

CREATE TABLE account_login (
    account_id  BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile     TEXT    NOT NULL,
    node_id     INTEGER NOT NULL DEFAULT 0,
    logged_in   INTEGER NOT NULL DEFAULT 0,
    logged_out  INTEGER NOT NULL DEFAULT 0,
    logout_time timestamptz,
    PRIMARY KEY (account_id, profile)
);

CREATE TABLE session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid TEXT NOT NULL CHECK (
        session_uuid ~ '^.{8}-.{4}-.{4}-.{4}-.{12}$'
    ),
    account_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile TEXT NOT NULL,
    world INTEGER NOT NULL DEFAULT 0,
    uid INTEGER NOT NULL DEFAULT 0,
    login_time timestamptz NOT NULL,
    remote_address TEXT NOT NULL DEFAULT ''
);

CREATE INDEX idx_session_account_profile ON session (account_id, profile);

CREATE TABLE ipban (
    ip TEXT NOT NULL PRIMARY KEY,
    added_by TEXT NOT NULL DEFAULT '',
    added_on TEXT NOT NULL DEFAULT ''
);

CREATE TABLE hiscore (
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile    TEXT    NOT NULL DEFAULT 'main',
    type       INTEGER NOT NULL,
    level      INTEGER NOT NULL,
    value      BIGINT  NOT NULL,
    date       timestamptz NOT NULL,
    PRIMARY KEY (profile, type, account_id)
);

CREATE TABLE hiscore_large (
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile    TEXT    NOT NULL DEFAULT 'main',
    type       INTEGER NOT NULL,
    level      INTEGER NOT NULL,
    value      BIGINT  NOT NULL,
    date       timestamptz NOT NULL,
    PRIMARY KEY (profile, type, account_id)
);

CREATE TABLE login (
    uuid       TEXT    NOT NULL PRIMARY KEY,
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    world      INTEGER NOT NULL,
    timestamp  timestamptz NOT NULL,
    uid        INTEGER NOT NULL DEFAULT 0,
    ip         TEXT
);

CREATE INDEX idx_login_account_ip_time ON login (account_id, ip, timestamp);

CREATE TABLE message_thread (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_account_id     BIGINT,
    from_account_id   BIGINT  NOT NULL,
    last_message_from BIGINT  NOT NULL,
    subject           TEXT    NOT NULL,
    created           timestamptz NOT NULL DEFAULT now(),
    updated           timestamptz NOT NULL DEFAULT now(),
    messages          INTEGER NOT NULL DEFAULT 1,
    closed            timestamptz,
    closed_by         BIGINT,
    marked_spam       timestamptz,
    marked_spam_by    BIGINT
);

CREATE TABLE message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id  BIGINT  NOT NULL,
    sender_id  BIGINT  NOT NULL,
    sender_ip  TEXT    NOT NULL,
    content    TEXT    NOT NULL,
    created    timestamptz NOT NULL DEFAULT now(),
    edited     timestamptz,
    edited_by  BIGINT,
    deleted    timestamptz,
    deleted_by BIGINT
);

CREATE TABLE message_status (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id  BIGINT  NOT NULL,
    account_id BIGINT  NOT NULL,
    "read"     timestamptz,
    deleted    timestamptz
);

CREATE TABLE account_session (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT  NOT NULL,
    world        INTEGER NOT NULL DEFAULT 0,
    profile      TEXT    NOT NULL DEFAULT 'main',
    session_uuid TEXT    NOT NULL,
    timestamp    timestamptz NOT NULL,
    coord        INTEGER NOT NULL,
    event        TEXT    NOT NULL,
    event_type   INTEGER NOT NULL DEFAULT -1
);

CREATE TABLE wealth_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp         timestamptz NOT NULL,
    coord             INTEGER NOT NULL,
    world             INTEGER NOT NULL DEFAULT 0,
    profile           TEXT    NOT NULL DEFAULT 'main',
    event_type        INTEGER NOT NULL DEFAULT -1,
    account_id        BIGINT  NOT NULL,
    account_session   TEXT    NOT NULL,
    account_items     TEXT    NOT NULL,
    account_value     BIGINT  NOT NULL,
    recipient_id      BIGINT,
    recipient_session TEXT,
    recipient_items   TEXT,
    recipient_value   BIGINT
);

CREATE INDEX idx_wealth_event_recipient ON wealth_event (recipient_id);

-- ==== friends tables: TS shape @2e3bcf43 + goscape FK extensions ====

CREATE TABLE friendlist (
    profile           TEXT    NOT NULL,
    account_id        BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    friend_account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    created           timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile, account_id, friend_account_id)
);

-- Backs GetFollowers / IsVisibleTo reverse lookups (friend-side scan).
CREATE INDEX idx_friendlist_friend ON friendlist (profile, friend_account_id);

CREATE TABLE ignorelist (
    profile    TEXT    NOT NULL,
    account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    value      TEXT    NOT NULL,
    created    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile, account_id, value)
);

CREATE TABLE private_chat (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    profile       TEXT    NOT NULL,
    timestamp     timestamptz NOT NULL DEFAULT now(),
    coord         INTEGER NOT NULL,
    to_account_id BIGINT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    message       TEXT    NOT NULL
);

CREATE INDEX idx_private_chat_to   ON private_chat (profile, to_account_id, timestamp);
CREATE INDEX idx_private_chat_from ON private_chat (profile, account_id, timestamp);

CREATE TABLE public_chat (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid TEXT    NOT NULL,
    timestamp    timestamptz NOT NULL DEFAULT now(),
    coord        INTEGER NOT NULL,
    message      TEXT    NOT NULL
);

CREATE INDEX idx_public_chat_session ON public_chat (session_uuid, timestamp);
