// Package compiler ports the symbol-table data type that the bytecode
// compiler consumes. TS source: tools/pack/Compiler.ts:21-107
// (CompilerTypeInfo class). The runServerCompiler driver assembles a
// TypeInfo per source kind and hands the result to CompileServerScript.
package compiler

import (
	"errors"
	"os"
	"strconv"
	"strings"
)

// TypeInfo holds the name/id/type-info maps for ONE symbol category
// (commands, varp, obj, …) consumed by the bytecode compiler.
//
// Per TS Compiler.ts:21-36 (class CompilerTypeInfo):
//
//	max: number = -1;
//	map: Record<string, string> = {};
//	vartype: Record<string, string> = {};
//	protect: Record<string, boolean> = {};
//	require, require2, set, set2, corrupt, corrupt2: Record<string, string>;
//	conditional: Record<string, boolean>;
//
// NAI-200-D-DUAL-MAP: TS `map: Record<string, string>` accepts BOTH
// numeric-IDs-coerced-to-strings (from add(id, name)) AND genuine
// string keys (from loadRecords/loadMap). Go cannot mix int and string
// keys in one map. The single TS field is split here into:
//
//   - Map     map[int]string    — int-keyed; Load + LoadArray write.
//   - NameMap map[string]string — string-keyed; LoadRecords + LoadMap write.
//
// Auxiliary maps (VarType, Protect, Require, …) are all map[int]<T>
// because every TS write to them uses a numeric ID — falls out of the
// dual-map split.
//
// NAI-200 ships zero writers for the auxiliary maps. The runServerCompiler
// driver is the first caller that populates them (see spec §9 R2).
type TypeInfo struct {
	Max int // = lastId + 1 (TS-faithful); -1 = empty. See Add doc.

	Map     map[int]string
	NameMap map[string]string

	VarType     map[int]string
	Protect     map[int]bool
	Require     map[int]string
	Require2    map[int]string
	Conditional map[int]bool
	Set         map[int]string
	Set2        map[int]string
	Corrupt     map[int]string
	Corrupt2    map[int]string
}

// newTypeInfo returns a zero-valued *TypeInfo with all maps initialized
// and Max=-1. All five public constructors call this so callers may
// invoke Add immediately without nil-map panic. Mirrors TS class field
// defaults at Compiler.ts:22-36.
func newTypeInfo() *TypeInfo {
	return &TypeInfo{
		Max:         -1,
		Map:         map[int]string{},
		NameMap:     map[string]string{},
		VarType:     map[int]string{},
		Protect:     map[int]bool{},
		Require:     map[int]string{},
		Require2:    map[int]string{},
		Conditional: map[int]bool{},
		Set:         map[int]string{},
		Set2:        map[int]string{},
		Corrupt:     map[int]string{},
		Corrupt2:    map[int]string{},
	}
}

// Add records id→name in Map. If updateMax is true and id exceeds the
// current Max, Max is set to id+1. TS callers iterate inclusively
// (`for id := 0; id <= info.max; id++`, e.g. Compiler.ts:205, 215,
// 235, 246, 256, 266) and guard absent ids inside the loop body —
// the loop visits one slot past the last assigned id, intentionally
// empty. runServerCompiler's symbol-table assembly mirrors this `<= Max`
// pattern with a `Map[id]` presence check.
//
// TS Compiler.ts:100-106:
//
//	add(id: number, name: string, updateMax: boolean = true) {
//	    this.map[id] = name;
//	    if (updateMax && this.max < id) {
//	        this.max = id + 1;
//	    }
//	}
func (p *TypeInfo) Add(id int, name string, updateMax bool) {
	p.Map[id] = name
	if updateMax && p.Max < id {
		p.Max = id + 1
	}
}

// Load reads a .pack-style file (one `id=name` entry per line) and
// returns a *TypeInfo populated via Add. Mirrors TS Compiler.ts:38-60
// (CompilerTypeInfo.load).
//
// Skip rules (TS-faithful, in order):
//   - empty line                → skip
//   - line contains no `=`      → skip
//   - name == "null"            → skip
//   - name == "null:null"       → skip
//   - id parse error            → skip (TS parseInt returns NaN;
//     see spec §9 R1 for unreachable-in-
//     practice rationale. .pack files are
//     mechanically generated by
//     pkg/pack/PackFile.Save → always
//     well-formed.)
//
// Missing file → empty *TypeInfo (Max=-1), nil error. Genuine IO
// errors (read of a directory, permission failure, etc.) → (nil, err).
func Load(path string) (*TypeInfo, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return newTypeInfo(), nil
		}
		return nil, err
	}

	p := newTypeInfo()
	// TS splits on /\r?\n/. strings.Split with "\n" handles \n; we strip
	// trailing \r per-line to match the regex.
	for raw := range strings.SplitSeq(string(data), "\n") {
		line := strings.TrimSuffix(raw, "\r")
		if len(line) == 0 {
			continue
		}
		// TS Compiler.ts:46 uses `const [id, name] = line.split('=')`,
		// a destructure of an unbounded split — segments past the second
		// are discarded. SplitN with cap 3 mirrors that: parts[0] = id,
		// parts[1] = name; anything past the second '=' is dropped.
		parts := strings.SplitN(line, "=", 3)
		if len(parts) < 2 {
			continue
		}
		idStr := parts[0]
		name := parts[1]
		if name == "null" || name == "null:null" {
			continue
		}
		id, parseErr := strconv.Atoi(idStr)
		if parseErr != nil {
			// TS parseInt would produce NaN here; goscape skips silently.
			// Unreachable in practice — .pack files are mechanically
			// generated. See spec §9 R1.
			continue
		}
		p.Add(id, name, true)
	}
	return p, nil
}

// LoadArray builds a *TypeInfo by treating each slice index as an ID
// and lowercasing the value. Mirrors TS Compiler.ts:62-70
// (CompilerTypeInfo.loadArray).
//
// Used by runServerCompiler for static enum-like sources:
// fontmetrics (['p11_full','p12_full','b12_full','q8_full']) and locshape (23 entries).
func LoadArray(input []string) *TypeInfo {
	p := newTypeInfo()
	for i, s := range input {
		p.Add(i, strings.ToLower(s), true)
	}
	return p
}

// LoadRecords builds a *TypeInfo from a string-keyed map. The
// valueAsKey flag flips which side of the input becomes the NameMap key.
//
//	false: NameMap[k] = v   (value stored as-is)
//	true:  NameMap[v] = lowercase(k)
//
// TS Compiler.ts:72-84 (CompilerTypeInfo.loadRecords) did
// `pack.map[key] = value.toLowerCase()` for the false branch.
// RuneScriptKt-26 supersedes the TS compiler and reads constant.sym
// (written with raw case by CompilerSymbols.ts) without any lowercasing.
// Lowercasing the value here produces wrong bytecode for mixed-case
// string constants (e.g. "You need..." → "you need..."; B6 Class-1 fix).
//
// The valueAsKey=true path (NameMap[v] = lowercase(k)) is unused in the
// current call graph but preserved for TS-structural fidelity.
//
// Used by runServerCompiler for the constant table loaded
// from data/src/scripts/**/*.constant files.
func LoadRecords(input map[string]string, valueAsKey bool) *TypeInfo {
	p := newTypeInfo()
	for k, v := range input {
		if valueAsKey {
			p.NameMap[v] = strings.ToLower(k)
		} else {
			p.NameMap[k] = v
		}
	}
	return p
}

// LoadMap builds a *TypeInfo from a map[string]int (mirroring TS
// Map<string, number>). The valueAsKey flag flips the direction.
// Mirrors TS Compiler.ts:86-98 (CompilerTypeInfo.loadMap).
//
//	false: NameMap[lowercase(k)] = Itoa(v)
//	true:  NameMap[Itoa(v)]      = lowercase(k)
//
// Iteration-order note: TS Map<string,number> is insertion-ordered;
// Go map[string]int iteration is randomized. Order only matters when
// two distinct keys collide on the same value (valueAsKey=true case).
// In every Compiler.ts call site the input is a static enum
// (PlayerStatMap, NpcStatMap, NpcModeMap) with unique-value-per-key —
// collisions don't occur. See spec §5.6 / §9 R6.
//
// Used by runServerCompiler for stat / npc_stat / npc_mode.
func LoadMap(input map[string]int, valueAsKey bool) *TypeInfo {
	p := newTypeInfo()
	for k, v := range input {
		if valueAsKey {
			p.NameMap[strconv.Itoa(v)] = strings.ToLower(k)
		} else {
			p.NameMap[strings.ToLower(k)] = strconv.Itoa(v)
		}
	}
	return p
}
