// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: friends/friends.proto

package friendspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendsService_WorldConnect_FullMethodName         = "/friends.v1.FriendsService/WorldConnect"
	FriendsService_PlayerLogin_FullMethodName          = "/friends.v1.FriendsService/PlayerLogin"
	FriendsService_PlayerLogout_FullMethodName         = "/friends.v1.FriendsService/PlayerLogout"
	FriendsService_ChatSetMode_FullMethodName          = "/friends.v1.FriendsService/ChatSetMode"
	FriendsService_FriendlistAdd_FullMethodName        = "/friends.v1.FriendsService/FriendlistAdd"
	FriendsService_FriendlistDel_FullMethodName        = "/friends.v1.FriendsService/FriendlistDel"
	FriendsService_IgnorelistAdd_FullMethodName        = "/friends.v1.FriendsService/IgnorelistAdd"
	FriendsService_IgnorelistDel_FullMethodName        = "/friends.v1.FriendsService/IgnorelistDel"
	FriendsService_PrivateMessage_FullMethodName       = "/friends.v1.FriendsService/PrivateMessage"
	FriendsService_PublicMessage_FullMethodName        = "/friends.v1.FriendsService/PublicMessage"
	FriendsService_SubscribeUpdates_FullMethodName     = "/friends.v1.FriendsService/SubscribeUpdates"
	FriendsService_RelayMute_FullMethodName            = "/friends.v1.FriendsService/RelayMute"
	FriendsService_RelayKick_FullMethodName            = "/friends.v1.FriendsService/RelayKick"
	FriendsService_RelayShutdown_FullMethodName        = "/friends.v1.FriendsService/RelayShutdown"
	FriendsService_RelayBroadcast_FullMethodName       = "/friends.v1.FriendsService/RelayBroadcast"
	FriendsService_RelayTrack_FullMethodName           = "/friends.v1.FriendsService/RelayTrack"
	FriendsService_RelayReload_FullMethodName          = "/friends.v1.FriendsService/RelayReload"
	FriendsService_RelayClearLogins_FullMethodName     = "/friends.v1.FriendsService/RelayClearLogins"
	FriendsService_RelayClearLogouts_FullMethodName    = "/friends.v1.FriendsService/RelayClearLogouts"
	FriendsService_RelayQueueScript_FullMethodName     = "/friends.v1.FriendsService/RelayQueueScript"
	FriendsService_SubscribeWorldEvents_FullMethodName = "/friends.v1.FriendsService/SubscribeWorldEvents"
)

// FriendsServiceClient is the client API for FriendsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendsServiceClient interface {
	// Lifecycle. Called once per world on startup; validates profile and
	// initializes the world's player-count slot. Mirrors TS FriendServer
	// WORLD_CONNECT opcode (FriendServer.ts:89-106).
	WorldConnect(ctx context.Context, in *WorldConnectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Player presence. Mirrors TS PLAYER_LOGIN/PLAYER_LOGOUT/PLAYER_CHAT_SETMODE.
	PlayerLogin(ctx context.Context, in *PlayerLoginRequest, opts ...grpc.CallOption) (*PlayerLoginResponse, error)
	PlayerLogout(ctx context.Context, in *PlayerLogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ChatSetMode(ctx context.Context, in *ChatSetModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Social-list mutations. Mirrors TS FRIENDLIST_ADD/DEL, IGNORELIST_ADD/DEL.
	FriendlistAdd(ctx context.Context, in *FriendlistAddRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FriendlistDel(ctx context.Context, in *FriendlistDelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IgnorelistAdd(ctx context.Context, in *IgnorelistAddRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IgnorelistDel(ctx context.Context, in *IgnorelistDelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Chat. Mirrors TS PRIVATE_MESSAGE. Server persists then delivers via
	// SubscribeUpdates fan-out; insert error → codes.Internal.
	PrivateMessage(ctx context.Context, in *PrivateMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Public-chat audit log. Mirrors TS FriendServer.ts:291-307 — append-
	// only persistence keyed by username + profile + world (rev-244 re-key:
	// TS re-keyed from session_uuid to username at FriendServer.ts:292-293).
	// No delivery half; the world handles in-world chat propagation itself.
	// Insert error → codes.Internal.
	PublicMessage(ctx context.Context, in *PublicMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Server -> world push. Server streams update events for a single
	// (world, player) subscription. Backed by a per-profile, per-subscriber
	// registry with broadcastWorldToFollowers fan-out on mutating RPCs.
	// rev-244: profile-scoped registries; each profile is an isolated
	// namespace (FriendServer.ts:546-722).
	SubscribeUpdates(ctx context.Context, in *SubscribeUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FriendsUpdate], error)
	// Cross-world admin relay. Each RPC accepts a target_world_id; the
	// server forwards a WorldEvent to that world's SubscribeWorldEvents
	// stream. No-op if no world is subscribed for target_world_id (matches
	// TS FriendServer.ts:298-302 `if (typeof this.socketByWorld[nodeId] !== 'undefined')`).
	// NAI-S5A-D-NO-ADMIN-AUTH-AT-SERVER — friends-server is dumb routing;
	// admin checks live on both sender and receiver world.
	RelayMute(ctx context.Context, in *RelayMuteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayKick(ctx context.Context, in *RelayKickRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayShutdown(ctx context.Context, in *RelayShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayBroadcast(ctx context.Context, in *RelayBroadcastRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayTrack(ctx context.Context, in *RelayTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayReload(ctx context.Context, in *RelayReloadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayClearLogins(ctx context.Context, in *RelayClearLoginsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayClearLogouts(ctx context.Context, in *RelayClearLogoutsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RelayQueueScript(ctx context.Context, in *RelayQueueScriptRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Server -> world push for cross-world admin events. One subscriber per
	// world (owned by world.Server); the world-side dispatcher applies
	// world-state effects on inbound events. rev-244: profile-scoped
	// registries; each profile is an isolated namespace
	// (FriendServer.ts:546-722).
	// NAI-S5A-D-PERWORLD-EVENTS-STREAM-SEPARATE — second stream RPC
	// alongside SubscribeUpdates; goscape has two parallel streams where
	// TS has one socket. Permanent; reviewer traceability only.
	SubscribeWorldEvents(ctx context.Context, in *SubscribeWorldEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldEvent], error)
}

type friendsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendsServiceClient(cc grpc.ClientConnInterface) FriendsServiceClient {
	return &friendsServiceClient{cc}
}

func (c *friendsServiceClient) WorldConnect(ctx context.Context, in *WorldConnectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_WorldConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) PlayerLogin(ctx context.Context, in *PlayerLoginRequest, opts ...grpc.CallOption) (*PlayerLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerLoginResponse)
	err := c.cc.Invoke(ctx, FriendsService_PlayerLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) PlayerLogout(ctx context.Context, in *PlayerLogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_PlayerLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) ChatSetMode(ctx context.Context, in *ChatSetModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_ChatSetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) FriendlistAdd(ctx context.Context, in *FriendlistAddRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_FriendlistAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) FriendlistDel(ctx context.Context, in *FriendlistDelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_FriendlistDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) IgnorelistAdd(ctx context.Context, in *IgnorelistAddRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_IgnorelistAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) IgnorelistDel(ctx context.Context, in *IgnorelistDelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_IgnorelistDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) PrivateMessage(ctx context.Context, in *PrivateMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_PrivateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) PublicMessage(ctx context.Context, in *PublicMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_PublicMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) SubscribeUpdates(ctx context.Context, in *SubscribeUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FriendsUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FriendsService_ServiceDesc.Streams[0], FriendsService_SubscribeUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeUpdatesRequest, FriendsUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FriendsService_SubscribeUpdatesClient = grpc.ServerStreamingClient[FriendsUpdate]

func (c *friendsServiceClient) RelayMute(ctx context.Context, in *RelayMuteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayMute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayKick(ctx context.Context, in *RelayKickRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayKick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayShutdown(ctx context.Context, in *RelayShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayBroadcast(ctx context.Context, in *RelayBroadcastRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayTrack(ctx context.Context, in *RelayTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayReload(ctx context.Context, in *RelayReloadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayReload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayClearLogins(ctx context.Context, in *RelayClearLoginsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayClearLogins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayClearLogouts(ctx context.Context, in *RelayClearLogoutsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayClearLogouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) RelayQueueScript(ctx context.Context, in *RelayQueueScriptRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FriendsService_RelayQueueScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiceClient) SubscribeWorldEvents(ctx context.Context, in *SubscribeWorldEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FriendsService_ServiceDesc.Streams[1], FriendsService_SubscribeWorldEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeWorldEventsRequest, WorldEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FriendsService_SubscribeWorldEventsClient = grpc.ServerStreamingClient[WorldEvent]

// FriendsServiceServer is the server API for FriendsService service.
// All implementations must embed UnimplementedFriendsServiceServer
// for forward compatibility.
type FriendsServiceServer interface {
	// Lifecycle. Called once per world on startup; validates profile and
	// initializes the world's player-count slot. Mirrors TS FriendServer
	// WORLD_CONNECT opcode (FriendServer.ts:89-106).
	WorldConnect(context.Context, *WorldConnectRequest) (*emptypb.Empty, error)
	// Player presence. Mirrors TS PLAYER_LOGIN/PLAYER_LOGOUT/PLAYER_CHAT_SETMODE.
	PlayerLogin(context.Context, *PlayerLoginRequest) (*PlayerLoginResponse, error)
	PlayerLogout(context.Context, *PlayerLogoutRequest) (*emptypb.Empty, error)
	ChatSetMode(context.Context, *ChatSetModeRequest) (*emptypb.Empty, error)
	// Social-list mutations. Mirrors TS FRIENDLIST_ADD/DEL, IGNORELIST_ADD/DEL.
	FriendlistAdd(context.Context, *FriendlistAddRequest) (*emptypb.Empty, error)
	FriendlistDel(context.Context, *FriendlistDelRequest) (*emptypb.Empty, error)
	IgnorelistAdd(context.Context, *IgnorelistAddRequest) (*emptypb.Empty, error)
	IgnorelistDel(context.Context, *IgnorelistDelRequest) (*emptypb.Empty, error)
	// Chat. Mirrors TS PRIVATE_MESSAGE. Server persists then delivers via
	// SubscribeUpdates fan-out; insert error → codes.Internal.
	PrivateMessage(context.Context, *PrivateMessageRequest) (*emptypb.Empty, error)
	// Public-chat audit log. Mirrors TS FriendServer.ts:291-307 — append-
	// only persistence keyed by username + profile + world (rev-244 re-key:
	// TS re-keyed from session_uuid to username at FriendServer.ts:292-293).
	// No delivery half; the world handles in-world chat propagation itself.
	// Insert error → codes.Internal.
	PublicMessage(context.Context, *PublicMessageRequest) (*emptypb.Empty, error)
	// Server -> world push. Server streams update events for a single
	// (world, player) subscription. Backed by a per-profile, per-subscriber
	// registry with broadcastWorldToFollowers fan-out on mutating RPCs.
	// rev-244: profile-scoped registries; each profile is an isolated
	// namespace (FriendServer.ts:546-722).
	SubscribeUpdates(*SubscribeUpdatesRequest, grpc.ServerStreamingServer[FriendsUpdate]) error
	// Cross-world admin relay. Each RPC accepts a target_world_id; the
	// server forwards a WorldEvent to that world's SubscribeWorldEvents
	// stream. No-op if no world is subscribed for target_world_id (matches
	// TS FriendServer.ts:298-302 `if (typeof this.socketByWorld[nodeId] !== 'undefined')`).
	// NAI-S5A-D-NO-ADMIN-AUTH-AT-SERVER — friends-server is dumb routing;
	// admin checks live on both sender and receiver world.
	RelayMute(context.Context, *RelayMuteRequest) (*emptypb.Empty, error)
	RelayKick(context.Context, *RelayKickRequest) (*emptypb.Empty, error)
	RelayShutdown(context.Context, *RelayShutdownRequest) (*emptypb.Empty, error)
	RelayBroadcast(context.Context, *RelayBroadcastRequest) (*emptypb.Empty, error)
	RelayTrack(context.Context, *RelayTrackRequest) (*emptypb.Empty, error)
	RelayReload(context.Context, *RelayReloadRequest) (*emptypb.Empty, error)
	RelayClearLogins(context.Context, *RelayClearLoginsRequest) (*emptypb.Empty, error)
	RelayClearLogouts(context.Context, *RelayClearLogoutsRequest) (*emptypb.Empty, error)
	RelayQueueScript(context.Context, *RelayQueueScriptRequest) (*emptypb.Empty, error)
	// Server -> world push for cross-world admin events. One subscriber per
	// world (owned by world.Server); the world-side dispatcher applies
	// world-state effects on inbound events. rev-244: profile-scoped
	// registries; each profile is an isolated namespace
	// (FriendServer.ts:546-722).
	// NAI-S5A-D-PERWORLD-EVENTS-STREAM-SEPARATE — second stream RPC
	// alongside SubscribeUpdates; goscape has two parallel streams where
	// TS has one socket. Permanent; reviewer traceability only.
	SubscribeWorldEvents(*SubscribeWorldEventsRequest, grpc.ServerStreamingServer[WorldEvent]) error
	mustEmbedUnimplementedFriendsServiceServer()
}

// UnimplementedFriendsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendsServiceServer struct{}

func (UnimplementedFriendsServiceServer) WorldConnect(context.Context, *WorldConnectRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WorldConnect not implemented")
}
func (UnimplementedFriendsServiceServer) PlayerLogin(context.Context, *PlayerLoginRequest) (*PlayerLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerLogin not implemented")
}
func (UnimplementedFriendsServiceServer) PlayerLogout(context.Context, *PlayerLogoutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerLogout not implemented")
}
func (UnimplementedFriendsServiceServer) ChatSetMode(context.Context, *ChatSetModeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatSetMode not implemented")
}
func (UnimplementedFriendsServiceServer) FriendlistAdd(context.Context, *FriendlistAddRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FriendlistAdd not implemented")
}
func (UnimplementedFriendsServiceServer) FriendlistDel(context.Context, *FriendlistDelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FriendlistDel not implemented")
}
func (UnimplementedFriendsServiceServer) IgnorelistAdd(context.Context, *IgnorelistAddRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IgnorelistAdd not implemented")
}
func (UnimplementedFriendsServiceServer) IgnorelistDel(context.Context, *IgnorelistDelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IgnorelistDel not implemented")
}
func (UnimplementedFriendsServiceServer) PrivateMessage(context.Context, *PrivateMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PrivateMessage not implemented")
}
func (UnimplementedFriendsServiceServer) PublicMessage(context.Context, *PublicMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicMessage not implemented")
}
func (UnimplementedFriendsServiceServer) SubscribeUpdates(*SubscribeUpdatesRequest, grpc.ServerStreamingServer[FriendsUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeUpdates not implemented")
}
func (UnimplementedFriendsServiceServer) RelayMute(context.Context, *RelayMuteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayMute not implemented")
}
func (UnimplementedFriendsServiceServer) RelayKick(context.Context, *RelayKickRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayKick not implemented")
}
func (UnimplementedFriendsServiceServer) RelayShutdown(context.Context, *RelayShutdownRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayShutdown not implemented")
}
func (UnimplementedFriendsServiceServer) RelayBroadcast(context.Context, *RelayBroadcastRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayBroadcast not implemented")
}
func (UnimplementedFriendsServiceServer) RelayTrack(context.Context, *RelayTrackRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayTrack not implemented")
}
func (UnimplementedFriendsServiceServer) RelayReload(context.Context, *RelayReloadRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayReload not implemented")
}
func (UnimplementedFriendsServiceServer) RelayClearLogins(context.Context, *RelayClearLoginsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayClearLogins not implemented")
}
func (UnimplementedFriendsServiceServer) RelayClearLogouts(context.Context, *RelayClearLogoutsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayClearLogouts not implemented")
}
func (UnimplementedFriendsServiceServer) RelayQueueScript(context.Context, *RelayQueueScriptRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayQueueScript not implemented")
}
func (UnimplementedFriendsServiceServer) SubscribeWorldEvents(*SubscribeWorldEventsRequest, grpc.ServerStreamingServer[WorldEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeWorldEvents not implemented")
}
func (UnimplementedFriendsServiceServer) mustEmbedUnimplementedFriendsServiceServer() {}
func (UnimplementedFriendsServiceServer) testEmbeddedByValue()                        {}

// UnsafeFriendsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendsServiceServer will
// result in compilation errors.
type UnsafeFriendsServiceServer interface {
	mustEmbedUnimplementedFriendsServiceServer()
}

func RegisterFriendsServiceServer(s grpc.ServiceRegistrar, srv FriendsServiceServer) {
	// If the following call panics, it indicates UnimplementedFriendsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendsService_ServiceDesc, srv)
}

func _FriendsService_WorldConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorldConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).WorldConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_WorldConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).WorldConnect(ctx, req.(*WorldConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_PlayerLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).PlayerLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_PlayerLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).PlayerLogin(ctx, req.(*PlayerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_PlayerLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).PlayerLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_PlayerLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).PlayerLogout(ctx, req.(*PlayerLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_ChatSetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatSetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).ChatSetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_ChatSetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).ChatSetMode(ctx, req.(*ChatSetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_FriendlistAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendlistAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).FriendlistAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_FriendlistAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).FriendlistAdd(ctx, req.(*FriendlistAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_FriendlistDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendlistDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).FriendlistDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_FriendlistDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).FriendlistDel(ctx, req.(*FriendlistDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_IgnorelistAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IgnorelistAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).IgnorelistAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_IgnorelistAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).IgnorelistAdd(ctx, req.(*IgnorelistAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_IgnorelistDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IgnorelistDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).IgnorelistDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_IgnorelistDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).IgnorelistDel(ctx, req.(*IgnorelistDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_PrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).PrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_PrivateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).PrivateMessage(ctx, req.(*PrivateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_PublicMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).PublicMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_PublicMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).PublicMessage(ctx, req.(*PublicMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_SubscribeUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FriendsServiceServer).SubscribeUpdates(m, &grpc.GenericServerStream[SubscribeUpdatesRequest, FriendsUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FriendsService_SubscribeUpdatesServer = grpc.ServerStreamingServer[FriendsUpdate]

func _FriendsService_RelayMute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayMuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayMute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayMute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayMute(ctx, req.(*RelayMuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayKick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayKickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayKick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayKick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayKick(ctx, req.(*RelayKickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayShutdown(ctx, req.(*RelayShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayBroadcast(ctx, req.(*RelayBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayTrack(ctx, req.(*RelayTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayReload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayReload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayReload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayReload(ctx, req.(*RelayReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayClearLogins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayClearLoginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayClearLogins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayClearLogins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayClearLogins(ctx, req.(*RelayClearLoginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayClearLogouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayClearLogoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayClearLogouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayClearLogouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayClearLogouts(ctx, req.(*RelayClearLogoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_RelayQueueScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayQueueScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiceServer).RelayQueueScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendsService_RelayQueueScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiceServer).RelayQueueScript(ctx, req.(*RelayQueueScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsService_SubscribeWorldEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeWorldEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FriendsServiceServer).SubscribeWorldEvents(m, &grpc.GenericServerStream[SubscribeWorldEventsRequest, WorldEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FriendsService_SubscribeWorldEventsServer = grpc.ServerStreamingServer[WorldEvent]

// FriendsService_ServiceDesc is the grpc.ServiceDesc for FriendsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friends.v1.FriendsService",
	HandlerType: (*FriendsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorldConnect",
			Handler:    _FriendsService_WorldConnect_Handler,
		},
		{
			MethodName: "PlayerLogin",
			Handler:    _FriendsService_PlayerLogin_Handler,
		},
		{
			MethodName: "PlayerLogout",
			Handler:    _FriendsService_PlayerLogout_Handler,
		},
		{
			MethodName: "ChatSetMode",
			Handler:    _FriendsService_ChatSetMode_Handler,
		},
		{
			MethodName: "FriendlistAdd",
			Handler:    _FriendsService_FriendlistAdd_Handler,
		},
		{
			MethodName: "FriendlistDel",
			Handler:    _FriendsService_FriendlistDel_Handler,
		},
		{
			MethodName: "IgnorelistAdd",
			Handler:    _FriendsService_IgnorelistAdd_Handler,
		},
		{
			MethodName: "IgnorelistDel",
			Handler:    _FriendsService_IgnorelistDel_Handler,
		},
		{
			MethodName: "PrivateMessage",
			Handler:    _FriendsService_PrivateMessage_Handler,
		},
		{
			MethodName: "PublicMessage",
			Handler:    _FriendsService_PublicMessage_Handler,
		},
		{
			MethodName: "RelayMute",
			Handler:    _FriendsService_RelayMute_Handler,
		},
		{
			MethodName: "RelayKick",
			Handler:    _FriendsService_RelayKick_Handler,
		},
		{
			MethodName: "RelayShutdown",
			Handler:    _FriendsService_RelayShutdown_Handler,
		},
		{
			MethodName: "RelayBroadcast",
			Handler:    _FriendsService_RelayBroadcast_Handler,
		},
		{
			MethodName: "RelayTrack",
			Handler:    _FriendsService_RelayTrack_Handler,
		},
		{
			MethodName: "RelayReload",
			Handler:    _FriendsService_RelayReload_Handler,
		},
		{
			MethodName: "RelayClearLogins",
			Handler:    _FriendsService_RelayClearLogins_Handler,
		},
		{
			MethodName: "RelayClearLogouts",
			Handler:    _FriendsService_RelayClearLogouts_Handler,
		},
		{
			MethodName: "RelayQueueScript",
			Handler:    _FriendsService_RelayQueueScript_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeUpdates",
			Handler:       _FriendsService_SubscribeUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeWorldEvents",
			Handler:       _FriendsService_SubscribeWorldEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "friends/friends.proto",
}
