// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: friends/friends.proto

package friendspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorldConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldConnectRequest) Reset() {
	*x = WorldConnectRequest{}
	mi := &file_friends_friends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldConnectRequest) ProtoMessage() {}

func (x *WorldConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldConnectRequest.ProtoReflect.Descriptor instead.
func (*WorldConnectRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{0}
}

func (x *WorldConnectRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *WorldConnectRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type PlayerLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37    uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	PrivateChat   int32                  `protobuf:"varint,3,opt,name=private_chat,json=privateChat,proto3" json:"private_chat,omitempty"`
	StaffLvl      int32                  `protobuf:"varint,4,opt,name=staff_lvl,json=staffLvl,proto3" json:"staff_lvl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginRequest) Reset() {
	*x = PlayerLoginRequest{}
	mi := &file_friends_friends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginRequest) ProtoMessage() {}

func (x *PlayerLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginRequest.ProtoReflect.Descriptor instead.
func (*PlayerLoginRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerLoginRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PlayerLoginRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

func (x *PlayerLoginRequest) GetPrivateChat() int32 {
	if x != nil {
		return x.PrivateChat
	}
	return 0
}

func (x *PlayerLoginRequest) GetStaffLvl() int32 {
	if x != nil {
		return x.StaffLvl
	}
	return 0
}

type PlayerLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reserved for slice 4 (per-RPC player-cap surfacing). Slice 1 leaves
	// unset; handler logs warn on cap rejection but accepts the call.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginResponse) Reset() {
	*x = PlayerLoginResponse{}
	mi := &file_friends_friends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginResponse) ProtoMessage() {}

func (x *PlayerLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginResponse.ProtoReflect.Descriptor instead.
func (*PlayerLoginResponse) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLoginResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type PlayerLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37    uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLogoutRequest) Reset() {
	*x = PlayerLogoutRequest{}
	mi := &file_friends_friends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogoutRequest) ProtoMessage() {}

func (x *PlayerLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogoutRequest.ProtoReflect.Descriptor instead.
func (*PlayerLogoutRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLogoutRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PlayerLogoutRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

type ChatSetModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37    uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	PrivateChat   int32                  `protobuf:"varint,3,opt,name=private_chat,json=privateChat,proto3" json:"private_chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSetModeRequest) Reset() {
	*x = ChatSetModeRequest{}
	mi := &file_friends_friends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSetModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSetModeRequest) ProtoMessage() {}

func (x *ChatSetModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSetModeRequest.ProtoReflect.Descriptor instead.
func (*ChatSetModeRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{4}
}

func (x *ChatSetModeRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *ChatSetModeRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

func (x *ChatSetModeRequest) GetPrivateChat() int32 {
	if x != nil {
		return x.PrivateChat
	}
	return 0
}

type FriendlistAddRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorldId          int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37       uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	TargetUsername37 uint64                 `protobuf:"varint,3,opt,name=target_username37,json=targetUsername37,proto3" json:"target_username37,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FriendlistAddRequest) Reset() {
	*x = FriendlistAddRequest{}
	mi := &file_friends_friends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendlistAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendlistAddRequest) ProtoMessage() {}

func (x *FriendlistAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendlistAddRequest.ProtoReflect.Descriptor instead.
func (*FriendlistAddRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{5}
}

func (x *FriendlistAddRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *FriendlistAddRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

func (x *FriendlistAddRequest) GetTargetUsername37() uint64 {
	if x != nil {
		return x.TargetUsername37
	}
	return 0
}

type FriendlistDelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorldId          int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37       uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	TargetUsername37 uint64                 `protobuf:"varint,3,opt,name=target_username37,json=targetUsername37,proto3" json:"target_username37,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FriendlistDelRequest) Reset() {
	*x = FriendlistDelRequest{}
	mi := &file_friends_friends_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendlistDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendlistDelRequest) ProtoMessage() {}

func (x *FriendlistDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendlistDelRequest.ProtoReflect.Descriptor instead.
func (*FriendlistDelRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{6}
}

func (x *FriendlistDelRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *FriendlistDelRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

func (x *FriendlistDelRequest) GetTargetUsername37() uint64 {
	if x != nil {
		return x.TargetUsername37
	}
	return 0
}

type IgnorelistAddRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorldId          int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37       uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	TargetUsername37 uint64                 `protobuf:"varint,3,opt,name=target_username37,json=targetUsername37,proto3" json:"target_username37,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IgnorelistAddRequest) Reset() {
	*x = IgnorelistAddRequest{}
	mi := &file_friends_friends_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgnorelistAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnorelistAddRequest) ProtoMessage() {}

func (x *IgnorelistAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnorelistAddRequest.ProtoReflect.Descriptor instead.
func (*IgnorelistAddRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{7}
}

func (x *IgnorelistAddRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *IgnorelistAddRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

func (x *IgnorelistAddRequest) GetTargetUsername37() uint64 {
	if x != nil {
		return x.TargetUsername37
	}
	return 0
}

type IgnorelistDelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorldId          int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37       uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	TargetUsername37 uint64                 `protobuf:"varint,3,opt,name=target_username37,json=targetUsername37,proto3" json:"target_username37,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IgnorelistDelRequest) Reset() {
	*x = IgnorelistDelRequest{}
	mi := &file_friends_friends_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgnorelistDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnorelistDelRequest) ProtoMessage() {}

func (x *IgnorelistDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnorelistDelRequest.ProtoReflect.Descriptor instead.
func (*IgnorelistDelRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{8}
}

func (x *IgnorelistDelRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *IgnorelistDelRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

func (x *IgnorelistDelRequest) GetTargetUsername37() uint64 {
	if x != nil {
		return x.TargetUsername37
	}
	return 0
}

type PrivateMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorldId          int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37       uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	TargetUsername37 uint64                 `protobuf:"varint,3,opt,name=target_username37,json=targetUsername37,proto3" json:"target_username37,omitempty"`
	StaffLvl         int32                  `protobuf:"varint,4,opt,name=staff_lvl,json=staffLvl,proto3" json:"staff_lvl,omitempty"`
	PmId             uint32                 `protobuf:"varint,5,opt,name=pm_id,json=pmId,proto3" json:"pm_id,omitempty"`
	Chat             string                 `protobuf:"bytes,6,opt,name=chat,proto3" json:"chat,omitempty"`
	Coord            int32                  `protobuf:"varint,7,opt,name=coord,proto3" json:"coord,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrivateMessageRequest) Reset() {
	*x = PrivateMessageRequest{}
	mi := &file_friends_friends_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessageRequest) ProtoMessage() {}

func (x *PrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*PrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{9}
}

func (x *PrivateMessageRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PrivateMessageRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

func (x *PrivateMessageRequest) GetTargetUsername37() uint64 {
	if x != nil {
		return x.TargetUsername37
	}
	return 0
}

func (x *PrivateMessageRequest) GetStaffLvl() int32 {
	if x != nil {
		return x.StaffLvl
	}
	return 0
}

func (x *PrivateMessageRequest) GetPmId() uint32 {
	if x != nil {
		return x.PmId
	}
	return 0
}

func (x *PrivateMessageRequest) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

func (x *PrivateMessageRequest) GetCoord() int32 {
	if x != nil {
		return x.Coord
	}
	return 0
}

type SubscribeUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37    uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUpdatesRequest) Reset() {
	*x = SubscribeUpdatesRequest{}
	mi := &file_friends_friends_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUpdatesRequest) ProtoMessage() {}

func (x *SubscribeUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUpdatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeUpdatesRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *SubscribeUpdatesRequest) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

type FriendsUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*FriendsUpdate_Friendlist
	//	*FriendsUpdate_Ignorelist
	//	*FriendsUpdate_PrivateMessage
	Update        isFriendsUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendsUpdate) Reset() {
	*x = FriendsUpdate{}
	mi := &file_friends_friends_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsUpdate) ProtoMessage() {}

func (x *FriendsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsUpdate.ProtoReflect.Descriptor instead.
func (*FriendsUpdate) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{11}
}

func (x *FriendsUpdate) GetUpdate() isFriendsUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *FriendsUpdate) GetFriendlist() *FriendlistUpdate {
	if x != nil {
		if x, ok := x.Update.(*FriendsUpdate_Friendlist); ok {
			return x.Friendlist
		}
	}
	return nil
}

func (x *FriendsUpdate) GetIgnorelist() *IgnorelistUpdate {
	if x != nil {
		if x, ok := x.Update.(*FriendsUpdate_Ignorelist); ok {
			return x.Ignorelist
		}
	}
	return nil
}

func (x *FriendsUpdate) GetPrivateMessage() *PrivateMessageDelivery {
	if x != nil {
		if x, ok := x.Update.(*FriendsUpdate_PrivateMessage); ok {
			return x.PrivateMessage
		}
	}
	return nil
}

type isFriendsUpdate_Update interface {
	isFriendsUpdate_Update()
}

type FriendsUpdate_Friendlist struct {
	Friendlist *FriendlistUpdate `protobuf:"bytes,1,opt,name=friendlist,proto3,oneof"`
}

type FriendsUpdate_Ignorelist struct {
	Ignorelist *IgnorelistUpdate `protobuf:"bytes,2,opt,name=ignorelist,proto3,oneof"`
}

type FriendsUpdate_PrivateMessage struct {
	PrivateMessage *PrivateMessageDelivery `protobuf:"bytes,3,opt,name=private_message,json=privateMessage,proto3,oneof"`
}

func (*FriendsUpdate_Friendlist) isFriendsUpdate_Update() {}

func (*FriendsUpdate_Ignorelist) isFriendsUpdate_Update() {}

func (*FriendsUpdate_PrivateMessage) isFriendsUpdate_Update() {}

type FriendlistUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (world_id, username37) pairs. world_id=0 means offline/hidden.
	Entries       []*FriendEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendlistUpdate) Reset() {
	*x = FriendlistUpdate{}
	mi := &file_friends_friends_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendlistUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendlistUpdate) ProtoMessage() {}

func (x *FriendlistUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendlistUpdate.ProtoReflect.Descriptor instead.
func (*FriendlistUpdate) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{12}
}

func (x *FriendlistUpdate) GetEntries() []*FriendEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FriendEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int32                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Username37    uint64                 `protobuf:"varint,2,opt,name=username37,proto3" json:"username37,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendEntry) Reset() {
	*x = FriendEntry{}
	mi := &file_friends_friends_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendEntry) ProtoMessage() {}

func (x *FriendEntry) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendEntry.ProtoReflect.Descriptor instead.
func (*FriendEntry) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{13}
}

func (x *FriendEntry) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *FriendEntry) GetUsername37() uint64 {
	if x != nil {
		return x.Username37
	}
	return 0
}

type IgnorelistUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username37    []uint64               `protobuf:"varint,1,rep,packed,name=username37,proto3" json:"username37,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgnorelistUpdate) Reset() {
	*x = IgnorelistUpdate{}
	mi := &file_friends_friends_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgnorelistUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnorelistUpdate) ProtoMessage() {}

func (x *IgnorelistUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnorelistUpdate.ProtoReflect.Descriptor instead.
func (*IgnorelistUpdate) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{14}
}

func (x *IgnorelistUpdate) GetUsername37() []uint64 {
	if x != nil {
		return x.Username37
	}
	return nil
}

type PrivateMessageDelivery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromUsername37 uint64                 `protobuf:"varint,1,opt,name=from_username37,json=fromUsername37,proto3" json:"from_username37,omitempty"`
	StaffLvl       int32                  `protobuf:"varint,2,opt,name=staff_lvl,json=staffLvl,proto3" json:"staff_lvl,omitempty"`
	PmId           uint32                 `protobuf:"varint,3,opt,name=pm_id,json=pmId,proto3" json:"pm_id,omitempty"`
	Chat           string                 `protobuf:"bytes,4,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrivateMessageDelivery) Reset() {
	*x = PrivateMessageDelivery{}
	mi := &file_friends_friends_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessageDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessageDelivery) ProtoMessage() {}

func (x *PrivateMessageDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_friends_friends_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessageDelivery.ProtoReflect.Descriptor instead.
func (*PrivateMessageDelivery) Descriptor() ([]byte, []int) {
	return file_friends_friends_proto_rawDescGZIP(), []int{15}
}

func (x *PrivateMessageDelivery) GetFromUsername37() uint64 {
	if x != nil {
		return x.FromUsername37
	}
	return 0
}

func (x *PrivateMessageDelivery) GetStaffLvl() int32 {
	if x != nil {
		return x.StaffLvl
	}
	return 0
}

func (x *PrivateMessageDelivery) GetPmId() uint32 {
	if x != nil {
		return x.PmId
	}
	return 0
}

func (x *PrivateMessageDelivery) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

var File_friends_friends_proto protoreflect.FileDescriptor

const file_friends_friends_proto_rawDesc = "" +
	"\n" +
	"\x15friends/friends.proto\x12\n" +
	"friends.v1\x1a\x1bgoogle/protobuf/empty.proto\"J\n" +
	"\x13WorldConnectRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\"\x8f\x01\n" +
	"\x12PlayerLoginRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\x12!\n" +
	"\fprivate_chat\x18\x03 \x01(\x05R\vprivateChat\x12\x1b\n" +
	"\tstaff_lvl\x18\x04 \x01(\x05R\bstaffLvl\"1\n" +
	"\x13PlayerLoginResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"P\n" +
	"\x13PlayerLogoutRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\"r\n" +
	"\x12ChatSetModeRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\x12!\n" +
	"\fprivate_chat\x18\x03 \x01(\x05R\vprivateChat\"~\n" +
	"\x14FriendlistAddRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\x12+\n" +
	"\x11target_username37\x18\x03 \x01(\x04R\x10targetUsername37\"~\n" +
	"\x14FriendlistDelRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\x12+\n" +
	"\x11target_username37\x18\x03 \x01(\x04R\x10targetUsername37\"~\n" +
	"\x14IgnorelistAddRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\x12+\n" +
	"\x11target_username37\x18\x03 \x01(\x04R\x10targetUsername37\"~\n" +
	"\x14IgnorelistDelRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\x12+\n" +
	"\x11target_username37\x18\x03 \x01(\x04R\x10targetUsername37\"\xdb\x01\n" +
	"\x15PrivateMessageRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\x12+\n" +
	"\x11target_username37\x18\x03 \x01(\x04R\x10targetUsername37\x12\x1b\n" +
	"\tstaff_lvl\x18\x04 \x01(\x05R\bstaffLvl\x12\x13\n" +
	"\x05pm_id\x18\x05 \x01(\rR\x04pmId\x12\x12\n" +
	"\x04chat\x18\x06 \x01(\tR\x04chat\x12\x14\n" +
	"\x05coord\x18\a \x01(\x05R\x05coord\"T\n" +
	"\x17SubscribeUpdatesRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\"\xe8\x01\n" +
	"\rFriendsUpdate\x12>\n" +
	"\n" +
	"friendlist\x18\x01 \x01(\v2\x1c.friends.v1.FriendlistUpdateH\x00R\n" +
	"friendlist\x12>\n" +
	"\n" +
	"ignorelist\x18\x02 \x01(\v2\x1c.friends.v1.IgnorelistUpdateH\x00R\n" +
	"ignorelist\x12M\n" +
	"\x0fprivate_message\x18\x03 \x01(\v2\".friends.v1.PrivateMessageDeliveryH\x00R\x0eprivateMessageB\b\n" +
	"\x06update\"E\n" +
	"\x10FriendlistUpdate\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.friends.v1.FriendEntryR\aentries\"H\n" +
	"\vFriendEntry\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x05R\aworldId\x12\x1e\n" +
	"\n" +
	"username37\x18\x02 \x01(\x04R\n" +
	"username37\"2\n" +
	"\x10IgnorelistUpdate\x12\x1e\n" +
	"\n" +
	"username37\x18\x01 \x03(\x04R\n" +
	"username37\"\x87\x01\n" +
	"\x16PrivateMessageDelivery\x12'\n" +
	"\x0ffrom_username37\x18\x01 \x01(\x04R\x0efromUsername37\x12\x1b\n" +
	"\tstaff_lvl\x18\x02 \x01(\x05R\bstaffLvl\x12\x13\n" +
	"\x05pm_id\x18\x03 \x01(\rR\x04pmId\x12\x12\n" +
	"\x04chat\x18\x04 \x01(\tR\x04chat2\x88\x06\n" +
	"\x0eFriendsService\x12G\n" +
	"\fWorldConnect\x12\x1f.friends.v1.WorldConnectRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\vPlayerLogin\x12\x1e.friends.v1.PlayerLoginRequest\x1a\x1f.friends.v1.PlayerLoginResponse\x12G\n" +
	"\fPlayerLogout\x12\x1f.friends.v1.PlayerLogoutRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\vChatSetMode\x12\x1e.friends.v1.ChatSetModeRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rFriendlistAdd\x12 .friends.v1.FriendlistAddRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rFriendlistDel\x12 .friends.v1.FriendlistDelRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rIgnorelistAdd\x12 .friends.v1.IgnorelistAddRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rIgnorelistDel\x12 .friends.v1.IgnorelistDelRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x0ePrivateMessage\x12!.friends.v1.PrivateMessageRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x10SubscribeUpdates\x12#.friends.v1.SubscribeUpdatesRequest\x1a\x19.friends.v1.FriendsUpdate0\x01B'Z%github.com/zsrv/goscape/pkg/friendspbb\x06proto3"

var (
	file_friends_friends_proto_rawDescOnce sync.Once
	file_friends_friends_proto_rawDescData []byte
)

func file_friends_friends_proto_rawDescGZIP() []byte {
	file_friends_friends_proto_rawDescOnce.Do(func() {
		file_friends_friends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friends_friends_proto_rawDesc), len(file_friends_friends_proto_rawDesc)))
	})
	return file_friends_friends_proto_rawDescData
}

var file_friends_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_friends_friends_proto_goTypes = []any{
	(*WorldConnectRequest)(nil),     // 0: friends.v1.WorldConnectRequest
	(*PlayerLoginRequest)(nil),      // 1: friends.v1.PlayerLoginRequest
	(*PlayerLoginResponse)(nil),     // 2: friends.v1.PlayerLoginResponse
	(*PlayerLogoutRequest)(nil),     // 3: friends.v1.PlayerLogoutRequest
	(*ChatSetModeRequest)(nil),      // 4: friends.v1.ChatSetModeRequest
	(*FriendlistAddRequest)(nil),    // 5: friends.v1.FriendlistAddRequest
	(*FriendlistDelRequest)(nil),    // 6: friends.v1.FriendlistDelRequest
	(*IgnorelistAddRequest)(nil),    // 7: friends.v1.IgnorelistAddRequest
	(*IgnorelistDelRequest)(nil),    // 8: friends.v1.IgnorelistDelRequest
	(*PrivateMessageRequest)(nil),   // 9: friends.v1.PrivateMessageRequest
	(*SubscribeUpdatesRequest)(nil), // 10: friends.v1.SubscribeUpdatesRequest
	(*FriendsUpdate)(nil),           // 11: friends.v1.FriendsUpdate
	(*FriendlistUpdate)(nil),        // 12: friends.v1.FriendlistUpdate
	(*FriendEntry)(nil),             // 13: friends.v1.FriendEntry
	(*IgnorelistUpdate)(nil),        // 14: friends.v1.IgnorelistUpdate
	(*PrivateMessageDelivery)(nil),  // 15: friends.v1.PrivateMessageDelivery
	(*emptypb.Empty)(nil),           // 16: google.protobuf.Empty
}
var file_friends_friends_proto_depIdxs = []int32{
	12, // 0: friends.v1.FriendsUpdate.friendlist:type_name -> friends.v1.FriendlistUpdate
	14, // 1: friends.v1.FriendsUpdate.ignorelist:type_name -> friends.v1.IgnorelistUpdate
	15, // 2: friends.v1.FriendsUpdate.private_message:type_name -> friends.v1.PrivateMessageDelivery
	13, // 3: friends.v1.FriendlistUpdate.entries:type_name -> friends.v1.FriendEntry
	0,  // 4: friends.v1.FriendsService.WorldConnect:input_type -> friends.v1.WorldConnectRequest
	1,  // 5: friends.v1.FriendsService.PlayerLogin:input_type -> friends.v1.PlayerLoginRequest
	3,  // 6: friends.v1.FriendsService.PlayerLogout:input_type -> friends.v1.PlayerLogoutRequest
	4,  // 7: friends.v1.FriendsService.ChatSetMode:input_type -> friends.v1.ChatSetModeRequest
	5,  // 8: friends.v1.FriendsService.FriendlistAdd:input_type -> friends.v1.FriendlistAddRequest
	6,  // 9: friends.v1.FriendsService.FriendlistDel:input_type -> friends.v1.FriendlistDelRequest
	7,  // 10: friends.v1.FriendsService.IgnorelistAdd:input_type -> friends.v1.IgnorelistAddRequest
	8,  // 11: friends.v1.FriendsService.IgnorelistDel:input_type -> friends.v1.IgnorelistDelRequest
	9,  // 12: friends.v1.FriendsService.PrivateMessage:input_type -> friends.v1.PrivateMessageRequest
	10, // 13: friends.v1.FriendsService.SubscribeUpdates:input_type -> friends.v1.SubscribeUpdatesRequest
	16, // 14: friends.v1.FriendsService.WorldConnect:output_type -> google.protobuf.Empty
	2,  // 15: friends.v1.FriendsService.PlayerLogin:output_type -> friends.v1.PlayerLoginResponse
	16, // 16: friends.v1.FriendsService.PlayerLogout:output_type -> google.protobuf.Empty
	16, // 17: friends.v1.FriendsService.ChatSetMode:output_type -> google.protobuf.Empty
	16, // 18: friends.v1.FriendsService.FriendlistAdd:output_type -> google.protobuf.Empty
	16, // 19: friends.v1.FriendsService.FriendlistDel:output_type -> google.protobuf.Empty
	16, // 20: friends.v1.FriendsService.IgnorelistAdd:output_type -> google.protobuf.Empty
	16, // 21: friends.v1.FriendsService.IgnorelistDel:output_type -> google.protobuf.Empty
	16, // 22: friends.v1.FriendsService.PrivateMessage:output_type -> google.protobuf.Empty
	11, // 23: friends.v1.FriendsService.SubscribeUpdates:output_type -> friends.v1.FriendsUpdate
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_friends_friends_proto_init() }
func file_friends_friends_proto_init() {
	if File_friends_friends_proto != nil {
		return
	}
	file_friends_friends_proto_msgTypes[11].OneofWrappers = []any{
		(*FriendsUpdate_Friendlist)(nil),
		(*FriendsUpdate_Ignorelist)(nil),
		(*FriendsUpdate_PrivateMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friends_friends_proto_rawDesc), len(file_friends_friends_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friends_friends_proto_goTypes,
		DependencyIndexes: file_friends_friends_proto_depIdxs,
		MessageInfos:      file_friends_friends_proto_msgTypes,
	}.Build()
	File_friends_friends_proto = out.File
	file_friends_friends_proto_goTypes = nil
	file_friends_friends_proto_depIdxs = nil
}
