// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: account/account.proto

package accountpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyResult int32

const (
	VerifyResult_VERIFY_RESULT_UNSPECIFIED         VerifyResult = 0
	VerifyResult_VERIFY_RESULT_OK                  VerifyResult = 1
	VerifyResult_VERIFY_RESULT_INVALID_CREDENTIALS VerifyResult = 2
	VerifyResult_VERIFY_RESULT_ACCOUNT_DISABLED    VerifyResult = 3
	VerifyResult_VERIFY_RESULT_EMAIL_UNVERIFIED    VerifyResult = 4
)

// Enum value maps for VerifyResult.
var (
	VerifyResult_name = map[int32]string{
		0: "VERIFY_RESULT_UNSPECIFIED",
		1: "VERIFY_RESULT_OK",
		2: "VERIFY_RESULT_INVALID_CREDENTIALS",
		3: "VERIFY_RESULT_ACCOUNT_DISABLED",
		4: "VERIFY_RESULT_EMAIL_UNVERIFIED",
	}
	VerifyResult_value = map[string]int32{
		"VERIFY_RESULT_UNSPECIFIED":         0,
		"VERIFY_RESULT_OK":                  1,
		"VERIFY_RESULT_INVALID_CREDENTIALS": 2,
		"VERIFY_RESULT_ACCOUNT_DISABLED":    3,
		"VERIFY_RESULT_EMAIL_UNVERIFIED":    4,
	}
)

func (x VerifyResult) Enum() *VerifyResult {
	p := new(VerifyResult)
	*p = x
	return p
}

func (x VerifyResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyResult) Descriptor() protoreflect.EnumDescriptor {
	return file_account_account_proto_enumTypes[0].Descriptor()
}

func (VerifyResult) Type() protoreflect.EnumType {
	return &file_account_account_proto_enumTypes[0]
}

func (x VerifyResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifyResult.Descriptor instead.
func (VerifyResult) EnumDescriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{0}
}

type VerifyGameLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterName string                 `protobuf:"bytes,1,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"` // safe-name normalized by the login module
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                // verbatim from the client (post-RSA decode)
	RemoteAddress string                 `protobuf:"bytes,3,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"` // audit context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyGameLoginRequest) Reset() {
	*x = VerifyGameLoginRequest{}
	mi := &file_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyGameLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyGameLoginRequest) ProtoMessage() {}

func (x *VerifyGameLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyGameLoginRequest.ProtoReflect.Descriptor instead.
func (*VerifyGameLoginRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyGameLoginRequest) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *VerifyGameLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *VerifyGameLoginRequest) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

type VerifyGameLoginResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Result          VerifyResult           `protobuf:"varint,1,opt,name=result,proto3,enum=account.v1.VerifyResult" json:"result,omitempty"`
	GameAccountId   int64                  `protobuf:"varint,2,opt,name=game_account_id,json=gameAccountId,proto3" json:"game_account_id,omitempty"` // goscape `account` row for this character
	PortalAccountId int64                  `protobuf:"varint,3,opt,name=portal_account_id,json=portalAccountId,proto3" json:"portal_account_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyGameLoginResponse) Reset() {
	*x = VerifyGameLoginResponse{}
	mi := &file_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyGameLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyGameLoginResponse) ProtoMessage() {}

func (x *VerifyGameLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyGameLoginResponse.ProtoReflect.Descriptor instead.
func (*VerifyGameLoginResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyGameLoginResponse) GetResult() VerifyResult {
	if x != nil {
		return x.Result
	}
	return VerifyResult_VERIFY_RESULT_UNSPECIFIED
}

func (x *VerifyGameLoginResponse) GetGameAccountId() int64 {
	if x != nil {
		return x.GameAccountId
	}
	return 0
}

func (x *VerifyGameLoginResponse) GetPortalAccountId() int64 {
	if x != nil {
		return x.PortalAccountId
	}
	return 0
}

type AccountSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified  bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // active | disabled
	CharacterCount int32                  `protobuf:"varint,5,opt,name=character_count,json=characterCount,proto3" json:"character_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountSummary) Reset() {
	*x = AccountSummary{}
	mi := &file_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSummary) ProtoMessage() {}

func (x *AccountSummary) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSummary.ProtoReflect.Descriptor instead.
func (*AccountSummary) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountSummary) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *AccountSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountSummary) GetCharacterCount() int32 {
	if x != nil {
		return x.CharacterCount
	}
	return 0
}

// query matches: email substring (case-insensitive), exact character
// name, or exact provider user id.
type SearchAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAccountsRequest) Reset() {
	*x = SearchAccountsRequest{}
	mi := &file_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAccountsRequest) ProtoMessage() {}

func (x *SearchAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAccountsRequest.ProtoReflect.Descriptor instead.
func (*SearchAccountsRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *SearchAccountsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountSummary      `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAccountsResponse) Reset() {
	*x = SearchAccountsResponse{}
	mi := &file_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAccountsResponse) ProtoMessage() {}

func (x *SearchAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAccountsResponse.ProtoReflect.Descriptor instead.
func (*SearchAccountsResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *SearchAccountsResponse) GetAccounts() []*AccountSummary {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type IdentityInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Provider         string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUserId   string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	ProviderUsername string                 `protobuf:"bytes,3,opt,name=provider_username,json=providerUsername,proto3" json:"provider_username,omitempty"`
	Revoked          bool                   `protobuf:"varint,4,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IdentityInfo) Reset() {
	*x = IdentityInfo{}
	mi := &file_account_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityInfo) ProtoMessage() {}

func (x *IdentityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityInfo.ProtoReflect.Descriptor instead.
func (*IdentityInfo) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{5}
}

func (x *IdentityInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *IdentityInfo) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *IdentityInfo) GetProviderUsername() string {
	if x != nil {
		return x.ProviderUsername
	}
	return ""
}

func (x *IdentityInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type CharacterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	GameAccountId int64                  `protobuf:"varint,3,opt,name=game_account_id,json=gameAccountId,proto3" json:"game_account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_account_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{6}
}

func (x *CharacterInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CharacterInfo) GetGameAccountId() int64 {
	if x != nil {
		return x.GameAccountId
	}
	return 0
}

// Exactly one of id / email must be set.
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_account_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountSummary        `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Identities    []*IdentityInfo        `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	Characters    []*CharacterInfo       `protobuf:"bytes,3,rep,name=characters,proto3" json:"characters,omitempty"`
	Groups        []string               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountResponse) GetAccount() *AccountSummary {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountResponse) GetIdentities() []*IdentityInfo {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *GetAccountResponse) GetCharacters() []*CharacterInfo {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *GetAccountResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type SetGroupMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"` // manually_approved | admin
	Member        bool                   `protobuf:"varint,3,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupMembershipRequest) Reset() {
	*x = SetGroupMembershipRequest{}
	mi := &file_account_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupMembershipRequest) ProtoMessage() {}

func (x *SetGroupMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupMembershipRequest.ProtoReflect.Descriptor instead.
func (*SetGroupMembershipRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{9}
}

func (x *SetGroupMembershipRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SetGroupMembershipRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SetGroupMembershipRequest) GetMember() bool {
	if x != nil {
		return x.Member
	}
	return false
}

type SetAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active | disabled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountStatusRequest) Reset() {
	*x = SetAccountStatusRequest{}
	mi := &file_account_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountStatusRequest) ProtoMessage() {}

func (x *SetAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*SetAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{10}
}

func (x *SetAccountStatusRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SetAccountStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UnlinkIdentity soft-revokes ("burns") — the identity can never vouch
// for another account. ReleaseIdentity hard-deletes, freeing it.
type UnlinkIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkIdentityRequest) Reset() {
	*x = UnlinkIdentityRequest{}
	mi := &file_account_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkIdentityRequest) ProtoMessage() {}

func (x *UnlinkIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkIdentityRequest.ProtoReflect.Descriptor instead.
func (*UnlinkIdentityRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{11}
}

func (x *UnlinkIdentityRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UnlinkIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ReleaseIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseIdentityRequest) Reset() {
	*x = ReleaseIdentityRequest{}
	mi := &file_account_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIdentityRequest) ProtoMessage() {}

func (x *ReleaseIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIdentityRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIdentityRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReleaseIdentityRequest) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

// AdminResetPassword mints a single-use reset token and returns the
// portal URL an admin can hand to the player out-of-band.
type AdminResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResetPasswordRequest) Reset() {
	*x = AdminResetPasswordRequest{}
	mi := &file_account_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResetPasswordRequest) ProtoMessage() {}

func (x *AdminResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*AdminResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{13}
}

func (x *AdminResetPasswordRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type AdminResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetUrl      string                 `protobuf:"bytes,1,opt,name=reset_url,json=resetUrl,proto3" json:"reset_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResetPasswordResponse) Reset() {
	*x = AdminResetPasswordResponse{}
	mi := &file_account_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResetPasswordResponse) ProtoMessage() {}

func (x *AdminResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*AdminResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{14}
}

func (x *AdminResetPasswordResponse) GetResetUrl() string {
	if x != nil {
		return x.ResetUrl
	}
	return ""
}

type BootstrapAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAdminRequest) Reset() {
	*x = BootstrapAdminRequest{}
	mi := &file_account_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAdminRequest) ProtoMessage() {}

func (x *BootstrapAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAdminRequest.ProtoReflect.Descriptor instead.
func (*BootstrapAdminRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{15}
}

func (x *BootstrapAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_account_account_proto protoreflect.FileDescriptor

const file_account_account_proto_rawDesc = "" +
	"\n" +
	"\x15account/account.proto\x12\n" +
	"account.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x01\n" +
	"\x16VerifyGameLoginRequest\x12%\n" +
	"\x0echaracter_name\x18\x01 \x01(\tR\rcharacterName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\x0eremote_address\x18\x03 \x01(\tR\rremoteAddress\"\x9f\x01\n" +
	"\x17VerifyGameLoginResponse\x120\n" +
	"\x06result\x18\x01 \x01(\x0e2\x18.account.v1.VerifyResultR\x06result\x12&\n" +
	"\x0fgame_account_id\x18\x02 \x01(\x03R\rgameAccountId\x12*\n" +
	"\x11portal_account_id\x18\x03 \x01(\x03R\x0fportalAccountId\"\x9e\x01\n" +
	"\x0eAccountSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fcharacter_count\x18\x05 \x01(\x05R\x0echaracterCount\"-\n" +
	"\x15SearchAccountsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"P\n" +
	"\x16SearchAccountsResponse\x126\n" +
	"\baccounts\x18\x01 \x03(\v2\x1a.account.v1.AccountSummaryR\baccounts\"\x9b\x01\n" +
	"\fIdentityInfo\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId\x12+\n" +
	"\x11provider_username\x18\x03 \x01(\tR\x10providerUsername\x12\x18\n" +
	"\arevoked\x18\x04 \x01(\bR\arevoked\"c\n" +
	"\rCharacterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12&\n" +
	"\x0fgame_account_id\x18\x03 \x01(\x03R\rgameAccountId\"9\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xd7\x01\n" +
	"\x12GetAccountResponse\x124\n" +
	"\aaccount\x18\x01 \x01(\v2\x1a.account.v1.AccountSummaryR\aaccount\x128\n" +
	"\n" +
	"identities\x18\x02 \x03(\v2\x18.account.v1.IdentityInfoR\n" +
	"identities\x129\n" +
	"\n" +
	"characters\x18\x03 \x03(\v2\x19.account.v1.CharacterInfoR\n" +
	"characters\x12\x16\n" +
	"\x06groups\x18\x04 \x03(\tR\x06groups\"h\n" +
	"\x19SetGroupMembershipRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x16\n" +
	"\x06member\x18\x03 \x01(\bR\x06member\"P\n" +
	"\x17SetAccountStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"R\n" +
	"\x15UnlinkIdentityRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"^\n" +
	"\x16ReleaseIdentityRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId\":\n" +
	"\x19AdminResetPasswordRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"9\n" +
	"\x1aAdminResetPasswordResponse\x12\x1b\n" +
	"\treset_url\x18\x01 \x01(\tR\bresetUrl\"-\n" +
	"\x15BootstrapAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email*\xb2\x01\n" +
	"\fVerifyResult\x12\x1d\n" +
	"\x19VERIFY_RESULT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VERIFY_RESULT_OK\x10\x01\x12%\n" +
	"!VERIFY_RESULT_INVALID_CREDENTIALS\x10\x02\x12\"\n" +
	"\x1eVERIFY_RESULT_ACCOUNT_DISABLED\x10\x03\x12\"\n" +
	"\x1eVERIFY_RESULT_EMAIL_UNVERIFIED\x10\x042\x86\x06\n" +
	"\x0eAccountService\x12Z\n" +
	"\x0fVerifyGameLogin\x12\".account.v1.VerifyGameLoginRequest\x1a#.account.v1.VerifyGameLoginResponse\x12W\n" +
	"\x0eSearchAccounts\x12!.account.v1.SearchAccountsRequest\x1a\".account.v1.SearchAccountsResponse\x12K\n" +
	"\n" +
	"GetAccount\x12\x1d.account.v1.GetAccountRequest\x1a\x1e.account.v1.GetAccountResponse\x12S\n" +
	"\x12SetGroupMembership\x12%.account.v1.SetGroupMembershipRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x10SetAccountStatus\x12#.account.v1.SetAccountStatusRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x0eUnlinkIdentity\x12!.account.v1.UnlinkIdentityRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x0fReleaseIdentity\x12\".account.v1.ReleaseIdentityRequest\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\x12AdminResetPassword\x12%.account.v1.AdminResetPasswordRequest\x1a&.account.v1.AdminResetPasswordResponse\x12K\n" +
	"\x0eBootstrapAdmin\x12!.account.v1.BootstrapAdminRequest\x1a\x16.google.protobuf.EmptyB'Z%github.com/zsrv/goscape/pkg/accountpbb\x06proto3"

var (
	file_account_account_proto_rawDescOnce sync.Once
	file_account_account_proto_rawDescData []byte
)

func file_account_account_proto_rawDescGZIP() []byte {
	file_account_account_proto_rawDescOnce.Do(func() {
		file_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)))
	})
	return file_account_account_proto_rawDescData
}

var file_account_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_account_account_proto_goTypes = []any{
	(VerifyResult)(0),                  // 0: account.v1.VerifyResult
	(*VerifyGameLoginRequest)(nil),     // 1: account.v1.VerifyGameLoginRequest
	(*VerifyGameLoginResponse)(nil),    // 2: account.v1.VerifyGameLoginResponse
	(*AccountSummary)(nil),             // 3: account.v1.AccountSummary
	(*SearchAccountsRequest)(nil),      // 4: account.v1.SearchAccountsRequest
	(*SearchAccountsResponse)(nil),     // 5: account.v1.SearchAccountsResponse
	(*IdentityInfo)(nil),               // 6: account.v1.IdentityInfo
	(*CharacterInfo)(nil),              // 7: account.v1.CharacterInfo
	(*GetAccountRequest)(nil),          // 8: account.v1.GetAccountRequest
	(*GetAccountResponse)(nil),         // 9: account.v1.GetAccountResponse
	(*SetGroupMembershipRequest)(nil),  // 10: account.v1.SetGroupMembershipRequest
	(*SetAccountStatusRequest)(nil),    // 11: account.v1.SetAccountStatusRequest
	(*UnlinkIdentityRequest)(nil),      // 12: account.v1.UnlinkIdentityRequest
	(*ReleaseIdentityRequest)(nil),     // 13: account.v1.ReleaseIdentityRequest
	(*AdminResetPasswordRequest)(nil),  // 14: account.v1.AdminResetPasswordRequest
	(*AdminResetPasswordResponse)(nil), // 15: account.v1.AdminResetPasswordResponse
	(*BootstrapAdminRequest)(nil),      // 16: account.v1.BootstrapAdminRequest
	(*emptypb.Empty)(nil),              // 17: google.protobuf.Empty
}
var file_account_account_proto_depIdxs = []int32{
	0,  // 0: account.v1.VerifyGameLoginResponse.result:type_name -> account.v1.VerifyResult
	3,  // 1: account.v1.SearchAccountsResponse.accounts:type_name -> account.v1.AccountSummary
	3,  // 2: account.v1.GetAccountResponse.account:type_name -> account.v1.AccountSummary
	6,  // 3: account.v1.GetAccountResponse.identities:type_name -> account.v1.IdentityInfo
	7,  // 4: account.v1.GetAccountResponse.characters:type_name -> account.v1.CharacterInfo
	1,  // 5: account.v1.AccountService.VerifyGameLogin:input_type -> account.v1.VerifyGameLoginRequest
	4,  // 6: account.v1.AccountService.SearchAccounts:input_type -> account.v1.SearchAccountsRequest
	8,  // 7: account.v1.AccountService.GetAccount:input_type -> account.v1.GetAccountRequest
	10, // 8: account.v1.AccountService.SetGroupMembership:input_type -> account.v1.SetGroupMembershipRequest
	11, // 9: account.v1.AccountService.SetAccountStatus:input_type -> account.v1.SetAccountStatusRequest
	12, // 10: account.v1.AccountService.UnlinkIdentity:input_type -> account.v1.UnlinkIdentityRequest
	13, // 11: account.v1.AccountService.ReleaseIdentity:input_type -> account.v1.ReleaseIdentityRequest
	14, // 12: account.v1.AccountService.AdminResetPassword:input_type -> account.v1.AdminResetPasswordRequest
	16, // 13: account.v1.AccountService.BootstrapAdmin:input_type -> account.v1.BootstrapAdminRequest
	2,  // 14: account.v1.AccountService.VerifyGameLogin:output_type -> account.v1.VerifyGameLoginResponse
	5,  // 15: account.v1.AccountService.SearchAccounts:output_type -> account.v1.SearchAccountsResponse
	9,  // 16: account.v1.AccountService.GetAccount:output_type -> account.v1.GetAccountResponse
	17, // 17: account.v1.AccountService.SetGroupMembership:output_type -> google.protobuf.Empty
	17, // 18: account.v1.AccountService.SetAccountStatus:output_type -> google.protobuf.Empty
	17, // 19: account.v1.AccountService.UnlinkIdentity:output_type -> google.protobuf.Empty
	17, // 20: account.v1.AccountService.ReleaseIdentity:output_type -> google.protobuf.Empty
	15, // 21: account.v1.AccountService.AdminResetPassword:output_type -> account.v1.AdminResetPasswordResponse
	17, // 22: account.v1.AccountService.BootstrapAdmin:output_type -> google.protobuf.Empty
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_account_account_proto_init() }
func file_account_account_proto_init() {
	if File_account_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_account_proto_goTypes,
		DependencyIndexes: file_account_account_proto_depIdxs,
		EnumInfos:         file_account_account_proto_enumTypes,
		MessageInfos:      file_account_account_proto_msgTypes,
	}.Build()
	File_account_account_proto = out.File
	file_account_account_proto_goTypes = nil
	file_account_account_proto_depIdxs = nil
}
