// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: account/account.proto

package accountpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_VerifyGameLogin_FullMethodName    = "/account.v1.AccountService/VerifyGameLogin"
	AccountService_SearchAccounts_FullMethodName     = "/account.v1.AccountService/SearchAccounts"
	AccountService_GetAccount_FullMethodName         = "/account.v1.AccountService/GetAccount"
	AccountService_SetGroupMembership_FullMethodName = "/account.v1.AccountService/SetGroupMembership"
	AccountService_SetAccountStatus_FullMethodName   = "/account.v1.AccountService/SetAccountStatus"
	AccountService_UnlinkIdentity_FullMethodName     = "/account.v1.AccountService/UnlinkIdentity"
	AccountService_ReleaseIdentity_FullMethodName    = "/account.v1.AccountService/ReleaseIdentity"
	AccountService_AdminResetPassword_FullMethodName = "/account.v1.AccountService/AdminResetPassword"
	AccountService_BootstrapAdmin_FullMethodName     = "/account.v1.AccountService/BootstrapAdmin"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountService is the account-management module's wire contract.
// VerifyGameLogin is called by the login module (unauthenticated,
// internal network). Every other RPC is the admin surface used by
// `goscape-cli account` and requires
//
//	authorization: Bearer <account.admin_token>
//
// metadata; with no token configured the admin surface is disabled.
// Spec: docs/superpowers/specs/2026-07-19-account-management-design.md
type AccountServiceClient interface {
	VerifyGameLogin(ctx context.Context, in *VerifyGameLoginRequest, opts ...grpc.CallOption) (*VerifyGameLoginResponse, error)
	SearchAccounts(ctx context.Context, in *SearchAccountsRequest, opts ...grpc.CallOption) (*SearchAccountsResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	SetGroupMembership(ctx context.Context, in *SetGroupMembershipRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetAccountStatus(ctx context.Context, in *SetAccountStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnlinkIdentity(ctx context.Context, in *UnlinkIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReleaseIdentity(ctx context.Context, in *ReleaseIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AdminResetPassword(ctx context.Context, in *AdminResetPasswordRequest, opts ...grpc.CallOption) (*AdminResetPasswordResponse, error)
	BootstrapAdmin(ctx context.Context, in *BootstrapAdminRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) VerifyGameLogin(ctx context.Context, in *VerifyGameLoginRequest, opts ...grpc.CallOption) (*VerifyGameLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyGameLoginResponse)
	err := c.cc.Invoke(ctx, AccountService_VerifyGameLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SearchAccounts(ctx context.Context, in *SearchAccountsRequest, opts ...grpc.CallOption) (*SearchAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAccountsResponse)
	err := c.cc.Invoke(ctx, AccountService_SearchAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SetGroupMembership(ctx context.Context, in *SetGroupMembershipRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_SetGroupMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SetAccountStatus(ctx context.Context, in *SetAccountStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_SetAccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UnlinkIdentity(ctx context.Context, in *UnlinkIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_UnlinkIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ReleaseIdentity(ctx context.Context, in *ReleaseIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_ReleaseIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AdminResetPassword(ctx context.Context, in *AdminResetPasswordRequest, opts ...grpc.CallOption) (*AdminResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResetPasswordResponse)
	err := c.cc.Invoke(ctx, AccountService_AdminResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) BootstrapAdmin(ctx context.Context, in *BootstrapAdminRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_BootstrapAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// AccountService is the account-management module's wire contract.
// VerifyGameLogin is called by the login module (unauthenticated,
// internal network). Every other RPC is the admin surface used by
// `goscape-cli account` and requires
//
//	authorization: Bearer <account.admin_token>
//
// metadata; with no token configured the admin surface is disabled.
// Spec: docs/superpowers/specs/2026-07-19-account-management-design.md
type AccountServiceServer interface {
	VerifyGameLogin(context.Context, *VerifyGameLoginRequest) (*VerifyGameLoginResponse, error)
	SearchAccounts(context.Context, *SearchAccountsRequest) (*SearchAccountsResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	SetGroupMembership(context.Context, *SetGroupMembershipRequest) (*emptypb.Empty, error)
	SetAccountStatus(context.Context, *SetAccountStatusRequest) (*emptypb.Empty, error)
	UnlinkIdentity(context.Context, *UnlinkIdentityRequest) (*emptypb.Empty, error)
	ReleaseIdentity(context.Context, *ReleaseIdentityRequest) (*emptypb.Empty, error)
	AdminResetPassword(context.Context, *AdminResetPasswordRequest) (*AdminResetPasswordResponse, error)
	BootstrapAdmin(context.Context, *BootstrapAdminRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) VerifyGameLogin(context.Context, *VerifyGameLoginRequest) (*VerifyGameLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyGameLogin not implemented")
}
func (UnimplementedAccountServiceServer) SearchAccounts(context.Context, *SearchAccountsRequest) (*SearchAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAccounts not implemented")
}
func (UnimplementedAccountServiceServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedAccountServiceServer) SetGroupMembership(context.Context, *SetGroupMembershipRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGroupMembership not implemented")
}
func (UnimplementedAccountServiceServer) SetAccountStatus(context.Context, *SetAccountStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAccountStatus not implemented")
}
func (UnimplementedAccountServiceServer) UnlinkIdentity(context.Context, *UnlinkIdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkIdentity not implemented")
}
func (UnimplementedAccountServiceServer) ReleaseIdentity(context.Context, *ReleaseIdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseIdentity not implemented")
}
func (UnimplementedAccountServiceServer) AdminResetPassword(context.Context, *AdminResetPasswordRequest) (*AdminResetPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminResetPassword not implemented")
}
func (UnimplementedAccountServiceServer) BootstrapAdmin(context.Context, *BootstrapAdminRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BootstrapAdmin not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_VerifyGameLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyGameLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).VerifyGameLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_VerifyGameLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).VerifyGameLogin(ctx, req.(*VerifyGameLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SearchAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SearchAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SearchAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SearchAccounts(ctx, req.(*SearchAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SetGroupMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SetGroupMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SetGroupMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SetGroupMembership(ctx, req.(*SetGroupMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SetAccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SetAccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SetAccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SetAccountStatus(ctx, req.(*SetAccountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UnlinkIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UnlinkIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UnlinkIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UnlinkIdentity(ctx, req.(*UnlinkIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ReleaseIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ReleaseIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ReleaseIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ReleaseIdentity(ctx, req.(*ReleaseIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AdminResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AdminResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AdminResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AdminResetPassword(ctx, req.(*AdminResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_BootstrapAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).BootstrapAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_BootstrapAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).BootstrapAdmin(ctx, req.(*BootstrapAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyGameLogin",
			Handler:    _AccountService_VerifyGameLogin_Handler,
		},
		{
			MethodName: "SearchAccounts",
			Handler:    _AccountService_SearchAccounts_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
		{
			MethodName: "SetGroupMembership",
			Handler:    _AccountService_SetGroupMembership_Handler,
		},
		{
			MethodName: "SetAccountStatus",
			Handler:    _AccountService_SetAccountStatus_Handler,
		},
		{
			MethodName: "UnlinkIdentity",
			Handler:    _AccountService_UnlinkIdentity_Handler,
		},
		{
			MethodName: "ReleaseIdentity",
			Handler:    _AccountService_ReleaseIdentity_Handler,
		},
		{
			MethodName: "AdminResetPassword",
			Handler:    _AccountService_AdminResetPassword_Handler,
		},
		{
			MethodName: "BootstrapAdmin",
			Handler:    _AccountService_BootstrapAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/account.proto",
}
