// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: login/login.proto

package loginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResult int32

const (
	LoginResult_LOGIN_RESULT_UNSPECIFIED         LoginResult = 0
	LoginResult_LOGIN_RESULT_OK                  LoginResult = 1
	LoginResult_LOGIN_RESULT_NEW_PLAYER          LoginResult = 2
	LoginResult_LOGIN_RESULT_RECONNECT_OK        LoginResult = 3
	LoginResult_LOGIN_RESULT_INVALID_CREDENTIALS LoginResult = 4
	LoginResult_LOGIN_RESULT_ALREADY_LOGGED_IN   LoginResult = 5
	LoginResult_LOGIN_RESULT_ACCOUNT_DISABLED    LoginResult = 6
	LoginResult_LOGIN_RESULT_NOT_A_MEMBER        LoginResult = 7
	LoginResult_LOGIN_RESULT_LOGIN_IN_PROGRESS   LoginResult = 8
	LoginResult_LOGIN_RESULT_TRY_AGAIN           LoginResult = 9
)

// Enum value maps for LoginResult.
var (
	LoginResult_name = map[int32]string{
		0: "LOGIN_RESULT_UNSPECIFIED",
		1: "LOGIN_RESULT_OK",
		2: "LOGIN_RESULT_NEW_PLAYER",
		3: "LOGIN_RESULT_RECONNECT_OK",
		4: "LOGIN_RESULT_INVALID_CREDENTIALS",
		5: "LOGIN_RESULT_ALREADY_LOGGED_IN",
		6: "LOGIN_RESULT_ACCOUNT_DISABLED",
		7: "LOGIN_RESULT_NOT_A_MEMBER",
		8: "LOGIN_RESULT_LOGIN_IN_PROGRESS",
		9: "LOGIN_RESULT_TRY_AGAIN",
	}
	LoginResult_value = map[string]int32{
		"LOGIN_RESULT_UNSPECIFIED":         0,
		"LOGIN_RESULT_OK":                  1,
		"LOGIN_RESULT_NEW_PLAYER":          2,
		"LOGIN_RESULT_RECONNECT_OK":        3,
		"LOGIN_RESULT_INVALID_CREDENTIALS": 4,
		"LOGIN_RESULT_ALREADY_LOGGED_IN":   5,
		"LOGIN_RESULT_ACCOUNT_DISABLED":    6,
		"LOGIN_RESULT_NOT_A_MEMBER":        7,
		"LOGIN_RESULT_LOGIN_IN_PROGRESS":   8,
		"LOGIN_RESULT_TRY_AGAIN":           9,
	}
)

func (x LoginResult) Enum() *LoginResult {
	p := new(LoginResult)
	*p = x
	return p
}

func (x LoginResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResult) Descriptor() protoreflect.EnumDescriptor {
	return file_login_login_proto_enumTypes[0].Descriptor()
}

func (LoginResult) Type() protoreflect.EnumType {
	return &file_login_login_proto_enumTypes[0]
}

func (x LoginResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResult.Descriptor instead.
func (LoginResult) EnumDescriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{0}
}

type WorldStartupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldStartupRequest) Reset() {
	*x = WorldStartupRequest{}
	mi := &file_login_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldStartupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldStartupRequest) ProtoMessage() {}

func (x *WorldStartupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldStartupRequest.ProtoReflect.Descriptor instead.
func (*WorldStartupRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{0}
}

func (x *WorldStartupRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *WorldStartupRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type PlayerLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	NodeMembers   bool                   `protobuf:"varint,3,opt,name=node_members,json=nodeMembers,proto3" json:"node_members,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Uid           int32                  `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Socket        string                 `protobuf:"bytes,7,opt,name=socket,proto3" json:"socket,omitempty"`
	RemoteAddress string                 `protobuf:"bytes,8,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	Reconnecting  bool                   `protobuf:"varint,9,opt,name=reconnecting,proto3" json:"reconnecting,omitempty"`
	HasSave       bool                   `protobuf:"varint,10,opt,name=has_save,json=hasSave,proto3" json:"has_save,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginRequest) Reset() {
	*x = PlayerLoginRequest{}
	mi := &file_login_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginRequest) ProtoMessage() {}

func (x *PlayerLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginRequest.ProtoReflect.Descriptor instead.
func (*PlayerLoginRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerLoginRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PlayerLoginRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *PlayerLoginRequest) GetNodeMembers() bool {
	if x != nil {
		return x.NodeMembers
	}
	return false
}

func (x *PlayerLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PlayerLoginRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerLoginRequest) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *PlayerLoginRequest) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *PlayerLoginRequest) GetReconnecting() bool {
	if x != nil {
		return x.Reconnecting
	}
	return false
}

func (x *PlayerLoginRequest) GetHasSave() bool {
	if x != nil {
		return x.HasSave
	}
	return false
}

type PlayerLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        LoginResult            `protobuf:"varint,1,opt,name=result,proto3,enum=login.v1.LoginResult" json:"result,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	StaffModLevel int32                  `protobuf:"varint,3,opt,name=staff_mod_level,json=staffModLevel,proto3" json:"staff_mod_level,omitempty"`
	Save          []byte                 `protobuf:"bytes,4,opt,name=save,proto3,oneof" json:"save,omitempty"`
	MutedUntil    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=muted_until,json=mutedUntil,proto3,oneof" json:"muted_until,omitempty"`
	Members       bool                   `protobuf:"varint,6,opt,name=members,proto3" json:"members,omitempty"`
	MessageCount  int32                  `protobuf:"varint,7,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginResponse) Reset() {
	*x = PlayerLoginResponse{}
	mi := &file_login_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginResponse) ProtoMessage() {}

func (x *PlayerLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginResponse.ProtoReflect.Descriptor instead.
func (*PlayerLoginResponse) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLoginResponse) GetResult() LoginResult {
	if x != nil {
		return x.Result
	}
	return LoginResult_LOGIN_RESULT_UNSPECIFIED
}

func (x *PlayerLoginResponse) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerLoginResponse) GetStaffModLevel() int32 {
	if x != nil {
		return x.StaffModLevel
	}
	return 0
}

func (x *PlayerLoginResponse) GetSave() []byte {
	if x != nil {
		return x.Save
	}
	return nil
}

func (x *PlayerLoginResponse) GetMutedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.MutedUntil
	}
	return nil
}

func (x *PlayerLoginResponse) GetMembers() bool {
	if x != nil {
		return x.Members
	}
	return false
}

func (x *PlayerLoginResponse) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type PlayerLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Save          []byte                 `protobuf:"bytes,4,opt,name=save,proto3" json:"save,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLogoutRequest) Reset() {
	*x = PlayerLogoutRequest{}
	mi := &file_login_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogoutRequest) ProtoMessage() {}

func (x *PlayerLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogoutRequest.ProtoReflect.Descriptor instead.
func (*PlayerLogoutRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLogoutRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PlayerLogoutRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *PlayerLogoutRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerLogoutRequest) GetSave() []byte {
	if x != nil {
		return x.Save
	}
	return nil
}

type PlayerLogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLogoutResponse) Reset() {
	*x = PlayerLogoutResponse{}
	mi := &file_login_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogoutResponse) ProtoMessage() {}

func (x *PlayerLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogoutResponse.ProtoReflect.Descriptor instead.
func (*PlayerLogoutResponse) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerLogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PlayerAutosaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Save          []byte                 `protobuf:"bytes,3,opt,name=save,proto3" json:"save,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAutosaveRequest) Reset() {
	*x = PlayerAutosaveRequest{}
	mi := &file_login_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAutosaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAutosaveRequest) ProtoMessage() {}

func (x *PlayerAutosaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAutosaveRequest.ProtoReflect.Descriptor instead.
func (*PlayerAutosaveRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerAutosaveRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *PlayerAutosaveRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerAutosaveRequest) GetSave() []byte {
	if x != nil {
		return x.Save
	}
	return nil
}

type PlayerForceLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerForceLogoutRequest) Reset() {
	*x = PlayerForceLogoutRequest{}
	mi := &file_login_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerForceLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerForceLogoutRequest) ProtoMessage() {}

func (x *PlayerForceLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerForceLogoutRequest.ProtoReflect.Descriptor instead.
func (*PlayerForceLogoutRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerForceLogoutRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PlayerForceLogoutRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *PlayerForceLogoutRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PlayerBanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         string                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBanRequest) Reset() {
	*x = PlayerBanRequest{}
	mi := &file_login_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBanRequest) ProtoMessage() {}

func (x *PlayerBanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBanRequest.ProtoReflect.Descriptor instead.
func (*PlayerBanRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerBanRequest) GetStaff() string {
	if x != nil {
		return x.Staff
	}
	return ""
}

func (x *PlayerBanRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerBanRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type PlayerBanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBanResponse) Reset() {
	*x = PlayerBanResponse{}
	mi := &file_login_login_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBanResponse) ProtoMessage() {}

func (x *PlayerBanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBanResponse.ProtoReflect.Descriptor instead.
func (*PlayerBanResponse) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{8}
}

type PlayerMuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         string                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMuteRequest) Reset() {
	*x = PlayerMuteRequest{}
	mi := &file_login_login_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMuteRequest) ProtoMessage() {}

func (x *PlayerMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMuteRequest.ProtoReflect.Descriptor instead.
func (*PlayerMuteRequest) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerMuteRequest) GetStaff() string {
	if x != nil {
		return x.Staff
	}
	return ""
}

func (x *PlayerMuteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerMuteRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type PlayerMuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMuteResponse) Reset() {
	*x = PlayerMuteResponse{}
	mi := &file_login_login_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMuteResponse) ProtoMessage() {}

func (x *PlayerMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_login_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMuteResponse.ProtoReflect.Descriptor instead.
func (*PlayerMuteResponse) Descriptor() ([]byte, []int) {
	return file_login_login_proto_rawDescGZIP(), []int{10}
}

var File_login_login_proto protoreflect.FileDescriptor

const file_login_login_proto_rawDesc = "" +
	"\n" +
	"\x11login/login.proto\x12\blogin.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x13WorldStartupRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\"\xb2\x02\n" +
	"\x12PlayerLoginRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12!\n" +
	"\fnode_members\x18\x03 \x01(\bR\vnodeMembers\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\x05R\x03uid\x12\x16\n" +
	"\x06socket\x18\a \x01(\tR\x06socket\x12%\n" +
	"\x0eremote_address\x18\b \x01(\tR\rremoteAddress\x12\"\n" +
	"\freconnecting\x18\t \x01(\bR\freconnecting\x12\x19\n" +
	"\bhas_save\x18\n" +
	" \x01(\bR\ahasSave\"\xbe\x02\n" +
	"\x13PlayerLoginResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\x0e2\x15.login.v1.LoginResultR\x06result\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12&\n" +
	"\x0fstaff_mod_level\x18\x03 \x01(\x05R\rstaffModLevel\x12\x17\n" +
	"\x04save\x18\x04 \x01(\fH\x00R\x04save\x88\x01\x01\x12@\n" +
	"\vmuted_until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"mutedUntil\x88\x01\x01\x12\x18\n" +
	"\amembers\x18\x06 \x01(\bR\amembers\x12#\n" +
	"\rmessage_count\x18\a \x01(\x05R\fmessageCountB\a\n" +
	"\x05_saveB\x0e\n" +
	"\f_muted_until\"x\n" +
	"\x13PlayerLogoutRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04save\x18\x04 \x01(\fR\x04save\"0\n" +
	"\x14PlayerLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x15PlayerAutosaveRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04save\x18\x03 \x01(\fR\x04save\"i\n" +
	"\x18PlayerForceLogoutRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"v\n" +
	"\x10PlayerBanRequest\x12\x14\n" +
	"\x05staff\x18\x01 \x01(\tR\x05staff\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\x13\n" +
	"\x11PlayerBanResponse\"w\n" +
	"\x11PlayerMuteRequest\x12\x14\n" +
	"\x05staff\x18\x01 \x01(\tR\x05staff\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\x14\n" +
	"\x12PlayerMuteResponse*\xc8\x02\n" +
	"\vLoginResult\x12\x1c\n" +
	"\x18LOGIN_RESULT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOGIN_RESULT_OK\x10\x01\x12\x1b\n" +
	"\x17LOGIN_RESULT_NEW_PLAYER\x10\x02\x12\x1d\n" +
	"\x19LOGIN_RESULT_RECONNECT_OK\x10\x03\x12$\n" +
	" LOGIN_RESULT_INVALID_CREDENTIALS\x10\x04\x12\"\n" +
	"\x1eLOGIN_RESULT_ALREADY_LOGGED_IN\x10\x05\x12!\n" +
	"\x1dLOGIN_RESULT_ACCOUNT_DISABLED\x10\x06\x12\x1d\n" +
	"\x19LOGIN_RESULT_NOT_A_MEMBER\x10\a\x12\"\n" +
	"\x1eLOGIN_RESULT_LOGIN_IN_PROGRESS\x10\b\x12\x1a\n" +
	"\x16LOGIN_RESULT_TRY_AGAIN\x10\t2\x9b\x04\n" +
	"\fLoginService\x12E\n" +
	"\fWorldStartup\x12\x1d.login.v1.WorldStartupRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\vPlayerLogin\x12\x1c.login.v1.PlayerLoginRequest\x1a\x1d.login.v1.PlayerLoginResponse\x12M\n" +
	"\fPlayerLogout\x12\x1d.login.v1.PlayerLogoutRequest\x1a\x1e.login.v1.PlayerLogoutResponse\x12I\n" +
	"\x0ePlayerAutosave\x12\x1f.login.v1.PlayerAutosaveRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x11PlayerForceLogout\x12\".login.v1.PlayerForceLogoutRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\tPlayerBan\x12\x1a.login.v1.PlayerBanRequest\x1a\x1b.login.v1.PlayerBanResponse\x12G\n" +
	"\n" +
	"PlayerMute\x12\x1b.login.v1.PlayerMuteRequest\x1a\x1c.login.v1.PlayerMuteResponseB%Z#github.com/zsrv/goscape/pkg/loginpbb\x06proto3"

var (
	file_login_login_proto_rawDescOnce sync.Once
	file_login_login_proto_rawDescData []byte
)

func file_login_login_proto_rawDescGZIP() []byte {
	file_login_login_proto_rawDescOnce.Do(func() {
		file_login_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_login_proto_rawDesc), len(file_login_login_proto_rawDesc)))
	})
	return file_login_login_proto_rawDescData
}

var file_login_login_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_login_login_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_login_login_proto_goTypes = []any{
	(LoginResult)(0),                 // 0: login.v1.LoginResult
	(*WorldStartupRequest)(nil),      // 1: login.v1.WorldStartupRequest
	(*PlayerLoginRequest)(nil),       // 2: login.v1.PlayerLoginRequest
	(*PlayerLoginResponse)(nil),      // 3: login.v1.PlayerLoginResponse
	(*PlayerLogoutRequest)(nil),      // 4: login.v1.PlayerLogoutRequest
	(*PlayerLogoutResponse)(nil),     // 5: login.v1.PlayerLogoutResponse
	(*PlayerAutosaveRequest)(nil),    // 6: login.v1.PlayerAutosaveRequest
	(*PlayerForceLogoutRequest)(nil), // 7: login.v1.PlayerForceLogoutRequest
	(*PlayerBanRequest)(nil),         // 8: login.v1.PlayerBanRequest
	(*PlayerBanResponse)(nil),        // 9: login.v1.PlayerBanResponse
	(*PlayerMuteRequest)(nil),        // 10: login.v1.PlayerMuteRequest
	(*PlayerMuteResponse)(nil),       // 11: login.v1.PlayerMuteResponse
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 13: google.protobuf.Empty
}
var file_login_login_proto_depIdxs = []int32{
	0,  // 0: login.v1.PlayerLoginResponse.result:type_name -> login.v1.LoginResult
	12, // 1: login.v1.PlayerLoginResponse.muted_until:type_name -> google.protobuf.Timestamp
	12, // 2: login.v1.PlayerBanRequest.until:type_name -> google.protobuf.Timestamp
	12, // 3: login.v1.PlayerMuteRequest.until:type_name -> google.protobuf.Timestamp
	1,  // 4: login.v1.LoginService.WorldStartup:input_type -> login.v1.WorldStartupRequest
	2,  // 5: login.v1.LoginService.PlayerLogin:input_type -> login.v1.PlayerLoginRequest
	4,  // 6: login.v1.LoginService.PlayerLogout:input_type -> login.v1.PlayerLogoutRequest
	6,  // 7: login.v1.LoginService.PlayerAutosave:input_type -> login.v1.PlayerAutosaveRequest
	7,  // 8: login.v1.LoginService.PlayerForceLogout:input_type -> login.v1.PlayerForceLogoutRequest
	8,  // 9: login.v1.LoginService.PlayerBan:input_type -> login.v1.PlayerBanRequest
	10, // 10: login.v1.LoginService.PlayerMute:input_type -> login.v1.PlayerMuteRequest
	13, // 11: login.v1.LoginService.WorldStartup:output_type -> google.protobuf.Empty
	3,  // 12: login.v1.LoginService.PlayerLogin:output_type -> login.v1.PlayerLoginResponse
	5,  // 13: login.v1.LoginService.PlayerLogout:output_type -> login.v1.PlayerLogoutResponse
	13, // 14: login.v1.LoginService.PlayerAutosave:output_type -> google.protobuf.Empty
	13, // 15: login.v1.LoginService.PlayerForceLogout:output_type -> google.protobuf.Empty
	9,  // 16: login.v1.LoginService.PlayerBan:output_type -> login.v1.PlayerBanResponse
	11, // 17: login.v1.LoginService.PlayerMute:output_type -> login.v1.PlayerMuteResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_login_login_proto_init() }
func file_login_login_proto_init() {
	if File_login_login_proto != nil {
		return
	}
	file_login_login_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_login_proto_rawDesc), len(file_login_login_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_login_proto_goTypes,
		DependencyIndexes: file_login_login_proto_depIdxs,
		EnumInfos:         file_login_login_proto_enumTypes,
		MessageInfos:      file_login_login_proto_msgTypes,
	}.Build()
	File_login_login_proto = out.File
	file_login_login_proto_goTypes = nil
	file_login_login_proto_depIdxs = nil
}
