// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: login/login.proto

package loginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginService_WorldStartup_FullMethodName      = "/login.v1.LoginService/WorldStartup"
	LoginService_PlayerLogin_FullMethodName       = "/login.v1.LoginService/PlayerLogin"
	LoginService_PlayerLogout_FullMethodName      = "/login.v1.LoginService/PlayerLogout"
	LoginService_PlayerAutosave_FullMethodName    = "/login.v1.LoginService/PlayerAutosave"
	LoginService_PlayerForceLogout_FullMethodName = "/login.v1.LoginService/PlayerForceLogout"
	LoginService_PlayerBan_FullMethodName         = "/login.v1.LoginService/PlayerBan"
	LoginService_PlayerMute_FullMethodName        = "/login.v1.LoginService/PlayerMute"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	WorldStartup(ctx context.Context, in *WorldStartupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PlayerLogin(ctx context.Context, in *PlayerLoginRequest, opts ...grpc.CallOption) (*PlayerLoginResponse, error)
	PlayerLogout(ctx context.Context, in *PlayerLogoutRequest, opts ...grpc.CallOption) (*PlayerLogoutResponse, error)
	PlayerAutosave(ctx context.Context, in *PlayerAutosaveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PlayerForceLogout(ctx context.Context, in *PlayerForceLogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PlayerBan(ctx context.Context, in *PlayerBanRequest, opts ...grpc.CallOption) (*PlayerBanResponse, error)
	PlayerMute(ctx context.Context, in *PlayerMuteRequest, opts ...grpc.CallOption) (*PlayerMuteResponse, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) WorldStartup(ctx context.Context, in *WorldStartupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoginService_WorldStartup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) PlayerLogin(ctx context.Context, in *PlayerLoginRequest, opts ...grpc.CallOption) (*PlayerLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerLoginResponse)
	err := c.cc.Invoke(ctx, LoginService_PlayerLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) PlayerLogout(ctx context.Context, in *PlayerLogoutRequest, opts ...grpc.CallOption) (*PlayerLogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerLogoutResponse)
	err := c.cc.Invoke(ctx, LoginService_PlayerLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) PlayerAutosave(ctx context.Context, in *PlayerAutosaveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoginService_PlayerAutosave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) PlayerForceLogout(ctx context.Context, in *PlayerForceLogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoginService_PlayerForceLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) PlayerBan(ctx context.Context, in *PlayerBanRequest, opts ...grpc.CallOption) (*PlayerBanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerBanResponse)
	err := c.cc.Invoke(ctx, LoginService_PlayerBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) PlayerMute(ctx context.Context, in *PlayerMuteRequest, opts ...grpc.CallOption) (*PlayerMuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerMuteResponse)
	err := c.cc.Invoke(ctx, LoginService_PlayerMute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility.
type LoginServiceServer interface {
	WorldStartup(context.Context, *WorldStartupRequest) (*emptypb.Empty, error)
	PlayerLogin(context.Context, *PlayerLoginRequest) (*PlayerLoginResponse, error)
	PlayerLogout(context.Context, *PlayerLogoutRequest) (*PlayerLogoutResponse, error)
	PlayerAutosave(context.Context, *PlayerAutosaveRequest) (*emptypb.Empty, error)
	PlayerForceLogout(context.Context, *PlayerForceLogoutRequest) (*emptypb.Empty, error)
	PlayerBan(context.Context, *PlayerBanRequest) (*PlayerBanResponse, error)
	PlayerMute(context.Context, *PlayerMuteRequest) (*PlayerMuteResponse, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServiceServer struct{}

func (UnimplementedLoginServiceServer) WorldStartup(context.Context, *WorldStartupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WorldStartup not implemented")
}
func (UnimplementedLoginServiceServer) PlayerLogin(context.Context, *PlayerLoginRequest) (*PlayerLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerLogin not implemented")
}
func (UnimplementedLoginServiceServer) PlayerLogout(context.Context, *PlayerLogoutRequest) (*PlayerLogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerLogout not implemented")
}
func (UnimplementedLoginServiceServer) PlayerAutosave(context.Context, *PlayerAutosaveRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerAutosave not implemented")
}
func (UnimplementedLoginServiceServer) PlayerForceLogout(context.Context, *PlayerForceLogoutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerForceLogout not implemented")
}
func (UnimplementedLoginServiceServer) PlayerBan(context.Context, *PlayerBanRequest) (*PlayerBanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerBan not implemented")
}
func (UnimplementedLoginServiceServer) PlayerMute(context.Context, *PlayerMuteRequest) (*PlayerMuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerMute not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}
func (UnimplementedLoginServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	// If the following call panics, it indicates UnimplementedLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_WorldStartup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorldStartupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).WorldStartup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_WorldStartup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).WorldStartup(ctx, req.(*WorldStartupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_PlayerLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).PlayerLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_PlayerLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).PlayerLogin(ctx, req.(*PlayerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_PlayerLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).PlayerLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_PlayerLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).PlayerLogout(ctx, req.(*PlayerLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_PlayerAutosave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAutosaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).PlayerAutosave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_PlayerAutosave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).PlayerAutosave(ctx, req.(*PlayerAutosaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_PlayerForceLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerForceLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).PlayerForceLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_PlayerForceLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).PlayerForceLogout(ctx, req.(*PlayerForceLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_PlayerBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).PlayerBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_PlayerBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).PlayerBan(ctx, req.(*PlayerBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_PlayerMute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerMuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).PlayerMute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_PlayerMute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).PlayerMute(ctx, req.(*PlayerMuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "login.v1.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorldStartup",
			Handler:    _LoginService_WorldStartup_Handler,
		},
		{
			MethodName: "PlayerLogin",
			Handler:    _LoginService_PlayerLogin_Handler,
		},
		{
			MethodName: "PlayerLogout",
			Handler:    _LoginService_PlayerLogout_Handler,
		},
		{
			MethodName: "PlayerAutosave",
			Handler:    _LoginService_PlayerAutosave_Handler,
		},
		{
			MethodName: "PlayerForceLogout",
			Handler:    _LoginService_PlayerForceLogout_Handler,
		},
		{
			MethodName: "PlayerBan",
			Handler:    _LoginService_PlayerBan_Handler,
		},
		{
			MethodName: "PlayerMute",
			Handler:    _LoginService_PlayerMute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login/login.proto",
}
