// proto/events/v1/auth.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/auth.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogoutEvent_Reason int32

const (
	LogoutEvent_REASON_UNSPECIFIED     LogoutEvent_Reason = 0
	LogoutEvent_REASON_USER_INITIATED  LogoutEvent_Reason = 1
	LogoutEvent_REASON_IDLE_TIMEOUT    LogoutEvent_Reason = 2
	LogoutEvent_REASON_KICKED          LogoutEvent_Reason = 3
	LogoutEvent_REASON_CONNECTION_LOST LogoutEvent_Reason = 4
	LogoutEvent_REASON_SERVER_SHUTDOWN LogoutEvent_Reason = 5
)

// Enum value maps for LogoutEvent_Reason.
var (
	LogoutEvent_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_USER_INITIATED",
		2: "REASON_IDLE_TIMEOUT",
		3: "REASON_KICKED",
		4: "REASON_CONNECTION_LOST",
		5: "REASON_SERVER_SHUTDOWN",
	}
	LogoutEvent_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":     0,
		"REASON_USER_INITIATED":  1,
		"REASON_IDLE_TIMEOUT":    2,
		"REASON_KICKED":          3,
		"REASON_CONNECTION_LOST": 4,
		"REASON_SERVER_SHUTDOWN": 5,
	}
)

func (x LogoutEvent_Reason) Enum() *LogoutEvent_Reason {
	p := new(LogoutEvent_Reason)
	*p = x
	return p
}

func (x LogoutEvent_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogoutEvent_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_auth_proto_enumTypes[0].Descriptor()
}

func (LogoutEvent_Reason) Type() protoreflect.EnumType {
	return &file_events_v1_auth_proto_enumTypes[0]
}

func (x LogoutEvent_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogoutEvent_Reason.Descriptor instead.
func (LogoutEvent_Reason) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_auth_proto_rawDescGZIP(), []int{2, 0}
}

// AuthEnvelope wraps every event published to the events.auth Kafka topic.
// Envelope fields use tags 1-99; oneof payload variants use tags 100+.
// Never reuse a tag. New fields must be optional (proto3 default).
type AuthEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // UUIDv7
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	AccountId     int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	WorldId       int32                  `protobuf:"varint,5,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AuthEnvelope_Login
	//	*AuthEnvelope_Logout
	Payload       isAuthEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEnvelope) Reset() {
	*x = AuthEnvelope{}
	mi := &file_events_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEnvelope) ProtoMessage() {}

func (x *AuthEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEnvelope.ProtoReflect.Descriptor instead.
func (*AuthEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AuthEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuthEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AuthEnvelope) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AuthEnvelope) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *AuthEnvelope) GetPayload() isAuthEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthEnvelope) GetLogin() *LoginEvent {
	if x != nil {
		if x, ok := x.Payload.(*AuthEnvelope_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *AuthEnvelope) GetLogout() *LogoutEvent {
	if x != nil {
		if x, ok := x.Payload.(*AuthEnvelope_Logout); ok {
			return x.Logout
		}
	}
	return nil
}

type isAuthEnvelope_Payload interface {
	isAuthEnvelope_Payload()
}

type AuthEnvelope_Login struct {
	Login *LoginEvent `protobuf:"bytes,100,opt,name=login,proto3,oneof"`
}

type AuthEnvelope_Logout struct {
	Logout *LogoutEvent `protobuf:"bytes,101,opt,name=logout,proto3,oneof"`
}

func (*AuthEnvelope_Login) isAuthEnvelope_Payload() {}

func (*AuthEnvelope_Logout) isAuthEnvelope_Payload() {}

type LoginEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ip    string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Client-supplied metadata (game-server-known; currently unpopulated).
	ClientBuild string `protobuf:"bytes,10,opt,name=client_build,json=clientBuild,proto3" json:"client_build,omitempty"`
	OsFamily    string `protobuf:"bytes,11,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	Locale      string `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	SoftwareId  string `protobuf:"bytes,13,opt,name=software_id,json=softwareId,proto3" json:"software_id,omitempty"`
	// uid is the raw client login-protocol UID (random.dat identifier).
	Uid           int32 `protobuf:"varint,27,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginEvent) Reset() {
	*x = LoginEvent{}
	mi := &file_events_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEvent) ProtoMessage() {}

func (x *LoginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEvent.ProtoReflect.Descriptor instead.
func (*LoginEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LoginEvent) GetClientBuild() string {
	if x != nil {
		return x.ClientBuild
	}
	return ""
}

func (x *LoginEvent) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *LoginEvent) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *LoginEvent) GetSoftwareId() string {
	if x != nil {
		return x.SoftwareId
	}
	return ""
}

func (x *LoginEvent) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type LogoutEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reason         LogoutEvent_Reason     `protobuf:"varint,1,opt,name=reason,proto3,enum=events.v1.LogoutEvent_Reason" json:"reason,omitempty"`
	SessionSeconds uint32                 `protobuf:"varint,2,opt,name=session_seconds,json=sessionSeconds,proto3" json:"session_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogoutEvent) Reset() {
	*x = LogoutEvent{}
	mi := &file_events_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutEvent) ProtoMessage() {}

func (x *LogoutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutEvent.ProtoReflect.Descriptor instead.
func (*LogoutEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutEvent) GetReason() LogoutEvent_Reason {
	if x != nil {
		return x.Reason
	}
	return LogoutEvent_REASON_UNSPECIFIED
}

func (x *LogoutEvent) GetSessionSeconds() uint32 {
	if x != nil {
		return x.SessionSeconds
	}
	return 0
}

var File_events_v1_auth_proto protoreflect.FileDescriptor

const file_events_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x14events/v1/auth.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x02\n" +
	"\fAuthEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x03R\taccountId\x12\x19\n" +
	"\bworld_id\x18\x05 \x01(\x05R\aworldId\x12-\n" +
	"\x05login\x18d \x01(\v2\x15.events.v1.LoginEventH\x00R\x05login\x120\n" +
	"\x06logout\x18e \x01(\v2\x16.events.v1.LogoutEventH\x00R\x06logoutB\t\n" +
	"\apayload\"\xb3\x01\n" +
	"\n" +
	"LoginEvent\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12!\n" +
	"\fclient_build\x18\n" +
	" \x01(\tR\vclientBuild\x12\x1b\n" +
	"\tos_family\x18\v \x01(\tR\bosFamily\x12\x16\n" +
	"\x06locale\x18\f \x01(\tR\x06locale\x12\x1f\n" +
	"\vsoftware_id\x18\r \x01(\tR\n" +
	"softwareId\x12\x10\n" +
	"\x03uid\x18\x1b \x01(\x05R\x03uidJ\x04\b\x02\x10\n" +
	"J\x04\b\x0e\x10\x1b\"\x8f\x02\n" +
	"\vLogoutEvent\x125\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1d.events.v1.LogoutEvent.ReasonR\x06reason\x12'\n" +
	"\x0fsession_seconds\x18\x02 \x01(\rR\x0esessionSeconds\"\x9f\x01\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REASON_USER_INITIATED\x10\x01\x12\x17\n" +
	"\x13REASON_IDLE_TIMEOUT\x10\x02\x12\x11\n" +
	"\rREASON_KICKED\x10\x03\x12\x1a\n" +
	"\x16REASON_CONNECTION_LOST\x10\x04\x12\x1a\n" +
	"\x16REASON_SERVER_SHUTDOWN\x10\x05B&Z$github.com/zsrv/goscape/pkg/eventspbb\x06proto3"

var (
	file_events_v1_auth_proto_rawDescOnce sync.Once
	file_events_v1_auth_proto_rawDescData []byte
)

func file_events_v1_auth_proto_rawDescGZIP() []byte {
	file_events_v1_auth_proto_rawDescOnce.Do(func() {
		file_events_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_auth_proto_rawDesc), len(file_events_v1_auth_proto_rawDesc)))
	})
	return file_events_v1_auth_proto_rawDescData
}

var file_events_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_v1_auth_proto_goTypes = []any{
	(LogoutEvent_Reason)(0),       // 0: events.v1.LogoutEvent.Reason
	(*AuthEnvelope)(nil),          // 1: events.v1.AuthEnvelope
	(*LoginEvent)(nil),            // 2: events.v1.LoginEvent
	(*LogoutEvent)(nil),           // 3: events.v1.LogoutEvent
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_events_v1_auth_proto_depIdxs = []int32{
	4, // 0: events.v1.AuthEnvelope.ts:type_name -> google.protobuf.Timestamp
	2, // 1: events.v1.AuthEnvelope.login:type_name -> events.v1.LoginEvent
	3, // 2: events.v1.AuthEnvelope.logout:type_name -> events.v1.LogoutEvent
	0, // 3: events.v1.LogoutEvent.reason:type_name -> events.v1.LogoutEvent.Reason
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_events_v1_auth_proto_init() }
func file_events_v1_auth_proto_init() {
	if File_events_v1_auth_proto != nil {
		return
	}
	file_events_v1_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*AuthEnvelope_Login)(nil),
		(*AuthEnvelope_Logout)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_auth_proto_rawDesc), len(file_events_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_auth_proto_goTypes,
		DependencyIndexes: file_events_v1_auth_proto_depIdxs,
		EnumInfos:         file_events_v1_auth_proto_enumTypes,
		MessageInfos:      file_events_v1_auth_proto_msgTypes,
	}.Build()
	File_events_v1_auth_proto = out.File
	file_events_v1_auth_proto_goTypes = nil
	file_events_v1_auth_proto_depIdxs = nil
}
