// proto/events/v1/player_input.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/player_input.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MouseClickEvent_Button int32

const (
	MouseClickEvent_BUTTON_UNSPECIFIED MouseClickEvent_Button = 0
	MouseClickEvent_BUTTON_LEFT        MouseClickEvent_Button = 1
	MouseClickEvent_BUTTON_RIGHT       MouseClickEvent_Button = 2
	MouseClickEvent_BUTTON_MIDDLE      MouseClickEvent_Button = 3
)

// Enum value maps for MouseClickEvent_Button.
var (
	MouseClickEvent_Button_name = map[int32]string{
		0: "BUTTON_UNSPECIFIED",
		1: "BUTTON_LEFT",
		2: "BUTTON_RIGHT",
		3: "BUTTON_MIDDLE",
	}
	MouseClickEvent_Button_value = map[string]int32{
		"BUTTON_UNSPECIFIED": 0,
		"BUTTON_LEFT":        1,
		"BUTTON_RIGHT":       2,
		"BUTTON_MIDDLE":      3,
	}
)

func (x MouseClickEvent_Button) Enum() *MouseClickEvent_Button {
	p := new(MouseClickEvent_Button)
	*p = x
	return p
}

func (x MouseClickEvent_Button) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseClickEvent_Button) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_player_input_proto_enumTypes[0].Descriptor()
}

func (MouseClickEvent_Button) Type() protoreflect.EnumType {
	return &file_events_v1_player_input_proto_enumTypes[0]
}

func (x MouseClickEvent_Button) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseClickEvent_Button.Descriptor instead.
func (MouseClickEvent_Button) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_player_input_proto_rawDescGZIP(), []int{2, 0}
}

type PlayerInputEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	AccountId     int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // partition key
	WorldId       int32                  `protobuf:"varint,5,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PlayerInputEnvelope_MouseMove
	//	*PlayerInputEnvelope_MouseClick
	//	*PlayerInputEnvelope_Camera
	//	*PlayerInputEnvelope_Keystroke
	//	*PlayerInputEnvelope_PrivateChat
	Payload       isPlayerInputEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInputEnvelope) Reset() {
	*x = PlayerInputEnvelope{}
	mi := &file_events_v1_player_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInputEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInputEnvelope) ProtoMessage() {}

func (x *PlayerInputEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_player_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInputEnvelope.ProtoReflect.Descriptor instead.
func (*PlayerInputEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_player_input_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInputEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *PlayerInputEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlayerInputEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *PlayerInputEnvelope) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerInputEnvelope) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PlayerInputEnvelope) GetPayload() isPlayerInputEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PlayerInputEnvelope) GetMouseMove() *MouseMoveEvent {
	if x != nil {
		if x, ok := x.Payload.(*PlayerInputEnvelope_MouseMove); ok {
			return x.MouseMove
		}
	}
	return nil
}

func (x *PlayerInputEnvelope) GetMouseClick() *MouseClickEvent {
	if x != nil {
		if x, ok := x.Payload.(*PlayerInputEnvelope_MouseClick); ok {
			return x.MouseClick
		}
	}
	return nil
}

func (x *PlayerInputEnvelope) GetCamera() *CameraEvent {
	if x != nil {
		if x, ok := x.Payload.(*PlayerInputEnvelope_Camera); ok {
			return x.Camera
		}
	}
	return nil
}

func (x *PlayerInputEnvelope) GetKeystroke() *KeystrokeEvent {
	if x != nil {
		if x, ok := x.Payload.(*PlayerInputEnvelope_Keystroke); ok {
			return x.Keystroke
		}
	}
	return nil
}

func (x *PlayerInputEnvelope) GetPrivateChat() *PrivateChatEvent {
	if x != nil {
		if x, ok := x.Payload.(*PlayerInputEnvelope_PrivateChat); ok {
			return x.PrivateChat
		}
	}
	return nil
}

type isPlayerInputEnvelope_Payload interface {
	isPlayerInputEnvelope_Payload()
}

type PlayerInputEnvelope_MouseMove struct {
	MouseMove *MouseMoveEvent `protobuf:"bytes,100,opt,name=mouse_move,json=mouseMove,proto3,oneof"`
}

type PlayerInputEnvelope_MouseClick struct {
	MouseClick *MouseClickEvent `protobuf:"bytes,101,opt,name=mouse_click,json=mouseClick,proto3,oneof"`
}

type PlayerInputEnvelope_Camera struct {
	Camera *CameraEvent `protobuf:"bytes,102,opt,name=camera,proto3,oneof"`
}

type PlayerInputEnvelope_Keystroke struct {
	Keystroke *KeystrokeEvent `protobuf:"bytes,103,opt,name=keystroke,proto3,oneof"`
}

type PlayerInputEnvelope_PrivateChat struct {
	PrivateChat *PrivateChatEvent `protobuf:"bytes,104,opt,name=private_chat,json=privateChat,proto3,oneof"`
}

func (*PlayerInputEnvelope_MouseMove) isPlayerInputEnvelope_Payload() {}

func (*PlayerInputEnvelope_MouseClick) isPlayerInputEnvelope_Payload() {}

func (*PlayerInputEnvelope_Camera) isPlayerInputEnvelope_Payload() {}

func (*PlayerInputEnvelope_Keystroke) isPlayerInputEnvelope_Payload() {}

func (*PlayerInputEnvelope_PrivateChat) isPlayerInputEnvelope_Payload() {}

type MouseMoveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseMoveEvent) Reset() {
	*x = MouseMoveEvent{}
	mi := &file_events_v1_player_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseMoveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseMoveEvent) ProtoMessage() {}

func (x *MouseMoveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_player_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseMoveEvent.ProtoReflect.Descriptor instead.
func (*MouseMoveEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_player_input_proto_rawDescGZIP(), []int{1}
}

func (x *MouseMoveEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseMoveEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MouseClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Button        MouseClickEvent_Button `protobuf:"varint,3,opt,name=button,proto3,enum=events.v1.MouseClickEvent_Button" json:"button,omitempty"`
	TargetKind    string                 `protobuf:"bytes,4,opt,name=target_kind,json=targetKind,proto3" json:"target_kind,omitempty"`
	TargetId      int64                  `protobuf:"varint,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseClickEvent) Reset() {
	*x = MouseClickEvent{}
	mi := &file_events_v1_player_input_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseClickEvent) ProtoMessage() {}

func (x *MouseClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_player_input_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseClickEvent.ProtoReflect.Descriptor instead.
func (*MouseClickEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_player_input_proto_rawDescGZIP(), []int{2}
}

func (x *MouseClickEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseClickEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseClickEvent) GetButton() MouseClickEvent_Button {
	if x != nil {
		return x.Button
	}
	return MouseClickEvent_BUTTON_UNSPECIFIED
}

func (x *MouseClickEvent) GetTargetKind() string {
	if x != nil {
		return x.TargetKind
	}
	return ""
}

func (x *MouseClickEvent) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CameraEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaw           float32                `protobuf:"fixed32,1,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Zoom          float32                `protobuf:"fixed32,3,opt,name=zoom,proto3" json:"zoom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraEvent) Reset() {
	*x = CameraEvent{}
	mi := &file_events_v1_player_input_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraEvent) ProtoMessage() {}

func (x *CameraEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_player_input_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraEvent.ProtoReflect.Descriptor instead.
func (*CameraEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_player_input_proto_rawDescGZIP(), []int{3}
}

func (x *CameraEvent) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *CameraEvent) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *CameraEvent) GetZoom() float32 {
	if x != nil {
		return x.Zoom
	}
	return 0
}

type KeystrokeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyCode       uint32                 `protobuf:"varint,1,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"`
	Modifiers     uint32                 `protobuf:"varint,2,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeystrokeEvent) Reset() {
	*x = KeystrokeEvent{}
	mi := &file_events_v1_player_input_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeystrokeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeystrokeEvent) ProtoMessage() {}

func (x *KeystrokeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_player_input_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeystrokeEvent.ProtoReflect.Descriptor instead.
func (*KeystrokeEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_player_input_proto_rawDescGZIP(), []int{4}
}

func (x *KeystrokeEvent) GetKeyCode() uint32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

func (x *KeystrokeEvent) GetModifiers() uint32 {
	if x != nil {
		return x.Modifiers
	}
	return 0
}

type PrivateChatEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientAccountId int64                  `protobuf:"varint,1,opt,name=recipient_account_id,json=recipientAccountId,proto3" json:"recipient_account_id,omitempty"`
	Text               string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrivateChatEvent) Reset() {
	*x = PrivateChatEvent{}
	mi := &file_events_v1_player_input_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatEvent) ProtoMessage() {}

func (x *PrivateChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_player_input_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatEvent.ProtoReflect.Descriptor instead.
func (*PrivateChatEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_player_input_proto_rawDescGZIP(), []int{5}
}

func (x *PrivateChatEvent) GetRecipientAccountId() int64 {
	if x != nil {
		return x.RecipientAccountId
	}
	return 0
}

func (x *PrivateChatEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_events_v1_player_input_proto protoreflect.FileDescriptor

const file_events_v1_player_input_proto_rawDesc = "" +
	"\n" +
	"\x1cevents/v1/player_input.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x03\n" +
	"\x13PlayerInputEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x03R\taccountId\x12\x19\n" +
	"\bworld_id\x18\x05 \x01(\x05R\aworldId\x12:\n" +
	"\n" +
	"mouse_move\x18d \x01(\v2\x19.events.v1.MouseMoveEventH\x00R\tmouseMove\x12=\n" +
	"\vmouse_click\x18e \x01(\v2\x1a.events.v1.MouseClickEventH\x00R\n" +
	"mouseClick\x120\n" +
	"\x06camera\x18f \x01(\v2\x16.events.v1.CameraEventH\x00R\x06camera\x129\n" +
	"\tkeystroke\x18g \x01(\v2\x19.events.v1.KeystrokeEventH\x00R\tkeystroke\x12@\n" +
	"\fprivate_chat\x18h \x01(\v2\x1b.events.v1.PrivateChatEventH\x00R\vprivateChatB\t\n" +
	"\apayload\",\n" +
	"\x0eMouseMoveEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xfe\x01\n" +
	"\x0fMouseClickEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x129\n" +
	"\x06button\x18\x03 \x01(\x0e2!.events.v1.MouseClickEvent.ButtonR\x06button\x12\x1f\n" +
	"\vtarget_kind\x18\x04 \x01(\tR\n" +
	"targetKind\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\x03R\btargetId\"V\n" +
	"\x06Button\x12\x16\n" +
	"\x12BUTTON_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vBUTTON_LEFT\x10\x01\x12\x10\n" +
	"\fBUTTON_RIGHT\x10\x02\x12\x11\n" +
	"\rBUTTON_MIDDLE\x10\x03\"I\n" +
	"\vCameraEvent\x12\x10\n" +
	"\x03yaw\x18\x01 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x02 \x01(\x02R\x05pitch\x12\x12\n" +
	"\x04zoom\x18\x03 \x01(\x02R\x04zoom\"I\n" +
	"\x0eKeystrokeEvent\x12\x19\n" +
	"\bkey_code\x18\x01 \x01(\rR\akeyCode\x12\x1c\n" +
	"\tmodifiers\x18\x02 \x01(\rR\tmodifiers\"X\n" +
	"\x10PrivateChatEvent\x120\n" +
	"\x14recipient_account_id\x18\x01 \x01(\x03R\x12recipientAccountId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textB&Z$github.com/zsrv/goscape/pkg/eventspbb\x06proto3"

var (
	file_events_v1_player_input_proto_rawDescOnce sync.Once
	file_events_v1_player_input_proto_rawDescData []byte
)

func file_events_v1_player_input_proto_rawDescGZIP() []byte {
	file_events_v1_player_input_proto_rawDescOnce.Do(func() {
		file_events_v1_player_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_player_input_proto_rawDesc), len(file_events_v1_player_input_proto_rawDesc)))
	})
	return file_events_v1_player_input_proto_rawDescData
}

var file_events_v1_player_input_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_v1_player_input_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_events_v1_player_input_proto_goTypes = []any{
	(MouseClickEvent_Button)(0),   // 0: events.v1.MouseClickEvent.Button
	(*PlayerInputEnvelope)(nil),   // 1: events.v1.PlayerInputEnvelope
	(*MouseMoveEvent)(nil),        // 2: events.v1.MouseMoveEvent
	(*MouseClickEvent)(nil),       // 3: events.v1.MouseClickEvent
	(*CameraEvent)(nil),           // 4: events.v1.CameraEvent
	(*KeystrokeEvent)(nil),        // 5: events.v1.KeystrokeEvent
	(*PrivateChatEvent)(nil),      // 6: events.v1.PrivateChatEvent
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_events_v1_player_input_proto_depIdxs = []int32{
	7, // 0: events.v1.PlayerInputEnvelope.ts:type_name -> google.protobuf.Timestamp
	2, // 1: events.v1.PlayerInputEnvelope.mouse_move:type_name -> events.v1.MouseMoveEvent
	3, // 2: events.v1.PlayerInputEnvelope.mouse_click:type_name -> events.v1.MouseClickEvent
	4, // 3: events.v1.PlayerInputEnvelope.camera:type_name -> events.v1.CameraEvent
	5, // 4: events.v1.PlayerInputEnvelope.keystroke:type_name -> events.v1.KeystrokeEvent
	6, // 5: events.v1.PlayerInputEnvelope.private_chat:type_name -> events.v1.PrivateChatEvent
	0, // 6: events.v1.MouseClickEvent.button:type_name -> events.v1.MouseClickEvent.Button
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_events_v1_player_input_proto_init() }
func file_events_v1_player_input_proto_init() {
	if File_events_v1_player_input_proto != nil {
		return
	}
	file_events_v1_player_input_proto_msgTypes[0].OneofWrappers = []any{
		(*PlayerInputEnvelope_MouseMove)(nil),
		(*PlayerInputEnvelope_MouseClick)(nil),
		(*PlayerInputEnvelope_Camera)(nil),
		(*PlayerInputEnvelope_Keystroke)(nil),
		(*PlayerInputEnvelope_PrivateChat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_player_input_proto_rawDesc), len(file_events_v1_player_input_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_player_input_proto_goTypes,
		DependencyIndexes: file_events_v1_player_input_proto_depIdxs,
		EnumInfos:         file_events_v1_player_input_proto_enumTypes,
		MessageInfos:      file_events_v1_player_input_proto_msgTypes,
	}.Build()
	File_events_v1_player_input_proto = out.File
	file_events_v1_player_input_proto_goTypes = nil
	file_events_v1_player_input_proto_depIdxs = nil
}
