// proto/events/v1/replay.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/replay.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionEvent_Kind int32

const (
	SessionEvent_KIND_UNSPECIFIED SessionEvent_Kind = 0
	SessionEvent_KIND_STARTED     SessionEvent_Kind = 1
	SessionEvent_KIND_ENDED       SessionEvent_Kind = 2
)

// Enum value maps for SessionEvent_Kind.
var (
	SessionEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_STARTED",
		2: "KIND_ENDED",
	}
	SessionEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_STARTED":     1,
		"KIND_ENDED":       2,
	}
)

func (x SessionEvent_Kind) Enum() *SessionEvent_Kind {
	p := new(SessionEvent_Kind)
	*p = x
	return p
}

func (x SessionEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_replay_proto_enumTypes[0].Descriptor()
}

func (SessionEvent_Kind) Type() protoreflect.EnumType {
	return &file_events_v1_replay_proto_enumTypes[0]
}

func (x SessionEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionEvent_Kind.Descriptor instead.
func (SessionEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_replay_proto_rawDescGZIP(), []int{2, 0}
}

// ReplayEnvelope wraps every record published to events.replay_packets.
// One Kafka topic; the oneof discriminates packet vs. session-lifecycle
// payloads. Consumers route on the populated field.
type ReplayEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	WorldId       int32                  `protobuf:"varint,4,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	// revision is the wire revision of the binary that emitted this record
	// (the revision.Expected constant). One world_id can be served by
	// several revisions at once, so revision is part of the record's origin.
	// 0 means the record was emitted by a build that predates this field.
	Revision uint32 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	// profile is the deployment profile the capturing world was configured
	// with (default "main"). account_id is global across profiles, so
	// profile is what separates the same account seen under two deployments.
	// "" means the record was emitted by a build that predates this field.
	// Tag 7 is deliberately left unused here: the other four envelopes
	// carry revision on 6 and profile on 7, while this one already had
	// revision on 5.
	Profile string `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ReplayEnvelope_Packet
	//	*ReplayEnvelope_Session
	Payload       isReplayEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayEnvelope) Reset() {
	*x = ReplayEnvelope{}
	mi := &file_events_v1_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayEnvelope) ProtoMessage() {}

func (x *ReplayEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayEnvelope.ProtoReflect.Descriptor instead.
func (*ReplayEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_replay_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ReplayEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReplayEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ReplayEnvelope) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *ReplayEnvelope) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ReplayEnvelope) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ReplayEnvelope) GetPayload() isReplayEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReplayEnvelope) GetPacket() *PacketEvent {
	if x != nil {
		if x, ok := x.Payload.(*ReplayEnvelope_Packet); ok {
			return x.Packet
		}
	}
	return nil
}

func (x *ReplayEnvelope) GetSession() *SessionEvent {
	if x != nil {
		if x, ok := x.Payload.(*ReplayEnvelope_Session); ok {
			return x.Session
		}
	}
	return nil
}

type isReplayEnvelope_Payload interface {
	isReplayEnvelope_Payload()
}

type ReplayEnvelope_Packet struct {
	Packet *PacketEvent `protobuf:"bytes,100,opt,name=packet,proto3,oneof"`
}

type ReplayEnvelope_Session struct {
	Session *SessionEvent `protobuf:"bytes,101,opt,name=session,proto3,oneof"`
}

func (*ReplayEnvelope_Packet) isReplayEnvelope_Payload() {}

func (*ReplayEnvelope_Session) isReplayEnvelope_Payload() {}

// PacketEvent: one captured wire packet (in either direction).
// `payload` is the raw packet BODY ONLY — the opcode is in its own field,
// not prefixed onto `payload`. Same convention for both directions.
type PacketEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // UUID as 36-char string
	Dir           uint32                 `protobuf:"varint,3,opt,name=dir,proto3" json:"dir,omitempty"`                             // 0 = inbound, 1 = outbound
	Opcode        uint32                 `protobuf:"varint,4,opt,name=opcode,proto3" json:"opcode,omitempty"`                       // 0-255
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketEvent) Reset() {
	*x = PacketEvent{}
	mi := &file_events_v1_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketEvent) ProtoMessage() {}

func (x *PacketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketEvent.ProtoReflect.Descriptor instead.
func (*PacketEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_replay_proto_rawDescGZIP(), []int{1}
}

func (x *PacketEvent) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PacketEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PacketEvent) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *PacketEvent) GetOpcode() uint32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *PacketEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SessionEvent: connection lifecycle. STARTED on login OK; ENDED on
// teardown, carrying total counters captured during the session.
type SessionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Kind           SessionEvent_Kind      `protobuf:"varint,3,opt,name=kind,proto3,enum=events.v1.SessionEvent_Kind" json:"kind,omitempty"`
	CloseReason    string                 `protobuf:"bytes,4,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"` // empty for STARTED
	PacketCountIn  uint64                 `protobuf:"varint,5,opt,name=packet_count_in,json=packetCountIn,proto3" json:"packet_count_in,omitempty"`
	PacketCountOut uint64                 `protobuf:"varint,6,opt,name=packet_count_out,json=packetCountOut,proto3" json:"packet_count_out,omitempty"`
	ByteCountIn    uint64                 `protobuf:"varint,7,opt,name=byte_count_in,json=byteCountIn,proto3" json:"byte_count_in,omitempty"`
	ByteCountOut   uint64                 `protobuf:"varint,8,opt,name=byte_count_out,json=byteCountOut,proto3" json:"byte_count_out,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"` // zero for STARTED
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_events_v1_replay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_replay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_replay_proto_rawDescGZIP(), []int{2}
}

func (x *SessionEvent) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetKind() SessionEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return SessionEvent_KIND_UNSPECIFIED
}

func (x *SessionEvent) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *SessionEvent) GetPacketCountIn() uint64 {
	if x != nil {
		return x.PacketCountIn
	}
	return 0
}

func (x *SessionEvent) GetPacketCountOut() uint64 {
	if x != nil {
		return x.PacketCountOut
	}
	return 0
}

func (x *SessionEvent) GetByteCountIn() uint64 {
	if x != nil {
		return x.ByteCountIn
	}
	return 0
}

func (x *SessionEvent) GetByteCountOut() uint64 {
	if x != nil {
		return x.ByteCountOut
	}
	return 0
}

func (x *SessionEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SessionEvent) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

var File_events_v1_replay_proto protoreflect.FileDescriptor

const file_events_v1_replay_proto_rawDesc = "" +
	"\n" +
	"\x16events/v1/replay.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x02\n" +
	"\x0eReplayEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x19\n" +
	"\bworld_id\x18\x04 \x01(\x05R\aworldId\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\rR\brevision\x12\x18\n" +
	"\aprofile\x18\x06 \x01(\tR\aprofile\x120\n" +
	"\x06packet\x18d \x01(\v2\x16.events.v1.PacketEventH\x00R\x06packet\x123\n" +
	"\asession\x18e \x01(\v2\x17.events.v1.SessionEventH\x00R\asessionB\t\n" +
	"\apayload\"\x8f\x01\n" +
	"\vPacketEvent\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\rR\x03dir\x12\x16\n" +
	"\x06opcode\x18\x04 \x01(\rR\x06opcode\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xef\x03\n" +
	"\fSessionEvent\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.events.v1.SessionEvent.KindR\x04kind\x12!\n" +
	"\fclose_reason\x18\x04 \x01(\tR\vcloseReason\x12&\n" +
	"\x0fpacket_count_in\x18\x05 \x01(\x04R\rpacketCountIn\x12(\n" +
	"\x10packet_count_out\x18\x06 \x01(\x04R\x0epacketCountOut\x12\"\n" +
	"\rbyte_count_in\x18\a \x01(\x04R\vbyteCountIn\x12$\n" +
	"\x0ebyte_count_out\x18\b \x01(\x04R\fbyteCountOut\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\">\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fKIND_STARTED\x10\x01\x12\x0e\n" +
	"\n" +
	"KIND_ENDED\x10\x02B&Z$github.com/zsrv/goscape/pkg/eventspbb\x06proto3"

var (
	file_events_v1_replay_proto_rawDescOnce sync.Once
	file_events_v1_replay_proto_rawDescData []byte
)

func file_events_v1_replay_proto_rawDescGZIP() []byte {
	file_events_v1_replay_proto_rawDescOnce.Do(func() {
		file_events_v1_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_replay_proto_rawDesc), len(file_events_v1_replay_proto_rawDesc)))
	})
	return file_events_v1_replay_proto_rawDescData
}

var file_events_v1_replay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_v1_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_v1_replay_proto_goTypes = []any{
	(SessionEvent_Kind)(0),        // 0: events.v1.SessionEvent.Kind
	(*ReplayEnvelope)(nil),        // 1: events.v1.ReplayEnvelope
	(*PacketEvent)(nil),           // 2: events.v1.PacketEvent
	(*SessionEvent)(nil),          // 3: events.v1.SessionEvent
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_events_v1_replay_proto_depIdxs = []int32{
	4, // 0: events.v1.ReplayEnvelope.ts:type_name -> google.protobuf.Timestamp
	2, // 1: events.v1.ReplayEnvelope.packet:type_name -> events.v1.PacketEvent
	3, // 2: events.v1.ReplayEnvelope.session:type_name -> events.v1.SessionEvent
	0, // 3: events.v1.SessionEvent.kind:type_name -> events.v1.SessionEvent.Kind
	4, // 4: events.v1.SessionEvent.started_at:type_name -> google.protobuf.Timestamp
	4, // 5: events.v1.SessionEvent.ended_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_events_v1_replay_proto_init() }
func file_events_v1_replay_proto_init() {
	if File_events_v1_replay_proto != nil {
		return
	}
	file_events_v1_replay_proto_msgTypes[0].OneofWrappers = []any{
		(*ReplayEnvelope_Packet)(nil),
		(*ReplayEnvelope_Session)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_replay_proto_rawDesc), len(file_events_v1_replay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_replay_proto_goTypes,
		DependencyIndexes: file_events_v1_replay_proto_depIdxs,
		EnumInfos:         file_events_v1_replay_proto_enumTypes,
		MessageInfos:      file_events_v1_replay_proto_msgTypes,
	}.Build()
	File_events_v1_replay_proto = out.File
	file_events_v1_replay_proto_goTypes = nil
	file_events_v1_replay_proto_depIdxs = nil
}
