// proto/events/v1/wealth.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/wealth.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WealthEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	AccountId     int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // partition key
	WorldId       int32                  `protobuf:"varint,5,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WealthEnvelope_TradeCompleted
	//	*WealthEnvelope_ItemDropped
	//	*WealthEnvelope_ItemPickedUp
	Payload       isWealthEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WealthEnvelope) Reset() {
	*x = WealthEnvelope{}
	mi := &file_events_v1_wealth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WealthEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WealthEnvelope) ProtoMessage() {}

func (x *WealthEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_wealth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WealthEnvelope.ProtoReflect.Descriptor instead.
func (*WealthEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_wealth_proto_rawDescGZIP(), []int{0}
}

func (x *WealthEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *WealthEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WealthEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WealthEnvelope) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WealthEnvelope) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *WealthEnvelope) GetPayload() isWealthEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WealthEnvelope) GetTradeCompleted() *TradeCompletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*WealthEnvelope_TradeCompleted); ok {
			return x.TradeCompleted
		}
	}
	return nil
}

func (x *WealthEnvelope) GetItemDropped() *ItemDroppedEvent {
	if x != nil {
		if x, ok := x.Payload.(*WealthEnvelope_ItemDropped); ok {
			return x.ItemDropped
		}
	}
	return nil
}

func (x *WealthEnvelope) GetItemPickedUp() *ItemPickedUpEvent {
	if x != nil {
		if x, ok := x.Payload.(*WealthEnvelope_ItemPickedUp); ok {
			return x.ItemPickedUp
		}
	}
	return nil
}

type isWealthEnvelope_Payload interface {
	isWealthEnvelope_Payload()
}

type WealthEnvelope_TradeCompleted struct {
	TradeCompleted *TradeCompletedEvent `protobuf:"bytes,100,opt,name=trade_completed,json=tradeCompleted,proto3,oneof"`
}

type WealthEnvelope_ItemDropped struct {
	ItemDropped *ItemDroppedEvent `protobuf:"bytes,101,opt,name=item_dropped,json=itemDropped,proto3,oneof"`
}

type WealthEnvelope_ItemPickedUp struct {
	ItemPickedUp *ItemPickedUpEvent `protobuf:"bytes,102,opt,name=item_picked_up,json=itemPickedUp,proto3,oneof"`
}

func (*WealthEnvelope_TradeCompleted) isWealthEnvelope_Payload() {}

func (*WealthEnvelope_ItemDropped) isWealthEnvelope_Payload() {}

func (*WealthEnvelope_ItemPickedUp) isWealthEnvelope_Payload() {}

type ItemStack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Qty           int32                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStack) Reset() {
	*x = ItemStack{}
	mi := &file_events_v1_wealth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStack) ProtoMessage() {}

func (x *ItemStack) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_wealth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStack.ProtoReflect.Descriptor instead.
func (*ItemStack) Descriptor() ([]byte, []int) {
	return file_events_v1_wealth_proto_rawDescGZIP(), []int{1}
}

func (x *ItemStack) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemStack) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type TradeCompletedEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartnerAccountId int64                  `protobuf:"varint,1,opt,name=partner_account_id,json=partnerAccountId,proto3" json:"partner_account_id,omitempty"`
	ItemsGiven       []*ItemStack           `protobuf:"bytes,2,rep,name=items_given,json=itemsGiven,proto3" json:"items_given,omitempty"`
	ItemsReceived    []*ItemStack           `protobuf:"bytes,3,rep,name=items_received,json=itemsReceived,proto3" json:"items_received,omitempty"`
	ValueGiven       int64                  `protobuf:"varint,4,opt,name=value_given,json=valueGiven,proto3" json:"value_given,omitempty"`
	ValueReceived    int64                  `protobuf:"varint,5,opt,name=value_received,json=valueReceived,proto3" json:"value_received,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TradeCompletedEvent) Reset() {
	*x = TradeCompletedEvent{}
	mi := &file_events_v1_wealth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeCompletedEvent) ProtoMessage() {}

func (x *TradeCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_wealth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeCompletedEvent.ProtoReflect.Descriptor instead.
func (*TradeCompletedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_wealth_proto_rawDescGZIP(), []int{2}
}

func (x *TradeCompletedEvent) GetPartnerAccountId() int64 {
	if x != nil {
		return x.PartnerAccountId
	}
	return 0
}

func (x *TradeCompletedEvent) GetItemsGiven() []*ItemStack {
	if x != nil {
		return x.ItemsGiven
	}
	return nil
}

func (x *TradeCompletedEvent) GetItemsReceived() []*ItemStack {
	if x != nil {
		return x.ItemsReceived
	}
	return nil
}

func (x *TradeCompletedEvent) GetValueGiven() int64 {
	if x != nil {
		return x.ValueGiven
	}
	return 0
}

func (x *TradeCompletedEvent) GetValueReceived() int64 {
	if x != nil {
		return x.ValueReceived
	}
	return 0
}

type ItemDroppedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Qty           int32                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Plane         int32                  `protobuf:"varint,5,opt,name=plane,proto3" json:"plane,omitempty"`
	AlchValue     int64                  `protobuf:"varint,6,opt,name=alch_value,json=alchValue,proto3" json:"alch_value,omitempty"`
	MarketValue   int64                  `protobuf:"varint,7,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDroppedEvent) Reset() {
	*x = ItemDroppedEvent{}
	mi := &file_events_v1_wealth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDroppedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDroppedEvent) ProtoMessage() {}

func (x *ItemDroppedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_wealth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDroppedEvent.ProtoReflect.Descriptor instead.
func (*ItemDroppedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_wealth_proto_rawDescGZIP(), []int{3}
}

func (x *ItemDroppedEvent) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemDroppedEvent) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *ItemDroppedEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ItemDroppedEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ItemDroppedEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

func (x *ItemDroppedEvent) GetAlchValue() int64 {
	if x != nil {
		return x.AlchValue
	}
	return 0
}

func (x *ItemDroppedEvent) GetMarketValue() int64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

type ItemPickedUpEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ItemId             int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Qty                int32                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	X                  int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                  int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Plane              int32                  `protobuf:"varint,5,opt,name=plane,proto3" json:"plane,omitempty"`
	DroppedByAccountId int64                  `protobuf:"varint,6,opt,name=dropped_by_account_id,json=droppedByAccountId,proto3" json:"dropped_by_account_id,omitempty"` // 0 if unknown
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ItemPickedUpEvent) Reset() {
	*x = ItemPickedUpEvent{}
	mi := &file_events_v1_wealth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemPickedUpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPickedUpEvent) ProtoMessage() {}

func (x *ItemPickedUpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_wealth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPickedUpEvent.ProtoReflect.Descriptor instead.
func (*ItemPickedUpEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_wealth_proto_rawDescGZIP(), []int{4}
}

func (x *ItemPickedUpEvent) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemPickedUpEvent) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *ItemPickedUpEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ItemPickedUpEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ItemPickedUpEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

func (x *ItemPickedUpEvent) GetDroppedByAccountId() int64 {
	if x != nil {
		return x.DroppedByAccountId
	}
	return 0
}

var File_events_v1_wealth_proto protoreflect.FileDescriptor

const file_events_v1_wealth_proto_rawDesc = "" +
	"\n" +
	"\x16events/v1/wealth.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x03\n" +
	"\x0eWealthEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x03R\taccountId\x12\x19\n" +
	"\bworld_id\x18\x05 \x01(\x05R\aworldId\x12I\n" +
	"\x0ftrade_completed\x18d \x01(\v2\x1e.events.v1.TradeCompletedEventH\x00R\x0etradeCompleted\x12@\n" +
	"\fitem_dropped\x18e \x01(\v2\x1b.events.v1.ItemDroppedEventH\x00R\vitemDropped\x12D\n" +
	"\x0eitem_picked_up\x18f \x01(\v2\x1c.events.v1.ItemPickedUpEventH\x00R\fitemPickedUpB\t\n" +
	"\apayload\"6\n" +
	"\tItemStack\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x05R\x03qty\"\xff\x01\n" +
	"\x13TradeCompletedEvent\x12,\n" +
	"\x12partner_account_id\x18\x01 \x01(\x03R\x10partnerAccountId\x125\n" +
	"\vitems_given\x18\x02 \x03(\v2\x14.events.v1.ItemStackR\n" +
	"itemsGiven\x12;\n" +
	"\x0eitems_received\x18\x03 \x03(\v2\x14.events.v1.ItemStackR\ritemsReceived\x12\x1f\n" +
	"\vvalue_given\x18\x04 \x01(\x03R\n" +
	"valueGiven\x12%\n" +
	"\x0evalue_received\x18\x05 \x01(\x03R\rvalueReceived\"\xb1\x01\n" +
	"\x10ItemDroppedEvent\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x05R\x03qty\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\x05R\x05plane\x12\x1d\n" +
	"\n" +
	"alch_value\x18\x06 \x01(\x03R\talchValue\x12!\n" +
	"\fmarket_value\x18\a \x01(\x03R\vmarketValue\"\xa3\x01\n" +
	"\x11ItemPickedUpEvent\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x05R\x03qty\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\x05R\x05plane\x121\n" +
	"\x15dropped_by_account_id\x18\x06 \x01(\x03R\x12droppedByAccountIdB&Z$github.com/zsrv/goscape/pkg/eventspbb\x06proto3"

var (
	file_events_v1_wealth_proto_rawDescOnce sync.Once
	file_events_v1_wealth_proto_rawDescData []byte
)

func file_events_v1_wealth_proto_rawDescGZIP() []byte {
	file_events_v1_wealth_proto_rawDescOnce.Do(func() {
		file_events_v1_wealth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_wealth_proto_rawDesc), len(file_events_v1_wealth_proto_rawDesc)))
	})
	return file_events_v1_wealth_proto_rawDescData
}

var file_events_v1_wealth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_events_v1_wealth_proto_goTypes = []any{
	(*WealthEnvelope)(nil),        // 0: events.v1.WealthEnvelope
	(*ItemStack)(nil),             // 1: events.v1.ItemStack
	(*TradeCompletedEvent)(nil),   // 2: events.v1.TradeCompletedEvent
	(*ItemDroppedEvent)(nil),      // 3: events.v1.ItemDroppedEvent
	(*ItemPickedUpEvent)(nil),     // 4: events.v1.ItemPickedUpEvent
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_events_v1_wealth_proto_depIdxs = []int32{
	5, // 0: events.v1.WealthEnvelope.ts:type_name -> google.protobuf.Timestamp
	2, // 1: events.v1.WealthEnvelope.trade_completed:type_name -> events.v1.TradeCompletedEvent
	3, // 2: events.v1.WealthEnvelope.item_dropped:type_name -> events.v1.ItemDroppedEvent
	4, // 3: events.v1.WealthEnvelope.item_picked_up:type_name -> events.v1.ItemPickedUpEvent
	1, // 4: events.v1.TradeCompletedEvent.items_given:type_name -> events.v1.ItemStack
	1, // 5: events.v1.TradeCompletedEvent.items_received:type_name -> events.v1.ItemStack
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_events_v1_wealth_proto_init() }
func file_events_v1_wealth_proto_init() {
	if File_events_v1_wealth_proto != nil {
		return
	}
	file_events_v1_wealth_proto_msgTypes[0].OneofWrappers = []any{
		(*WealthEnvelope_TradeCompleted)(nil),
		(*WealthEnvelope_ItemDropped)(nil),
		(*WealthEnvelope_ItemPickedUp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_wealth_proto_rawDesc), len(file_events_v1_wealth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_wealth_proto_goTypes,
		DependencyIndexes: file_events_v1_wealth_proto_depIdxs,
		MessageInfos:      file_events_v1_wealth_proto_msgTypes,
	}.Build()
	File_events_v1_wealth_proto = out.File
	file_events_v1_wealth_proto_goTypes = nil
	file_events_v1_wealth_proto_depIdxs = nil
}
