// proto/events/v1/world.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/world.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessageEvent_Channel int32

const (
	ChatMessageEvent_CHANNEL_UNSPECIFIED ChatMessageEvent_Channel = 0
	ChatMessageEvent_CHANNEL_PUBLIC      ChatMessageEvent_Channel = 1
	ChatMessageEvent_CHANNEL_CLAN        ChatMessageEvent_Channel = 2
)

// Enum value maps for ChatMessageEvent_Channel.
var (
	ChatMessageEvent_Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_PUBLIC",
		2: "CHANNEL_CLAN",
	}
	ChatMessageEvent_Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_PUBLIC":      1,
		"CHANNEL_CLAN":        2,
	}
)

func (x ChatMessageEvent_Channel) Enum() *ChatMessageEvent_Channel {
	p := new(ChatMessageEvent_Channel)
	*p = x
	return p
}

func (x ChatMessageEvent_Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessageEvent_Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_world_proto_enumTypes[0].Descriptor()
}

func (ChatMessageEvent_Channel) Type() protoreflect.EnumType {
	return &file_events_v1_world_proto_enumTypes[0]
}

func (x ChatMessageEvent_Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessageEvent_Channel.Descriptor instead.
func (ChatMessageEvent_Channel) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{4, 0}
}

type WorldEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	WorldId       int32                  `protobuf:"varint,4,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`       // partition key
	AccountId     int64                  `protobuf:"varint,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 0 for world-scoped events
	// Types that are valid to be assigned to Payload:
	//
	//	*WorldEnvelope_TilePosition
	//	*WorldEnvelope_Combat
	//	*WorldEnvelope_Interaction
	//	*WorldEnvelope_Chat
	//	*WorldEnvelope_NpcSpawn
	//	*WorldEnvelope_NpcDespawn
	//	*WorldEnvelope_DoorState
	//	*WorldEnvelope_PacketReceived
	Payload       isWorldEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldEnvelope) Reset() {
	*x = WorldEnvelope{}
	mi := &file_events_v1_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldEnvelope) ProtoMessage() {}

func (x *WorldEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldEnvelope.ProtoReflect.Descriptor instead.
func (*WorldEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{0}
}

func (x *WorldEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *WorldEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WorldEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WorldEnvelope) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *WorldEnvelope) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WorldEnvelope) GetPayload() isWorldEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorldEnvelope) GetTilePosition() *TilePositionEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_TilePosition); ok {
			return x.TilePosition
		}
	}
	return nil
}

func (x *WorldEnvelope) GetCombat() *CombatEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_Combat); ok {
			return x.Combat
		}
	}
	return nil
}

func (x *WorldEnvelope) GetInteraction() *InteractionEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

func (x *WorldEnvelope) GetChat() *ChatMessageEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *WorldEnvelope) GetNpcSpawn() *NpcSpawnEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_NpcSpawn); ok {
			return x.NpcSpawn
		}
	}
	return nil
}

func (x *WorldEnvelope) GetNpcDespawn() *NpcDespawnEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_NpcDespawn); ok {
			return x.NpcDespawn
		}
	}
	return nil
}

func (x *WorldEnvelope) GetDoorState() *DoorStateEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_DoorState); ok {
			return x.DoorState
		}
	}
	return nil
}

func (x *WorldEnvelope) GetPacketReceived() *PacketReceivedEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_PacketReceived); ok {
			return x.PacketReceived
		}
	}
	return nil
}

type isWorldEnvelope_Payload interface {
	isWorldEnvelope_Payload()
}

type WorldEnvelope_TilePosition struct {
	TilePosition *TilePositionEvent `protobuf:"bytes,100,opt,name=tile_position,json=tilePosition,proto3,oneof"`
}

type WorldEnvelope_Combat struct {
	Combat *CombatEvent `protobuf:"bytes,101,opt,name=combat,proto3,oneof"`
}

type WorldEnvelope_Interaction struct {
	Interaction *InteractionEvent `protobuf:"bytes,102,opt,name=interaction,proto3,oneof"`
}

type WorldEnvelope_Chat struct {
	Chat *ChatMessageEvent `protobuf:"bytes,103,opt,name=chat,proto3,oneof"`
}

type WorldEnvelope_NpcSpawn struct {
	NpcSpawn *NpcSpawnEvent `protobuf:"bytes,104,opt,name=npc_spawn,json=npcSpawn,proto3,oneof"`
}

type WorldEnvelope_NpcDespawn struct {
	NpcDespawn *NpcDespawnEvent `protobuf:"bytes,105,opt,name=npc_despawn,json=npcDespawn,proto3,oneof"`
}

type WorldEnvelope_DoorState struct {
	DoorState *DoorStateEvent `protobuf:"bytes,106,opt,name=door_state,json=doorState,proto3,oneof"`
}

type WorldEnvelope_PacketReceived struct {
	PacketReceived *PacketReceivedEvent `protobuf:"bytes,107,opt,name=packet_received,json=packetReceived,proto3,oneof"`
}

func (*WorldEnvelope_TilePosition) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_Combat) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_Interaction) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_Chat) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_NpcSpawn) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_NpcDespawn) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_DoorState) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_PacketReceived) isWorldEnvelope_Payload() {}

type TilePositionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Plane         int32                  `protobuf:"varint,3,opt,name=plane,proto3" json:"plane,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TilePositionEvent) Reset() {
	*x = TilePositionEvent{}
	mi := &file_events_v1_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TilePositionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TilePositionEvent) ProtoMessage() {}

func (x *TilePositionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TilePositionEvent.ProtoReflect.Descriptor instead.
func (*TilePositionEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{1}
}

func (x *TilePositionEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TilePositionEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TilePositionEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

type CombatEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAccountId int64                  `protobuf:"varint,1,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"` // or 0 if NPC
	TargetNpcId     int32                  `protobuf:"varint,2,opt,name=target_npc_id,json=targetNpcId,proto3" json:"target_npc_id,omitempty"`
	Damage          int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	CombatStyle     string                 `protobuf:"bytes,4,opt,name=combat_style,json=combatStyle,proto3" json:"combat_style,omitempty"` // melee/ranged/magic
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CombatEvent) Reset() {
	*x = CombatEvent{}
	mi := &file_events_v1_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatEvent) ProtoMessage() {}

func (x *CombatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatEvent.ProtoReflect.Descriptor instead.
func (*CombatEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{2}
}

func (x *CombatEvent) GetTargetAccountId() int64 {
	if x != nil {
		return x.TargetAccountId
	}
	return 0
}

func (x *CombatEvent) GetTargetNpcId() int32 {
	if x != nil {
		return x.TargetNpcId
	}
	return 0
}

func (x *CombatEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CombatEvent) GetCombatStyle() string {
	if x != nil {
		return x.CombatStyle
	}
	return ""
}

type InteractionEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAccountId int64                  `protobuf:"varint,1,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	TargetNpcId     int32                  `protobuf:"varint,2,opt,name=target_npc_id,json=targetNpcId,proto3" json:"target_npc_id,omitempty"`
	Action          string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InteractionEvent) Reset() {
	*x = InteractionEvent{}
	mi := &file_events_v1_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionEvent) ProtoMessage() {}

func (x *InteractionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionEvent.ProtoReflect.Descriptor instead.
func (*InteractionEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{3}
}

func (x *InteractionEvent) GetTargetAccountId() int64 {
	if x != nil {
		return x.TargetAccountId
	}
	return 0
}

func (x *InteractionEvent) GetTargetNpcId() int32 {
	if x != nil {
		return x.TargetNpcId
	}
	return 0
}

func (x *InteractionEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ChatMessageEvent struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Channel       ChatMessageEvent_Channel `protobuf:"varint,1,opt,name=channel,proto3,enum=events.v1.ChatMessageEvent_Channel" json:"channel,omitempty"`
	Text          string                   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageEvent) Reset() {
	*x = ChatMessageEvent{}
	mi := &file_events_v1_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageEvent) ProtoMessage() {}

func (x *ChatMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageEvent.ProtoReflect.Descriptor instead.
func (*ChatMessageEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessageEvent) GetChannel() ChatMessageEvent_Channel {
	if x != nil {
		return x.Channel
	}
	return ChatMessageEvent_CHANNEL_UNSPECIFIED
}

func (x *ChatMessageEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NpcSpawnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	NpcType       int32                  `protobuf:"varint,2,opt,name=npc_type,json=npcType,proto3" json:"npc_type,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Plane         int32                  `protobuf:"varint,5,opt,name=plane,proto3" json:"plane,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcSpawnEvent) Reset() {
	*x = NpcSpawnEvent{}
	mi := &file_events_v1_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcSpawnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcSpawnEvent) ProtoMessage() {}

func (x *NpcSpawnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcSpawnEvent.ProtoReflect.Descriptor instead.
func (*NpcSpawnEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{5}
}

func (x *NpcSpawnEvent) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *NpcSpawnEvent) GetNpcType() int32 {
	if x != nil {
		return x.NpcType
	}
	return 0
}

func (x *NpcSpawnEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NpcSpawnEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NpcSpawnEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

type NpcDespawnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcDespawnEvent) Reset() {
	*x = NpcDespawnEvent{}
	mi := &file_events_v1_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcDespawnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcDespawnEvent) ProtoMessage() {}

func (x *NpcDespawnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcDespawnEvent.ProtoReflect.Descriptor instead.
func (*NpcDespawnEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{6}
}

func (x *NpcDespawnEvent) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

type DoorStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocId         int32                  `protobuf:"varint,1,opt,name=loc_id,json=locId,proto3" json:"loc_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Plane         int32                  `protobuf:"varint,4,opt,name=plane,proto3" json:"plane,omitempty"`
	Open          bool                   `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorStateEvent) Reset() {
	*x = DoorStateEvent{}
	mi := &file_events_v1_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorStateEvent) ProtoMessage() {}

func (x *DoorStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorStateEvent.ProtoReflect.Descriptor instead.
func (*DoorStateEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{7}
}

func (x *DoorStateEvent) GetLocId() int32 {
	if x != nil {
		return x.LocId
	}
	return 0
}

func (x *DoorStateEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DoorStateEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DoorStateEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

func (x *DoorStateEvent) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

type PacketReceivedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opcode        uint32                 `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketReceivedEvent) Reset() {
	*x = PacketReceivedEvent{}
	mi := &file_events_v1_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketReceivedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketReceivedEvent) ProtoMessage() {}

func (x *PacketReceivedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketReceivedEvent.ProtoReflect.Descriptor instead.
func (*PacketReceivedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{8}
}

func (x *PacketReceivedEvent) GetOpcode() uint32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *PacketReceivedEvent) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_events_v1_world_proto protoreflect.FileDescriptor

const file_events_v1_world_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/world.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x05\n" +
	"\rWorldEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x19\n" +
	"\bworld_id\x18\x04 \x01(\x05R\aworldId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\x03R\taccountId\x12C\n" +
	"\rtile_position\x18d \x01(\v2\x1c.events.v1.TilePositionEventH\x00R\ftilePosition\x120\n" +
	"\x06combat\x18e \x01(\v2\x16.events.v1.CombatEventH\x00R\x06combat\x12?\n" +
	"\vinteraction\x18f \x01(\v2\x1b.events.v1.InteractionEventH\x00R\vinteraction\x121\n" +
	"\x04chat\x18g \x01(\v2\x1b.events.v1.ChatMessageEventH\x00R\x04chat\x127\n" +
	"\tnpc_spawn\x18h \x01(\v2\x18.events.v1.NpcSpawnEventH\x00R\bnpcSpawn\x12=\n" +
	"\vnpc_despawn\x18i \x01(\v2\x1a.events.v1.NpcDespawnEventH\x00R\n" +
	"npcDespawn\x12:\n" +
	"\n" +
	"door_state\x18j \x01(\v2\x19.events.v1.DoorStateEventH\x00R\tdoorState\x12I\n" +
	"\x0fpacket_received\x18k \x01(\v2\x1e.events.v1.PacketReceivedEventH\x00R\x0epacketReceivedB\t\n" +
	"\apayload\"E\n" +
	"\x11TilePositionEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x03 \x01(\x05R\x05plane\"\x98\x01\n" +
	"\vCombatEvent\x12*\n" +
	"\x11target_account_id\x18\x01 \x01(\x03R\x0ftargetAccountId\x12\"\n" +
	"\rtarget_npc_id\x18\x02 \x01(\x05R\vtargetNpcId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12!\n" +
	"\fcombat_style\x18\x04 \x01(\tR\vcombatStyle\"z\n" +
	"\x10InteractionEvent\x12*\n" +
	"\x11target_account_id\x18\x01 \x01(\x03R\x0ftargetAccountId\x12\"\n" +
	"\rtarget_npc_id\x18\x02 \x01(\x05R\vtargetNpcId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\xaf\x01\n" +
	"\x10ChatMessageEvent\x12=\n" +
	"\achannel\x18\x01 \x01(\x0e2#.events.v1.ChatMessageEvent.ChannelR\achannel\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"H\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCHANNEL_PUBLIC\x10\x01\x12\x10\n" +
	"\fCHANNEL_CLAN\x10\x02\"s\n" +
	"\rNpcSpawnEvent\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\x12\x19\n" +
	"\bnpc_type\x18\x02 \x01(\x05R\anpcType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\x05R\x05plane\"(\n" +
	"\x0fNpcDespawnEvent\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\"m\n" +
	"\x0eDoorStateEvent\x12\x15\n" +
	"\x06loc_id\x18\x01 \x01(\x05R\x05locId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x04 \x01(\x05R\x05plane\x12\x12\n" +
	"\x04open\x18\x05 \x01(\bR\x04open\"A\n" +
	"\x13PacketReceivedEvent\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\rR\x06opcode\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04sizeB&Z$github.com/zsrv/goscape/pkg/eventspbb\x06proto3"

var (
	file_events_v1_world_proto_rawDescOnce sync.Once
	file_events_v1_world_proto_rawDescData []byte
)

func file_events_v1_world_proto_rawDescGZIP() []byte {
	file_events_v1_world_proto_rawDescOnce.Do(func() {
		file_events_v1_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_world_proto_rawDesc), len(file_events_v1_world_proto_rawDesc)))
	})
	return file_events_v1_world_proto_rawDescData
}

var file_events_v1_world_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_v1_world_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_events_v1_world_proto_goTypes = []any{
	(ChatMessageEvent_Channel)(0), // 0: events.v1.ChatMessageEvent.Channel
	(*WorldEnvelope)(nil),         // 1: events.v1.WorldEnvelope
	(*TilePositionEvent)(nil),     // 2: events.v1.TilePositionEvent
	(*CombatEvent)(nil),           // 3: events.v1.CombatEvent
	(*InteractionEvent)(nil),      // 4: events.v1.InteractionEvent
	(*ChatMessageEvent)(nil),      // 5: events.v1.ChatMessageEvent
	(*NpcSpawnEvent)(nil),         // 6: events.v1.NpcSpawnEvent
	(*NpcDespawnEvent)(nil),       // 7: events.v1.NpcDespawnEvent
	(*DoorStateEvent)(nil),        // 8: events.v1.DoorStateEvent
	(*PacketReceivedEvent)(nil),   // 9: events.v1.PacketReceivedEvent
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_events_v1_world_proto_depIdxs = []int32{
	10, // 0: events.v1.WorldEnvelope.ts:type_name -> google.protobuf.Timestamp
	2,  // 1: events.v1.WorldEnvelope.tile_position:type_name -> events.v1.TilePositionEvent
	3,  // 2: events.v1.WorldEnvelope.combat:type_name -> events.v1.CombatEvent
	4,  // 3: events.v1.WorldEnvelope.interaction:type_name -> events.v1.InteractionEvent
	5,  // 4: events.v1.WorldEnvelope.chat:type_name -> events.v1.ChatMessageEvent
	6,  // 5: events.v1.WorldEnvelope.npc_spawn:type_name -> events.v1.NpcSpawnEvent
	7,  // 6: events.v1.WorldEnvelope.npc_despawn:type_name -> events.v1.NpcDespawnEvent
	8,  // 7: events.v1.WorldEnvelope.door_state:type_name -> events.v1.DoorStateEvent
	9,  // 8: events.v1.WorldEnvelope.packet_received:type_name -> events.v1.PacketReceivedEvent
	0,  // 9: events.v1.ChatMessageEvent.channel:type_name -> events.v1.ChatMessageEvent.Channel
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_events_v1_world_proto_init() }
func file_events_v1_world_proto_init() {
	if File_events_v1_world_proto != nil {
		return
	}
	file_events_v1_world_proto_msgTypes[0].OneofWrappers = []any{
		(*WorldEnvelope_TilePosition)(nil),
		(*WorldEnvelope_Combat)(nil),
		(*WorldEnvelope_Interaction)(nil),
		(*WorldEnvelope_Chat)(nil),
		(*WorldEnvelope_NpcSpawn)(nil),
		(*WorldEnvelope_NpcDespawn)(nil),
		(*WorldEnvelope_DoorState)(nil),
		(*WorldEnvelope_PacketReceived)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_world_proto_rawDesc), len(file_events_v1_world_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_world_proto_goTypes,
		DependencyIndexes: file_events_v1_world_proto_depIdxs,
		EnumInfos:         file_events_v1_world_proto_enumTypes,
		MessageInfos:      file_events_v1_world_proto_msgTypes,
	}.Build()
	File_events_v1_world_proto = out.File
	file_events_v1_world_proto_goTypes = nil
	file_events_v1_world_proto_depIdxs = nil
}
