// proto/events/v1/world.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/world.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorldEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	WorldId       int32                  `protobuf:"varint,4,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`       // partition key
	AccountId     int64                  `protobuf:"varint,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 0 for world-scoped events
	// Types that are valid to be assigned to Payload:
	//
	//	*WorldEnvelope_TilePosition
	//	*WorldEnvelope_Combat
	//	*WorldEnvelope_Interaction
	//	*WorldEnvelope_PublicChat
	//	*WorldEnvelope_NpcSpawn
	//	*WorldEnvelope_NpcDespawn
	//	*WorldEnvelope_DoorState
	//	*WorldEnvelope_PacketReceived
	Payload       isWorldEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldEnvelope) Reset() {
	*x = WorldEnvelope{}
	mi := &file_events_v1_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldEnvelope) ProtoMessage() {}

func (x *WorldEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldEnvelope.ProtoReflect.Descriptor instead.
func (*WorldEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{0}
}

func (x *WorldEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *WorldEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WorldEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WorldEnvelope) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *WorldEnvelope) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WorldEnvelope) GetPayload() isWorldEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorldEnvelope) GetTilePosition() *TilePositionEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_TilePosition); ok {
			return x.TilePosition
		}
	}
	return nil
}

func (x *WorldEnvelope) GetCombat() *CombatEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_Combat); ok {
			return x.Combat
		}
	}
	return nil
}

func (x *WorldEnvelope) GetInteraction() *InteractionEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

func (x *WorldEnvelope) GetPublicChat() *PublicChatEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_PublicChat); ok {
			return x.PublicChat
		}
	}
	return nil
}

func (x *WorldEnvelope) GetNpcSpawn() *NpcSpawnEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_NpcSpawn); ok {
			return x.NpcSpawn
		}
	}
	return nil
}

func (x *WorldEnvelope) GetNpcDespawn() *NpcDespawnEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_NpcDespawn); ok {
			return x.NpcDespawn
		}
	}
	return nil
}

func (x *WorldEnvelope) GetDoorState() *DoorStateEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_DoorState); ok {
			return x.DoorState
		}
	}
	return nil
}

func (x *WorldEnvelope) GetPacketReceived() *PacketReceivedEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorldEnvelope_PacketReceived); ok {
			return x.PacketReceived
		}
	}
	return nil
}

type isWorldEnvelope_Payload interface {
	isWorldEnvelope_Payload()
}

type WorldEnvelope_TilePosition struct {
	TilePosition *TilePositionEvent `protobuf:"bytes,100,opt,name=tile_position,json=tilePosition,proto3,oneof"`
}

type WorldEnvelope_Combat struct {
	Combat *CombatEvent `protobuf:"bytes,101,opt,name=combat,proto3,oneof"`
}

type WorldEnvelope_Interaction struct {
	Interaction *InteractionEvent `protobuf:"bytes,102,opt,name=interaction,proto3,oneof"`
}

type WorldEnvelope_PublicChat struct {
	PublicChat *PublicChatEvent `protobuf:"bytes,103,opt,name=public_chat,json=publicChat,proto3,oneof"`
}

type WorldEnvelope_NpcSpawn struct {
	NpcSpawn *NpcSpawnEvent `protobuf:"bytes,104,opt,name=npc_spawn,json=npcSpawn,proto3,oneof"`
}

type WorldEnvelope_NpcDespawn struct {
	NpcDespawn *NpcDespawnEvent `protobuf:"bytes,105,opt,name=npc_despawn,json=npcDespawn,proto3,oneof"`
}

type WorldEnvelope_DoorState struct {
	DoorState *DoorStateEvent `protobuf:"bytes,106,opt,name=door_state,json=doorState,proto3,oneof"`
}

type WorldEnvelope_PacketReceived struct {
	PacketReceived *PacketReceivedEvent `protobuf:"bytes,107,opt,name=packet_received,json=packetReceived,proto3,oneof"`
}

func (*WorldEnvelope_TilePosition) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_Combat) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_Interaction) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_PublicChat) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_NpcSpawn) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_NpcDespawn) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_DoorState) isWorldEnvelope_Payload() {}

func (*WorldEnvelope_PacketReceived) isWorldEnvelope_Payload() {}

type TilePositionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Plane         int32                  `protobuf:"varint,3,opt,name=plane,proto3" json:"plane,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TilePositionEvent) Reset() {
	*x = TilePositionEvent{}
	mi := &file_events_v1_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TilePositionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TilePositionEvent) ProtoMessage() {}

func (x *TilePositionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TilePositionEvent.ProtoReflect.Descriptor instead.
func (*TilePositionEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{1}
}

func (x *TilePositionEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TilePositionEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TilePositionEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

type CombatEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAccountId int64                  `protobuf:"varint,1,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"` // or 0 if NPC
	TargetNpcId     int32                  `protobuf:"varint,2,opt,name=target_npc_id,json=targetNpcId,proto3" json:"target_npc_id,omitempty"`
	Damage          int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	CombatStyle     string                 `protobuf:"bytes,4,opt,name=combat_style,json=combatStyle,proto3" json:"combat_style,omitempty"` // melee/ranged/magic
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CombatEvent) Reset() {
	*x = CombatEvent{}
	mi := &file_events_v1_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatEvent) ProtoMessage() {}

func (x *CombatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatEvent.ProtoReflect.Descriptor instead.
func (*CombatEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{2}
}

func (x *CombatEvent) GetTargetAccountId() int64 {
	if x != nil {
		return x.TargetAccountId
	}
	return 0
}

func (x *CombatEvent) GetTargetNpcId() int32 {
	if x != nil {
		return x.TargetNpcId
	}
	return 0
}

func (x *CombatEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CombatEvent) GetCombatStyle() string {
	if x != nil {
		return x.CombatStyle
	}
	return ""
}

type InteractionEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAccountId int64                  `protobuf:"varint,1,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	TargetNpcId     int32                  `protobuf:"varint,2,opt,name=target_npc_id,json=targetNpcId,proto3" json:"target_npc_id,omitempty"`
	Action          string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InteractionEvent) Reset() {
	*x = InteractionEvent{}
	mi := &file_events_v1_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionEvent) ProtoMessage() {}

func (x *InteractionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionEvent.ProtoReflect.Descriptor instead.
func (*InteractionEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{3}
}

func (x *InteractionEvent) GetTargetAccountId() int64 {
	if x != nil {
		return x.TargetAccountId
	}
	return 0
}

func (x *InteractionEvent) GetTargetNpcId() int32 {
	if x != nil {
		return x.TargetNpcId
	}
	return 0
}

func (x *InteractionEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// PublicChatEvent is the only record of a public-chat utterance — chat
// is Kafka-only (documented TS divergence: TS persists a public_chat DB
// row instead; spec docs/superpowers/specs/2026-07-07-chat-kafka-only-design.md).
type PublicChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WordPack-decoded, UNFILTERED text (TS sets player.logMessage BEFORE
	// the wordenc filter, MessagePublicHandler.ts:32). Kept on field 2 so
	// in-flight Kafka messages decode across the rename.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Player.session per-login UUID; 'headless' when unassigned (TS
	// Player.ts ctor default). No session-validity gate.
	SessionUuid string `protobuf:"bytes,3,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	// coordgrid.PackCoord(level, x, z) at utterance.
	Coord         int32 `protobuf:"varint,4,opt,name=coord,proto3" json:"coord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicChatEvent) Reset() {
	*x = PublicChatEvent{}
	mi := &file_events_v1_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicChatEvent) ProtoMessage() {}

func (x *PublicChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicChatEvent.ProtoReflect.Descriptor instead.
func (*PublicChatEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{4}
}

func (x *PublicChatEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PublicChatEvent) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *PublicChatEvent) GetCoord() int32 {
	if x != nil {
		return x.Coord
	}
	return 0
}

type NpcSpawnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	NpcType       int32                  `protobuf:"varint,2,opt,name=npc_type,json=npcType,proto3" json:"npc_type,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Plane         int32                  `protobuf:"varint,5,opt,name=plane,proto3" json:"plane,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcSpawnEvent) Reset() {
	*x = NpcSpawnEvent{}
	mi := &file_events_v1_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcSpawnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcSpawnEvent) ProtoMessage() {}

func (x *NpcSpawnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcSpawnEvent.ProtoReflect.Descriptor instead.
func (*NpcSpawnEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{5}
}

func (x *NpcSpawnEvent) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *NpcSpawnEvent) GetNpcType() int32 {
	if x != nil {
		return x.NpcType
	}
	return 0
}

func (x *NpcSpawnEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NpcSpawnEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NpcSpawnEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

type NpcDespawnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcDespawnEvent) Reset() {
	*x = NpcDespawnEvent{}
	mi := &file_events_v1_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcDespawnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcDespawnEvent) ProtoMessage() {}

func (x *NpcDespawnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcDespawnEvent.ProtoReflect.Descriptor instead.
func (*NpcDespawnEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{6}
}

func (x *NpcDespawnEvent) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

type DoorStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocId         int32                  `protobuf:"varint,1,opt,name=loc_id,json=locId,proto3" json:"loc_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Plane         int32                  `protobuf:"varint,4,opt,name=plane,proto3" json:"plane,omitempty"`
	Open          bool                   `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorStateEvent) Reset() {
	*x = DoorStateEvent{}
	mi := &file_events_v1_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorStateEvent) ProtoMessage() {}

func (x *DoorStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorStateEvent.ProtoReflect.Descriptor instead.
func (*DoorStateEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{7}
}

func (x *DoorStateEvent) GetLocId() int32 {
	if x != nil {
		return x.LocId
	}
	return 0
}

func (x *DoorStateEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DoorStateEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DoorStateEvent) GetPlane() int32 {
	if x != nil {
		return x.Plane
	}
	return 0
}

func (x *DoorStateEvent) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

type PacketReceivedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opcode        uint32                 `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketReceivedEvent) Reset() {
	*x = PacketReceivedEvent{}
	mi := &file_events_v1_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketReceivedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketReceivedEvent) ProtoMessage() {}

func (x *PacketReceivedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketReceivedEvent.ProtoReflect.Descriptor instead.
func (*PacketReceivedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_world_proto_rawDescGZIP(), []int{8}
}

func (x *PacketReceivedEvent) GetOpcode() uint32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *PacketReceivedEvent) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_events_v1_world_proto protoreflect.FileDescriptor

const file_events_v1_world_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/world.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x05\n" +
	"\rWorldEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x19\n" +
	"\bworld_id\x18\x04 \x01(\x05R\aworldId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\x03R\taccountId\x12C\n" +
	"\rtile_position\x18d \x01(\v2\x1c.events.v1.TilePositionEventH\x00R\ftilePosition\x120\n" +
	"\x06combat\x18e \x01(\v2\x16.events.v1.CombatEventH\x00R\x06combat\x12?\n" +
	"\vinteraction\x18f \x01(\v2\x1b.events.v1.InteractionEventH\x00R\vinteraction\x12=\n" +
	"\vpublic_chat\x18g \x01(\v2\x1a.events.v1.PublicChatEventH\x00R\n" +
	"publicChat\x127\n" +
	"\tnpc_spawn\x18h \x01(\v2\x18.events.v1.NpcSpawnEventH\x00R\bnpcSpawn\x12=\n" +
	"\vnpc_despawn\x18i \x01(\v2\x1a.events.v1.NpcDespawnEventH\x00R\n" +
	"npcDespawn\x12:\n" +
	"\n" +
	"door_state\x18j \x01(\v2\x19.events.v1.DoorStateEventH\x00R\tdoorState\x12I\n" +
	"\x0fpacket_received\x18k \x01(\v2\x1e.events.v1.PacketReceivedEventH\x00R\x0epacketReceivedB\t\n" +
	"\apayload\"E\n" +
	"\x11TilePositionEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x03 \x01(\x05R\x05plane\"\x98\x01\n" +
	"\vCombatEvent\x12*\n" +
	"\x11target_account_id\x18\x01 \x01(\x03R\x0ftargetAccountId\x12\"\n" +
	"\rtarget_npc_id\x18\x02 \x01(\x05R\vtargetNpcId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12!\n" +
	"\fcombat_style\x18\x04 \x01(\tR\vcombatStyle\"z\n" +
	"\x10InteractionEvent\x12*\n" +
	"\x11target_account_id\x18\x01 \x01(\x03R\x0ftargetAccountId\x12\"\n" +
	"\rtarget_npc_id\x18\x02 \x01(\x05R\vtargetNpcId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"d\n" +
	"\x0fPublicChatEvent\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\fsession_uuid\x18\x03 \x01(\tR\vsessionUuid\x12\x14\n" +
	"\x05coord\x18\x04 \x01(\x05R\x05coordJ\x04\b\x01\x10\x02\"s\n" +
	"\rNpcSpawnEvent\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\x12\x19\n" +
	"\bnpc_type\x18\x02 \x01(\x05R\anpcType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\x05R\x05plane\"(\n" +
	"\x0fNpcDespawnEvent\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\"m\n" +
	"\x0eDoorStateEvent\x12\x15\n" +
	"\x06loc_id\x18\x01 \x01(\x05R\x05locId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05plane\x18\x04 \x01(\x05R\x05plane\x12\x12\n" +
	"\x04open\x18\x05 \x01(\bR\x04open\"A\n" +
	"\x13PacketReceivedEvent\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\rR\x06opcode\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04sizeB&Z$github.com/zsrv/goscape/pkg/eventspbb\x06proto3"

var (
	file_events_v1_world_proto_rawDescOnce sync.Once
	file_events_v1_world_proto_rawDescData []byte
)

func file_events_v1_world_proto_rawDescGZIP() []byte {
	file_events_v1_world_proto_rawDescOnce.Do(func() {
		file_events_v1_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_world_proto_rawDesc), len(file_events_v1_world_proto_rawDesc)))
	})
	return file_events_v1_world_proto_rawDescData
}

var file_events_v1_world_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_events_v1_world_proto_goTypes = []any{
	(*WorldEnvelope)(nil),         // 0: events.v1.WorldEnvelope
	(*TilePositionEvent)(nil),     // 1: events.v1.TilePositionEvent
	(*CombatEvent)(nil),           // 2: events.v1.CombatEvent
	(*InteractionEvent)(nil),      // 3: events.v1.InteractionEvent
	(*PublicChatEvent)(nil),       // 4: events.v1.PublicChatEvent
	(*NpcSpawnEvent)(nil),         // 5: events.v1.NpcSpawnEvent
	(*NpcDespawnEvent)(nil),       // 6: events.v1.NpcDespawnEvent
	(*DoorStateEvent)(nil),        // 7: events.v1.DoorStateEvent
	(*PacketReceivedEvent)(nil),   // 8: events.v1.PacketReceivedEvent
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_events_v1_world_proto_depIdxs = []int32{
	9, // 0: events.v1.WorldEnvelope.ts:type_name -> google.protobuf.Timestamp
	1, // 1: events.v1.WorldEnvelope.tile_position:type_name -> events.v1.TilePositionEvent
	2, // 2: events.v1.WorldEnvelope.combat:type_name -> events.v1.CombatEvent
	3, // 3: events.v1.WorldEnvelope.interaction:type_name -> events.v1.InteractionEvent
	4, // 4: events.v1.WorldEnvelope.public_chat:type_name -> events.v1.PublicChatEvent
	5, // 5: events.v1.WorldEnvelope.npc_spawn:type_name -> events.v1.NpcSpawnEvent
	6, // 6: events.v1.WorldEnvelope.npc_despawn:type_name -> events.v1.NpcDespawnEvent
	7, // 7: events.v1.WorldEnvelope.door_state:type_name -> events.v1.DoorStateEvent
	8, // 8: events.v1.WorldEnvelope.packet_received:type_name -> events.v1.PacketReceivedEvent
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_events_v1_world_proto_init() }
func file_events_v1_world_proto_init() {
	if File_events_v1_world_proto != nil {
		return
	}
	file_events_v1_world_proto_msgTypes[0].OneofWrappers = []any{
		(*WorldEnvelope_TilePosition)(nil),
		(*WorldEnvelope_Combat)(nil),
		(*WorldEnvelope_Interaction)(nil),
		(*WorldEnvelope_PublicChat)(nil),
		(*WorldEnvelope_NpcSpawn)(nil),
		(*WorldEnvelope_NpcDespawn)(nil),
		(*WorldEnvelope_DoorState)(nil),
		(*WorldEnvelope_PacketReceived)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_world_proto_rawDesc), len(file_events_v1_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_world_proto_goTypes,
		DependencyIndexes: file_events_v1_world_proto_depIdxs,
		MessageInfos:      file_events_v1_world_proto_msgTypes,
	}.Build()
	File_events_v1_world_proto = out.File
	file_events_v1_world_proto_goTypes = nil
	file_events_v1_world_proto_depIdxs = nil
}
