{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "goscape.fullname" . }}
  labels:
    {{- include "goscape.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "goscape.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if eq .Values.deploymentMode "Management" }}
    # Allow gRPC only from goscape world/single-binary pods in this namespace
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "goscape.name" . }}
      ports:
        - port: {{ .Values.goscape.ports.loginGRPC }}
          protocol: TCP
        - port: {{ .Values.goscape.ports.friendsGRPC }}
          protocol: TCP
    {{- else }}
    # Allow client-facing ports from anywhere
    - ports:
        - port: {{ .Values.goscape.ports.ondemandHTTP }}
          protocol: TCP
        - port: {{ .Values.goscape.ports.worldTCP }}
          protocol: TCP
    {{- end }}
{{- end }}
