"""Markdown rendering helpers for generated reference pages."""
from pathlib import Path

GENERATED = "<!-- GENERATED by tools/docsgen — do not edit; regenerate instead. -->"


def md_escape(s: str) -> str:
    return s.replace("\n", " ").replace("|", "\\|")


def _display_name(rec: dict) -> str:
    name = rec.get("name") or rec["_debugname"]
    return name if isinstance(name, str) else name[0]


def render_chunked_family(records, family, title, columns, row_fn,
                          out_dir: Path, chunk: int = 500):
    out_dir.mkdir(parents=True, exist_ok=True)
    header = f"| {' | '.join(columns)} |\n|{'---|' * len(columns)}\n"
    entries: list[tuple[str, str]] = []
    rel_base = f"player/{family}"
    chunks = [records[i:i + chunk] for i in range(0, len(records), chunk)]

    for n, part in enumerate(chunks, start=1):
        first, last = _display_name(part[0]), _display_name(part[-1])
        label = f"page {n} ({first} – {last})"
        rows = "".join(
            f"| {' | '.join(md_escape(c) for c in row_fn(r))} |\n" for r in part
        )
        body = (
            f"{GENERATED}\n\n# {title} — {label}\n\n{header}{rows}"
        )
        (out_dir / f"page-{n:03d}.md").write_text(body)
        entries.append((label, f"{rel_base}/page-{n:03d}.md"))

    toc = "".join(
        f"- [{label}]({rel.rsplit('/', 1)[1]})\n" for label, rel in entries
    )
    (out_dir / "index.md").write_text(
        f"{GENERATED}\n\n# {title}\n\n{len(records)} entries "
        f"in {len(chunks)} pages.\n\n{toc}"
    )
    return entries


def render_nav_fragment(sections):
    lines: list[str] = []
    for label, index_rel, chunk_entries in sections:
        lines.append(f"      - {label}:")
        lines.append(f"          - {index_rel}")
        for entry_label, rel in chunk_entries:
            lines.append(f'          - "{entry_label}": {rel}')
    return "\n".join(lines)
