# .github/workflows/buf.yml
name: buf

on:
  pull_request:
    paths:
      - "proto/**"
      - "buf.yaml"
      - "buf.gen.yaml"
      - ".github/workflows/buf.yml"
  push:
    branches: [main]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # buf breaking needs history
      - uses: bufbuild/buf-action@v1
        with:
          breaking_against: "https://github.com/${{ github.repository }}.git#branch=main,subdir=."
